### ISSUE TITLE
Get Regional ChannelList

### ISSUE THREAD

**Issue by truered2** [Arcana/node-dota2#250]
How I get regional channel list? CMsgDOTARequestChatChannelList return only custom chat channels. 
![0ulxbsk](https://cloud.githubusercontent.com/assets/17601514/13474330/35b21d62-e0c6-11e5-8252-cfb388b07394.png)

**Comment by jimmydorry** [comment]
You may need to implement this function into the chat handler.

https://github.com/RJacksonm1/node-dota2/blob/dev/proto/dota_gcmessages_client.proto#L1255

https://github.com/RJacksonm1/node-dota2/blob/dev/handlers/chat.js

If that does not work, you will need to see what method and what data your client is using. Use nethook https://github.com/RJacksonm1/node-dota2/wiki

Please let us know what works, so the library improves.

**Comment by truered2** [comment]
Method regionEnabled did not help. I'll use nethook.
![screenshot_2](https://cloud.githubusercontent.com/assets/17601514/13487794/513d6f6e-e125-11e5-815a-b8ffa194b9be.png)
![screenshot_6](https://cloud.githubusercontent.com/assets/17601514/13487793/513a884e-e125-11e5-81e5-98c90153de58.png)

**Comment by jimmydorry** [comment]
It has a required parameter of enabled_regions. It's definitely worth using nethook though, to confirm what is required.

**Comment by Crazy-Duck** [comment]
Been trying some stuff as well, but don't seem to get any response for regional channels as well. We're gonna have to nethook.

Example request
```
Dota2.Dota2Client.prototype.enableAllChatRegions = function() {
    /* Requests a list of chat channels from the GC. */
    if (this.debug) util.log("Enabling all chat regions");
    
    var payload = new Dota2.schema.CMsgDOTAChatRegionsEnabled ({
        enable_all_regions: true
    });
    this.sendToGC(Dota2.schema.EDOTAGCMsg.k_EMsgGCToClientChatRegionsEnabled, payload);
};
```

**Comment by jimmydorry** [comment]
If I am reading it correctly, it's the complicated enabled_regions bit that is mandatory... not the optional bool for all_regions. ;)

**Comment by Crazy-Duck** [comment]
derp, anyways, I tried this as well, but it's equally ineffective
```
Dota2.Dota2Client.prototype.enableAllChatRegions = function() {
    /* Requests a list of chat channels from the GC. */
    if (this.debug) util.log("Disabling all chat regions");
    
    var payload = new Dota2.schema.CMsgDOTAChatRegionsEnabled ({
        "enabled_regions": [{
            "min_latitude": -90.0000,
            "max_latitude": 90.0000,
            "min_longitude": -180.0000,
            "max_longitude": 180.0000
        }]
    });
    this.sendToGC(Dota2.schema.EDOTAGCMsg.k_EMsgGCToClientChatRegionsEnabled, payload);
};
```

**Comment by Crazy-Duck** [comment]
Might be that those regions need to have specific predefined min/max values -> TBD with nethook

**Comment by jimmydorry** [comment]
Seattle is 47.6097° N, 122.3331° W

But yes, will have to see what nethook says. I should get a chance on the weekend.

**Comment by truered2** [comment]
I download NetHook2 old pre-compiled version and NetHook2.dll . After dowloading, I move NetHook2 to "C:\Program Files (x86)\Steam\NetHook2.dll". I launched Steam and Dota2. After, I run "C:\Program Files (x86)\Steam\nethook\NetHookAnalyzer2.exe" and paste in cmd(admin) "rundll32 C:\Program Files (x86)\Steam\NetHook2.dll,Inject"
![screenshot_3](https://cloud.githubusercontent.com/assets/17601514/13586782/bd3dee2e-e4cb-11e5-90b6-07d0aeac7f23.png)

 but cmd write "Not found module", why?

![screenshot_1](https://cloud.githubusercontent.com/assets/17601514/13586842/2ae884de-e4cc-11e5-8bb0-e007eecb46c7.png)

Sorry my bad english.

**Comment by jimmydorry** [comment]
Is that the exact error? And is your steam running?

**Comment by truered2** [comment]
Yes. Steam and Dota2 running. Screenshot error, but error russian, "Not found module".

![screenshot_2](https://cloud.githubusercontent.com/assets/17601514/13587129/96428fca-e4ce-11e5-955c-48d91b9f487f.png)

**Comment by jimmydorry** [comment]
Can you try it in a path that doesn't have a space? I haven't seen that issue before... but perhaps the nethook module is too far out of date. :(

**Comment by truered2** [comment]
Yes. Screenshots:
![screenshot_4](https://cloud.githubusercontent.com/assets/17601514/13587240/89906fc6-e4cf-11e5-9ddd-e305cd1c567a.png)
![screenshot_5](https://cloud.githubusercontent.com/assets/17601514/13587245/8df20ff2-e4cf-11e5-95e6-894ca672eca4.png)

**Comment by truered2** [comment]
Windows 7 does not see NetHook2.dll. It's a problem.

**Comment by jimmydorry** [comment]
If you right click on the NetHook2.dll ... there isn't something silly like an "unblock" menu item? You may need to go into properties, via right click.

**Comment by truered2** [comment]
What do you use the os system? I not found "unblock", I have given all user rights for file, but problem is not lost.

**Comment by jimmydorry** [comment]
Alright, I'll try and find some time to look at it tonight. It could simply be a case of the compiled nethook being too old.

**Comment by truered2** [comment]
Thanks.

**Comment by jimmydorry** [comment]
Yea it looks to be too old. @imayhaveborkedit Are you able to run nethook?

**Comment by truered2** [comment]
Okey. NetHook don't work, but name issue - GetRegionalChannelList. Without nethook, how I get protobuf data dota2?

**Comment by jimmydorry** [comment]
If you just want the schemas, they are all in in the protos folder... and the ones you want are around this line https://github.com/RJacksonm1/node-dota2/blob/dev/proto/dota_gcmessages_client.proto#L1255

If you mean the raw data and actual messages the client sends... then nethook is the only way. You need to compile a new version, which is straight forward if you have visual studio installed. If you want to have a go, it's here: https://github.com/SteamRE/SteamKit/tree/master/Resources/NetHook2

**Comment by truered2** [comment]
CMsgDOTAChatRegionsEnabled don't help. You use the NetHook without any problems?

**Comment by jimmydorry** [comment]
No, same error. It needs to be recompiled.

**Comment by truered2** [comment]
Maybe, you know. Dota2 return 200 channels within a radius of 200 kilometers of my geolocation. Is it possible to change the limit 200 channels to 1000 channel, for example?

**Comment by jimmydorry** [comment]
I don't know. It needs to be nethooked.

**Comment by imayhaveborkedit** [comment]
My nethook still works fine. I'll see if I can find what we need here.

**Comment by jimmydorry** [comment]
That's weird. It used to work for me, but doesn't any more (it's been months since I last used it)... but it works for you. :(

**Comment by truered2** [comment]
imayhaveborkedit, you use old pre-compiled version or you recompiled nethook and use new version?

**Comment by ZiRoger** [comment]
I just figured out how to get the regional channel list. You can never get the list through nethook, since it is saved in a vpk file which locates 

> "{dota2 dir}\game\dota\pak01_dir.vpk"

 And then you will need GCFScape.exe to extract the file 

> "root\scripts\chat_regions.txt"

I have uploaded the file
[chat_regions.txt](https://github.com/RJacksonm1/node-dota2/files/392029/chat_regions.txt)

**Comment by Crazy-Duck** [comment]
Chat regions with their coordinates can be found online [here](https://github.com/SteamDatabase/GameTracking/blob/master/dota/game/dota/pak01_dir/scripts/chat_regions.txt). This file is kept up to date with the game files automatically

**Comment by liesnikov** [comment]
the file is here now, in case anyone is looking for it

https://github.com/SteamDatabase/GameTracking-Dota2/blob/master/game/dota/pak01_dir/scripts/chat_regions.txt
