### ISSUE TITLE
Example dota2 require error

### ISSUE THREAD

**Issue by rsage28** [Arcana/node-dota2#296]
I am trying to run the example files, and it returns this error on the line where it tries to require the dota2 module. 
```
Cannot read property 'k_EMsgGCClientWelcome' of undefined
    at Object.<anonymous> (dota2\index.js:163:39)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (dota2\examples\example2.js:8:10)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```
I also get this when trying to run the test file. What I have in the config file does not seem to affect the output of the test or the example. 
```
Steam
    #connect
      √ should connect to Steam (393ms)
    #login
{ eresult: 5,
  eresult_extended: 5,
  client_supplied_steamid: '76561197960265728',
  count_loginfailures_to_migrate: 0,
  count_disconnects_to_migrate: 0 }
      1) should login to Steam

  Dota2
    2) "before all" hook


  1 passing (11s)
  2 failing

  1) Steam #login should login to Steam:
     Uncaught Error: Disconnected
      at SteamClient._disconnected (steam\lib\steam_client.js:186:24)
      at TCP._onclose (net.js:477:12)

  2) Dota2 "before all" hook:
     Error: timeout of 10000ms exceeded. Ensure the done() callback is being called in this test.
      at null.<anonymous> (mocha\lib\runnable.js:226:19)
```
JavaScript is not my forte, could somebody shed some light on this for me please?

**Comment by jimmydorry** [comment]
Which example did you run? Did you make a config file? Not enough info to help you.

**Comment by Crazy-Duck** [comment]
From the test file it seems you get an `eresult: 5`. If you check out handlers\helper.js, you'll see this: `k_EResultInvalidPassword : 5, // password/ticket is invalid`. So imma hazard a guess and say you've made a typo in your password.

**Comment by jimmydorry** [comment]
`test.js` is the one that users shouldn't run... as it's for coverage testing. Simply running it will give the error 5, as no one should know its password, except travis.

We need more info on why the first script he run didn't work, as we literally have no idea what he did.

**Comment by Crazy-Duck** [comment]
You can run test.js locally if you want though, it suffices to set the `STEAM_USERNAME` and  `STEAM_PASSWORD` environment variables. I do it all the time when I'm making new pulls. However I agree that it's pretty much useless if you want to actually see an example of how to use the library. I might rearrange the README at one point to put those two paragraphs at the end at the top.

**Comment by Crazy-Duck** [comment]
@chardzard if you're running example2.js, make sure that the reference to node-dota2 is correct. In the version on the master and dev branches it references `require('./')` instead of `require('../')` (artifact of when the file was located at the root of the repo. I've made pull #297 to fix this.

**Comment by chardzard** [comment]
I get the same error when running both example files. @Crazy-Duck I did change that, and I still get the error shown. It points me to an error in index.js that I'm not sure what it means. I am attempting to write a chat bot that will monitor a chat to send invites a private chat lobby. 

I just read in the README about running the test file, so I was trying it out. Good to know I don't need to touch it. I thought that was what was used to determine if everything was setup correctly.

**Comment by Crazy-Duck** [comment]
@chardzard can you list the exact steps you've taken when you're trying to set up the example files? The correct way to set things up to execute the example files is

1. install latest version of node js (either 4.4.7 or 6.2.2)
1. clone the repo
1. navigate to the repository root
1. npm install steam (not sure if this is still necessary, but it can't hurt)
1. npm install
1. create a config.js file in the examples directory. You can see some example contents in config.js.example
1. run either node examples/example.js or node/examples/example.js

If you want to start using the library in an existing project, just do an `npm install --save dota2`. From then on you can require the library in your project.

**Comment by howardchung** [comment]
if steam is listed in package.json, then npm install will install it.

**Comment by Crazy-Duck** [comment]
There used to be an issue which required you to install steam separately as well. If this is no longer applicable, I'll remove that part from the README :)

**Comment by howardchung** [comment]
Once upon a time, it was a peerDependency instead of a dependency:

https://github.com/RJacksonm1/node-dota2/commit/d9d5f956a52fa7dce842a414d667dac2a4d1c2d8#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R9

**Comment by Crazy-Duck** [comment]
Alright, I'll remove that from the README then next time I'm doing a pull

**Comment by Crazy-Duck** [comment]
Stale issue, reopen if still relevant
