### ISSUE TITLE
Incompatibility with node-steam-user

### ISSUE THREAD

**Issue by SmaugTheGreat** [Arcana/node-dota2#307]
When I try to use node-steam-user together with node-steam and node-dota2, it gets stuck on "Sending ClientHello". I don't know whether it is node-steam-user's fault or node-dota2's fault.

Code:
```
"use strict";

let SteamUser = require("steam-user");
let Steam = require("steam");
let Dota2 = require("dota2");

let steamClient = new Steam.SteamClient();
let dota2 = new Dota2.Dota2Client(steamClient, true, true);

steamClient.on("error", (e) => {
    console.log(e);
});

steamClient.on('connected', (err) => {
    console.log("Connected.");
    let user = new SteamUser(steamClient);
    user.logOn({
        account_name: accName,
        password: accPassword
    });
});

steamClient.on('logOnResponse', () => {
    console.log("Logged in!");
    dota2.launch();
});

steamClient.connect();
```
Output:
```
Connected.
Logged in!
10 Jul 20:32:05 - Launching Dota 2
10 Jul 20:32:06 - Sending ClientHello
10 Jul 20:32:11 - Sending ClientHello
10 Jul 20:32:17 - Sending ClientHello
10 Jul 20:32:23 - Sending ClientHello
10 Jul 20:32:29 - Sending ClientHello
```

**Comment by jimmydorry** [comment]
Those need to be var, not let... I believe.

Try running the example.js with working config.js

**Comment by SmaugTheGreat** [comment]
The example works because it is not using node-steam-user. The problem only occurs with node-steam-user, but not with the normal Steam.SteamUser.

As I said, I am not sure whether this is because of node-dota2 or because of node-steam-user, but one of these two libs doesn't seem to work with the other.

Replacing the let's with var didn't have any effect.

**Comment by Crazy-Duck** [comment]
Here's what I *think* is happening: by using a third party library to log in the steam user, the node-steam client instance does not get properly logged in. Since node-dota2 relies on having a logged in node-steam client instance to be able to send messages to the Dota 2 Game Coordinator, node-dota2 can never establish a connection with the GC

**Comment by Crazy-Duck** [comment]
Stale issue, reopen if issue still relevant

**Comment by markrmessmore** [comment]
I'm in a similar spot as the OP. I spent time transitioning my whole project from the node-steam library to node-steam-user. However when incorporating node-dota2 I have the following error:


`if (str.length === 0)
               ^

TypeError: Cannot read property 'length' of undefined
    at new fromString (C:\Users\markr\Google Drive\Personal\WLDL\wldleague\node_modules\long\dist\long.js:244:16)
    at Dota2Client.Dota2.Dota2Client.ToAccountID (C:\Users\markr\Google Drive\Personal\WLDL\wldleague\node_modules\dota2\index.js:218:12)
    at Dota2Client.Dota2.Dota2Client.launch (C:\Users\markr\Google Drive\Personal\WLDL\wldleague\node_modules\dota2\index.js:238:27)
    at SteamUser.steamUserClient.on (C:\Users\markr\Google Drive\Personal\WLDL\wldleague\dota2\dotaBot.js:52:11)
    at emitTwo (events.js:106:13)
    at SteamUser.emit (events.js:194:7)
    at SteamUser._handlers.(anonymous function) (C:\Users\markr\Google Drive\Personal\WLDL\wldleague\node_modules\steam-user\components\logon.js:310:9)
    at SteamUser._handleMessage (C:\Users\markr\Google Drive\Personal\WLDL\wldleague\node_modules\steam-user\components\messages.js:213:29)
    at emitThree (events.js:116:13)
    at CMClient.emit (events.js:197:7)`

The more I've investigated and looked at the coding of the library it seems like node-dota2 isn't just awaiting some basic login information but truly is built around the steam library. Without a re-write I don't believe the two are truly compatible. However I'm following up here out of curiosity to see if anyone has come up with any solution for this. Thanks.

**Comment by andresrivero** [comment]
A solution for your out-of-band rewrite? Sure, if you would post some actual code. I think people would help you, otherwise, I'm not sure how a solution would exist or even be created.

**Comment by jimmydorry** [comment]
It's out of scope any way. Looking at those errors and the issue appears to be with `node_modules\steam-user\...`.

Not only do you need to attach code, you probably need to be asking the steam-user devs.

**Comment by markrmessmore** [comment]
For posterity I **THINK** I've got it working. The pertinent code can be seen [here](https://www.reddit.com/r/SteamBot/comments/6ckhe8/question_has_anyone_successfully_used_nodedota2/):

**Comment by jimmydorry** [comment]
Good to see you found a solution.

**Comment by jimmydorry** [comment]
Good to see you found a solution. The best idea would be to post the code snippet here, in case that thread gets archived or lost. It would also keep the content together.

**Comment by markrmessmore** [comment]
`//LOAD LIBRARIES & Files
var util              =   require("util"),
    fs                =   require("fs"),
    crypto            =   require("crypto"),
    dota2             =   require("dota2"),
    steamUser         =   require('steam-user'),
    steamTotp         =   require("steam-totp"),
    steamCommunity    =   require('steamcommunity'),
    tradeOfferManager =   require('steam-tradeoffer-manager'),
    dotaTrades        =   require('./dotaTrades.js'),
    steamAddFriend    =   require("./steamAddFriend.js"),
    steamMsg          =   require("./steamMsg.js"),
    SteamID           =   require('steamid'),
    dota2             =   require('dota2');

//CREATE CLIENTS
var steamUserClient         =   new steamUser(),
     steamClient             =   steamUserClient.client,
     Dota2                   =   new dota2.Dota2Client(steamClient, true, false),
     steamCommunityClient    =   new steamCommunity(),
     tradeManager            =   new tradeOfferManager({
          "steam":      steamUserClient,
          "language":   'en'
     });

exports.run = function (settings, mongo, mongoClient, assert, Discord, discordClient) {

// Get logOn information
  var logOnDetails = {
       accountName: settings.steamBotUsername,
       password: settings.steamBotPswd,
       twoFactorCode: steamTotp.generateAuthCode(settings.steamSharedSecret)
  };

//Use the credentials and log in.
  steamUserClient.logOn(logOnDetails);

  steamUserClient.on('loggedOn', () => {
   console.log('Logged into Steam');
  steamUserClient.setPersona(steamUser.Steam.EPersonaState.Online, settings.steamBotNickname);
  Dota2.launch();
  Dota2.on("ready", function() {
    console.log("Dota2 ready.");
  });
  Dota2.on("unready", function onUnready() {
    console.log("Node-dota2 unready.");
  });
  Dota2.on("unhandled", function(kMsg) {
    util.log("UNHANDLED MESSAGE " + dota2._getMessageName(kMsg));
  });
});``
