### ISSUE TITLE
Valve: Stop making gambling sites via Valve infrastructure

### ISSUE THREAD

**Issue by jimmydorry** [Arcana/node-dota2#308]
http://store.steampowered.com/news/22883/
# In-Game Item Trading Update [13 Jul]

In 2011, we added a feature to Steam that enabled users to trade in-game items as a way to make it easier for people to get the items they wanted in games featuring in-game economies.

Since then a number of gambling sites started leveraging the Steam trading system, and there’s been some false assumptions about our involvement with these sites. We’d like to clarify that we have no business relationships with any of these sites. We have never received any revenue from them. And Steam does not have a system for turning in-game items into real world currency.

These sites have basically pieced together their operations in a two-part fashion. First, they are using the OpenID API as a way for users to prove ownership of their Steam accounts and items. Any other information they obtain about a user's Steam account is either manually disclosed by the user or obtained from the user’s Steam Community profile (when the user has chosen to make their profile public). Second, they create automated Steam accounts that make the same web calls as individual Steam users. 

Using the OpenID API and making the same web calls as Steam users to run a gambling business is not allowed by our API nor our user agreements. We are going to start sending notices to these sites requesting they cease operations through Steam, and further pursue the matter as necessary. Users should probably consider this information as they manage their in-game item inventory and trade activity.

-Erik Johnson

**Comment by howardchung** [comment]
Clearly we need to add a patch that checks the hostname of the machine running the library and refuses to run if it detects anything gambling related. :)

**Comment by jimmydorry** [comment]
Haha. Well, let's all be careful. 

This opening shot against gambling sites is but just the first step Valve could take that could negatively impact all of us.

It would be a shame if they end up just doing a blanket ban on all kinds of bots.

**Comment by Crazy-Duck** [comment]
Thing is, I could actually see them going that way. For the moment they still rely on bots to organize their open qualifiers (I think FaceIt uses @paralin 's library), however now that they're starting to experiment with the weekend tourneys, I could very well see them organizing these themselves in the future. Once They don't rely on them anymore, they could start banning them...

**Comment by jimmydorry** [comment]
Absolutely :(

**Comment by Crazy-Duck** [comment]
It would be a shame though, there's a lot of communities that are maintained by bots, lots of cool functionality as well. Not to mention quite a few streamers who use them to inform chat of MMR stats etc..

**Comment by Esssport** [comment]
> (I think FaceIt uses @paralin 's library)
@Crazy-Duck May I ask which library it is? I'm looking at his github profile and he has a lot of repositories, is it protobuf.js? I'd love to take a look at the code.

**Comment by paralin** [comment]
@Esssport https://github.com/paralin/dota2

**Comment by Esssport** [comment]
@paralin Thank you very much.
