### ISSUE TITLE
respondPartyInvite not wotking

### ISSUE THREAD

**Issue by Prosto-Sanja** [Arcana/node-dota2#326]
Hello,
`Dota2.respondPartyInvite(party.group_id, false);`
 is not working properly, and throws
`Error: .CMsgPartyInviteResponse#as_coach is not a field: undefined`
As i understand, it just tries to use a wrong proto file, but i dont know how they work, so any suggestions??

**Comment by Prosto-Sanja** [comment]
Found fix temporary fix, changing 
`// Methods`
`Dota2.Dota2Client.prototype.respondPartyInvite = function(id, accept) {`

to this solves problem, but i think it is temporary solution only

_var payload = new Dota2.schema.CMsgPartyInviteResponse({
        "party_id": id,
        "accept": accept
    });_

**Comment by Crazy-Duck** [comment]
The new protobuf seems to be
```
message CMsgClientPingData {
	repeated fixed32 relay_codes = 4 [packed = true];
	repeated uint32 relay_pings = 5 [packed = true];
	repeated uint32 region_codes = 8 [packed = true];
	repeated uint32 region_pings = 9 [packed = true];
	optional uint32 region_ping_failed_bitmask = 10;
}
message CMsgPartyInviteResponse {
	optional uint64 party_id = 1;
	optional bool accept = 2;
	optional uint32 client_version = 3;
	optional .CMsgClientPingData ping_data = 8;
}
```
`as_coach`, `team_id`, `game_language_enum`, `game_language_name` have been removed in a recent update. We're gonna have to find out how the ping_data is determined, seems like nethook time!

**Comment by Prosto-Sanja** [comment]
I made a tempoorary pull request, it all seems to workwit only two parameters, i tested.
