### ISSUE TITLE
Is there any way that I can get skill bracket?

### ISSUE THREAD

**Issue by gerlaic** [Arcana/node-dota2#329]
I know the skill bracket was in valve's api and the return info from requestMatchDetails() but it looks like it has been gone for a while. Is there any other way that I can find it? #

**Comment by Crazy-Duck** [comment]
@howardchung how do you guys obtain the skill bracket for a game? Do you grab it from the replay?

**Comment by howardchung** [comment]
No, you can use the GetMatchHistory endpoint with a skill parameter to get up to 500 recent matches in that skill bracket.  I describe it briefly here: https://blog.yasp.co/2016/05/15/architecture/

**Comment by Crazy-Duck** [comment]
The equivalent in node-dota2 is `requestMatches` in [handlers\match.js](https://github.com/Arcana/node-dota2/blob/staging/handlers/match.js).

**Comment by howardchung** [comment]
I have not confirmed that endpoint can be filtered by/contains skill.

In any case, to get skill data for a lot of matches you need to make a lot
of calls rapidly (since you can only get the last 500, if you don't get the
skill for a match before it moves out of the window, you're out of luck),
you may not want to do this to the GC.

**Comment by Crazy-Duck** [comment]
It's one of the optional criteria you can specify when you make the call:
```
message CMsgDOTARequestMatches {
	enum SkillLevel {
		Any = 0;
		Normal = 1;
		High = 2;
		VeryHigh = 3;
	}

	optional uint32 hero_id = 2;
	optional uint32 game_mode = 3;
	optional fixed32 date_min = 6;
	optional fixed32 date_max = 7;
	optional uint32 matches_requested = 10;
	optional uint64 start_at_match_id = 11;
	optional fixed32 min_players = 12;
	optional uint32 request_id = 13;
	optional bool tournament_games_only = 14;
	optional uint32 account_id = 15;
	optional uint32 league_id = 16;
	optional .CMsgDOTARequestMatches.SkillLevel skill = 17 [default = Any];
	optional uint32 team_id = 18;
	optional uint64 custom_game_id = 20;
}
```

Then again, I agree that one should be nice to the GC and that the webAPI might be better suited for this.

**Comment by Crazy-Duck** [comment]
@gerlaic did this sufficiently answer your question?

**Comment by gerlaic** [comment]
Yeah this is good enough:D
Thanks! I'll close the thread.
