### ISSUE TITLE
Player panel.

### ISSUE THREAD

**Issue by kprodinfo** [Arcana/node-dota2#333]
How to take the data specified in the panel player? marked in red
![8a03f95e-6e00-11e6-888e-c1585abde6eb](https://cloud.githubusercontent.com/assets/20172275/18052711/254ddf18-6e26-11e6-9fde-bc4783fdb170.png)

Help me please!

**Comment by Crazy-Duck** [comment]
Use `requestProfileCard` in [handlers\community.js](https://github.com/Arcana/node-dota2/blob/staging/handlers/community.js)

**Comment by kprodinfo** [comment]
Example plz, I noon :(

**Comment by Crazy-Duck** [comment]
Take a look at [examples\example.js](https://github.com/Arcana/node-dota2/blob/staging/examples/example.js), it contains an example of how to call this function.
