### ISSUE TITLE
Returns the number of duplicate values

### ISSUE THREAD

**Issue by kprodinfo** [Arcana/node-dota2#334]
I need to get data from multiple profiles.

But this request:
```
	Dota2.requestProfileCard(Dota2.ToAccountID('76561198021206461'));
	Dota2.on("profileCardData", function (accountId, profileData) {
		console.log(JSON.stringify(profileData));
	});

		Dota2.requestProfileCard(Dota2.ToAccountID('76561198117318581'));
	Dota2.on("profileCardData", function (accountId, profileData) {
		console.log(JSON.stringify(profileData));
	});
```
I get the data several times. Example:
![image](https://cloud.githubusercontent.com/assets/20172275/18076534/f25ff95a-6ea8-11e6-94bb-53badbd487ac.png)

Why is this happening?

**Comment by Crazy-Duck** [comment]
You're registering two event listeners that listen to the same event, so each time the event fires, it gets treated twice. Just remove the second event handler and the event will only be treated once. You also might wanna consider registering your event handlers before you make the call that triggers the firing of the event, just to make sure you don't miss it.

**Comment by kprodinfo** [comment]
@Crazy-Duck how to use this function in a loop?

It also gives doubles:
```
for(var i = 1; i < 10; i++) {
Dota2.requestProfileCard(i);
    Dota2.on("profileCardData", function (accountId, profileData) {
        console.log(JSON.stringify(profileData));
    });
}
```

**Comment by Crazy-Duck** [comment]
Ofcourse, because you're still registering multiple event handlers. If you structure your code as follows, you'll no longer have the issue
```
Dota2.on("profileCardData", function (accountId, profileData) {
    console.log(JSON.stringify(profileData));
});
for(var i = 1; i < 10; i++) {
    Dota2.requestProfileCard(i);
}
```
