### ISSUE TITLE
Ignore start_at_match_id

### ISSUE THREAD

**Issue by micdoug** [Arcana/node-dota2#336]
I can only get the last 20 matches in the function requestMatches. It seems that the parameter start_at_match_id is ignored.

**Comment by Crazy-Duck** [comment]
This function is pretty tricky to use, since there's only a moving frame of matches that are available via this method. For example, you won't be able to obtain last year's matches via this function. Can you post a small blurb indicating how you are calling this function?

**Comment by Crazy-Duck** [comment]
I confirm, I've tried this:
```
Dota2.requestMatches({
                    "matches_requested": 25,
                    "tournament_games_only": false,
                    "skill": 1
                }, (result,response) => {
                    response.matches.map(match => console.log(""+match.match_id));
                    let lastID = ""+ (response.matches[24].match_id-1);
                    console.log("Starting at "+lastID);
                    console.log(response.results_remaining);
                    Dota2.requestMatches({
                        "matches_requested": 25,
                        "start_at_match_id": lastID,
                        "tournament_games_only": false,
                        "skill": 1
                    }, (result, response)=>{
                        response.matches.map(match => console.log(""+match.match_id));
                        console.log(response.results_remaining);
                    });
                    
                });
```
And indeed it returns the same the same result twice. @howardchung does OpenDota use this function or do you guys use the webAPI?

**Comment by howardchung** [comment]
webAPI.  I believe the GC lacks a sequence number endpoint, which is the most efficient way to find new matches.

**Comment by micdoug** [comment]
Crazy-Duck I have used a code similar to yours and I have always the same result, no matter what parameter values I use.

**Comment by Crazy-Duck** [comment]
Seems like GC is bugged then, or we're missing something in the request... I recommend using the webAPI in the mean time.

**Comment by rossengeorgiev** [comment]
I've tried this and it works as expected. Up to 25 matches per request, and `start_at_match_id` works within the 500 total result.

**Comment by Crazy-Duck** [comment]
@rossengeorgiev can you paste a snipper with how you've managed to obtain multiple pages of results? I'd love to know how you got it to work so I can add it to the example list.

**Comment by rossengeorgiev** [comment]
By setting `start_at_match_id` to the last `match_id` from the previous response, until `results_remaining` is 0. I'm not using node-dota2 tho.

**Comment by micdoug** [comment]
@rossengeorgiev, what library have you used? Maybe I can test with it and try to figure out the source of the problem. Thanks

**Comment by rossengeorgiev** [comment]
@micdoug https://github.com/ValvePython/dota2

I do the same as what @Crazy-Duck does, maybe his code has a bug? I can't tell from glance. To step through the results I do something like:

```python
last_match_id = 0
while True:
    dota.request_matches(matches_requested=25, start_at_match_id=last_match_id)
    msg, = dota.wait_event('matches')
    # do stuff with matches
    last_match_id = msg.matches[-1].match_id - 1
    if msg.results_remaining == 0: break

**Comment by micdoug** [comment]
Ok. I will take a look and try to figure out the source of the problem. Thank you.

**Comment by Crazy-Duck** [comment]
The most obvious difference I'm seeing atm is the handling of job id's, which we completely ignore in node-dota2...

**Comment by Crazy-Duck** [comment]
Alright, found the error, there was indeed an error in my code, got fucked over again by the 64bit handling shenanigans of JavaScript. Here's a snippet that gives the intended result:

```JavaScript
        Dota2.requestMatches({
                    "matches_requested": 25,
                    "tournament_games_only": false,
                    "skill": 1
                }, (result,response) => {
                    response.matches.map(match => console.log(""+match.match_id));
                    let lastID = response.matches[24].match_id-1;
                    console.log("Starting at "+lastID);
                    console.log(response.results_remaining);
                    Dota2.requestMatches({
                        "matches_requested": 25,
                        "start_at_match_id": lastID,
                        "tournament_games_only": false,
                        "skill": 1
                    }, (result, response)=>{
                        response.matches.map(match => console.log(""+match.match_id));
                        console.log(response.results_remaining);
                    });

                });
```
Which prints:
```
...
15 Nov 15:12:11 - Reveived listing for matches
2780546302
2780544835
2780539900
2780537850
2780537337
2780536139
2780535376
2780529497
2780526619
2780526158
2780525567
2780525367
2780524985
2780523981
2780523123
2780522834
2780521907
2780521892
2780521475
2780521399
2780521169
2780520899
2780520676
2780520645
2780520594
Starting at 2780520593
475
15 Nov 15:12:12 - Sending match request
15 Nov 15:12:13 - Reveived listing for matches
2780520242
2780519618
2780519414
2780519325
2780519286
2780518092
2780518047
2780517805
2780517755
2780517635
2780517407
2780517022
2780516818
2780516678
2780516563
2780516368
2780515568
2780515421
2780515398
2780515158
2780514115
2780513871
2780513447
2780513385
2780512892
450
```
So what was the problem? This line: `let lastID = ""+ (response.matches[24].match_id-1);`
I think I added the quote concatenation to get rid of the high/low object shenanigans, but I've now found out that the subtraction already seems to do this (how? magic I guess...). The difference is in the datatype. By concatenating with an empty string, the whole thing gets casted to a String type, which apparently doesn't sit well with the proto parsing (why it doesn't return an error or why it doesn't work here while it works perfectly well elsewhere is beyond me, but here you go). By doing a subtraction however, a number datatype is preserved and properly put into the protobuf and the correct result is returned. So after all, not a confirmed bug, everything working as intended

**Comment by micdoug** [comment]
Good to know. @Crazy-Duck thanks for help.

**Comment by rossengeorgiev** [comment]
#justjavascriptthings

**Comment by Crazy-Duck** [comment]
@rossengeorgiev pretty much. It's all a consequence of JavaScript treating everything numeric as a Number, which can only safely represent integers up to 2^53. So as soon as you start messing with 64bit unsigned int's, things have a tendency to get murky -_-'

**Comment by rossengeorgiev** [comment]
One of the reasons why I love python. You can have integers as big as your can fit in memory.
