### ISSUE TITLE
problem with joinPracticeLobbyTeam

### ISSUE THREAD

**Issue by lemkova** [Arcana/node-dota2#337]
yo when i was trying to change my bot slot into "unassigned" it doesnt want to move its slot.

i was using
```
Dota2.createPracticeLobby("pass", properties, function(err, details){
});
Dota2.joinPracticeLobbyTeam(0, 4)
```

the lobby was successfully created but my bot's team didnt even change, its still on radiant slot

**Comment by lemkova** [comment]
ah really sorry, because it worked now, i just put the joinPracticeLobbyTeam() inside `practiceLobbyResponse` event

**Comment by Crazy-Duck** [comment]
Yeah, you kinda need to have a lobby before you can switch slots ☺️
