### ISSUE TITLE
Bring bot repo into org

### ISSUE THREAD

**Issue by jimmydorry** [Arcana/node-dota2#346]
https://github.com/Arcana/node-dota2/issues/342

@RJacksonm1 How do you want to handle adding the bot repo for node-dota2 to this org? It's a wrapper for the library.

[You can temporarily](https://github.com/orgs/Arcana/people) add @Crazy-Duck as owner to the org. He can then transfer ownership of it to Arcana, and then you can put him back to member.

Or perhaps @Crazy-Duck should make a new org and keep it separate?

What do?

**Comment by RJacksonm1** [comment]
@Crazy-Duck is now an owner!

**Comment by RJacksonm1** [comment]
Fuck it, so are you @jimmydorry

**Comment by jimmydorry** [comment]
Awesome. So much new power!

**Comment by RJacksonm1** [comment]
![image](https://cloud.githubusercontent.com/assets/602850/18778289/9077aa00-816b-11e6-8ae3-e5482fbef476.png)

although ...

**Comment by jimmydorry** [comment]
What's the worst that can happen? ![GreyFace](http://dota2.photography/public/s/Kappa.png)

Does 2FA change the workflow for committing? I don't want to be whipping out my phone for every commit.

**Comment by RJacksonm1** [comment]
If you're using git over HTTPS?  You'll need a "personal access token" rather than using your account password, it seems:

https://help.github.com/articles/providing-your-2fa-authentication-code/#when-youll-be-asked-for-a-personal-access-token-as-a-password

You needn't set it up just for Arcana. I'm just casually poking you with a pokey stick.

**Comment by jimmydorry** [comment]
I'll have a look when I get back from South Africa. When I do that, I'll also sort out this npm repo push nonsense. 👍

**Comment by RJacksonm1** [comment]
What're you doing in South Africa?  Don't ya know Elon is in the Americas now?

**Comment by jimmydorry** [comment]
I got summoned to go do some real work and earn my keep. Found out like yesterday and leave for SA on sunday. Elon is gonna need heaps of the stuff I'm digging out of the ground, so I'm sure he approves. :calendar:
