### ISSUE TITLE
How can I get ChatChannellList members

### ISSUE THREAD

**Issue by soloqi** [Arcana/node-dota2#362]
![qq 20161024185833](https://cloud.githubusercontent.com/assets/9653184/19643250/f9e1a680-9a1b-11e6-864e-36e255c423c8.jpg)

![qq 20161024190222](https://cloud.githubusercontent.com/assets/9653184/19643379/8e7caf38-9a1c-11e6-9245-a3c264d05957.jpg)

I can't understand what this means. 
I cant't find message about memebers by nethook2
My English is poor ,Can anyone understand me?

**Comment by Crazy-Duck** [comment]
When you request the chat channel list, you only receive the number of members in the channel. If you want information on the members currently present in the channel, you need to find the `CMsgDOTAJoinChatChannelResponse` and track the `CMsgDOTAOtherJoinedChatChannel` and `CMsgDOTAOtherLeftChatChannel` messages.

**Comment by soloqi** [comment]
I'm sorry ,But i cant find CMsgDOTAOtherJoinedChatChannel  or CMsgDOTAOtherLeftChatChannel  message when others join or left
only CMsgDOTAJoinChatChannelResponse  enabled bu no members_count
~~~~(>_<)~~~~

**Comment by soloqi** [comment]
I got it by http request
http://store.dota2.com.cn/webapi/IChat/GetChannelMembers/v0001?channel_id=552
thank all !!!

**Comment by Crazy-Duck** [comment]
@howardchung Did you know about this API endpoint? I've only ever heard about the http://api.steampowered.com one...

**Comment by howardchung** [comment]
No, I haven't heard of it.  I assume Valve uses it for something, or it wouldn't exist.  If we know where they use it, it might be possible to find some of the other endpoints that exist

**Comment by Crazy-Duck** [comment]
store.dota2.com.cn seems to be the chinese version of steamcmmunity, so it might be an API that's used for some China-oriented functionality.. Endpoint is unfortunately not selfdocumenting :/
```json
{
    "success": 0,
    "error": "Invalid URL. Usage: /webapi/interface/api/version?parameters"
}
```

**Comment by Crazy-Duck** [comment]
@soloqi where did you find this api?

**Comment by howardchung** [comment]
http://www.dota2.com/webapi/IChat/GetChannelMembers/v0001?channel_id=552

That works too so I don't think it's China specific.  Check dota2 for any functionality related to this?

**Comment by Crazy-Duck** [comment]
hmm, strange, www.dota2.com/webapi didn't return the above error so I assumed it only worked for the cn site. Thing is that IChat endpoint vaguely rings a bell but I can't seem to recall where I've seen it before...

**Comment by rossengeorgiev** [comment]
That API endpoint has been available for a long time, and it's not China specific. It's how the client handles certain channel types. The list is polled from that API, probably to avoid performance issues with doing over the steam protocol.

**Comment by Crazy-Duck** [comment]
Do you know if there are other methods/endpoints available on that api? Is it documented somewhere?

**Comment by rossengeorgiev** [comment]
Here are some.  That is as documented as you can get

```
webapi/IChat/GetChannelMembers/v0001
webapi/IDOTA2Events/GetArcanaVotes/v0001
webapi/IDOTA2Leagues/GetInvitedTeams/v001
webapi/IFrontpage/cell_data/v0001
webapi/ITournaments/GetLiveLeagueGames/v001
webapi/ITournaments/GetPredictionResults/v001
webapi/ITournaments/GetPredictions/v001
webapi/ITournaments/GetTournamentPlayers/v001

**Comment by Ne3tCode** [comment]
I don't know if it's ever useful, but...
```
/webapi/ICustomGames/GetPopularGames/v0001
/webapi/ICustomGames/GetSuggestedGames/v0001
/webapi/ICustomGames/GetWorkshopVoteQueue/v0001
/webapi/IDOTA2AutomatedTourney/GetParticipationDetails/v001
/webapi/IDOTA2AutomatedTourney/GetParticipationDetails/v001
/webapi/IDOTA2AutomatedTourney/GetPlayerHistory/v001
/webapi/IDOTA2AutomatedTourney/GetTournamentDetails/v001
/webapi/IDOTA2Fantasy/GetFantasyPlayerRawStats/v0001
/webapi/IDOTA2Fantasy/GetProPlayerList/v001
/webapi/IDOTA2Match/GetMatchMVPVotes/v001
/webapi/IDOTA2Match/GetTopLiveGame/v001
/webapi/IDOTA2MatchStats/GetRealtimeStats/v001
/webapi/IDOTA2StreamSystem/GetBroadcasterInfo/v001
/webapi/IDOTA2Teams/GetTeamInfo/v0001
/webapi/IDOTA2Teams/GetTeamInfo/v0001
/webapi/ILeague/GetLeagueInfo/v0002
/webapi/ILobbies/GetJoinableCustomLobbies/v0001
/webapi/IStore/GetClientStoreData/v0001
/webapi/ITournaments/GetGroupStandings/v001
/webapi/ITournaments/GetLeaguePrizePool/v001
/webapi/ITournaments/GetTournamentBrackets/v001
/webapi/ITournaments/GetTournamentInfo/v001
/webapi/ITournaments/GetTournamentSeriesDetails/v001
/webapi/IWorkshop/GetChangeLog/v0001
```
See `\game\dota\bin\<..>\client.dll` for more "documentation" :wink:

**Comment by jimmydorry** [comment]
Holy shit, thanks for the custom games stuff.

**Comment by Crazy-Duck** [comment]
There's a GetRealtimeStats as well, I need to look into this stuff 😮

**Comment by jimmydorry** [comment]
From what someone was theorising to me yesterday, any API that returns the same results to everyone, gets made into a public API that they can cache to reduce server strain.

**Comment by howardchung** [comment]
run fiddler/wireshark on your machine with the client open to see what http calls it's making and what params need to be passed.  I guessed a few things for GetRealTimeStats (match_id, lobby_id, but no luck).  GetLiveLeagueGames appears to be the same the official API version (but without the need for an API key)

**Comment by Crazy-Duck** [comment]
WE WON BOIS!

Wireshark trace:
GET //webapi/IDOTA2MatchStats/GetRealtimeStats/v001?server_steam_id=90105191599565825 HTTP/1.1

![image](https://cloud.githubusercontent.com/assets/11719463/20224866/e9fcc23a-a840-11e6-8924-28499f2f5d1b.png)

**Comment by Crazy-Duck** [comment]
So only 1 parameter, being the server_steam_id. This gives us: 
* current ingame time
* live stats on every player,
** location (!)
** last hits/denies
** kda
** hero
** level
** gold
* building status
* gold graph

**Comment by rossengeorgiev** [comment]
live as in after DotaTV delay

**Comment by howardchung** [comment]
Anything special not in http://www.dota2.com/webapi/ITournaments/GetLiveLeagueGames/v001

**Comment by Crazy-Duck** [comment]
Apart from the fact that this endpoint can be used for matches without ticket, don't think so..

**Comment by howardchung** [comment]
How do you resolve server_steam_id for an arbitrary match?

**Comment by rossengeorgiev** [comment]
You can't. Unless you are participating in the match

**Comment by Crazy-Duck** [comment]
You can for the games your friends are playing at the very least, since these pop up in the watch tab too

**Comment by howardchung** [comment]
Interesting, so maybe with adding service accounts as friends, live stats could be generated for matches you're playing in.  Not sure if that would be useful

**Comment by Crazy-Duck** [comment]
That's what I was thinking yes. Might be cool to have like a trackdota for your friends' games 😄

**Comment by Crazy-Duck** [comment]
These should be able to get you the server_team_id's for your friends' games, based on which we could be able to hit the api

```
message CMsgSpectateFriendGame {
	optional fixed64 steam_id = 1;
}

message CMsgSpectateFriendGameResponse {
	optional fixed64 server_steamid = 4;
}
```

**Comment by soloqi** [comment]
@Crazy-Duck I,m web developer and i used fiddler to get http request
GitHub is really a good place. ^_^

**Comment by kevinyeo92** [comment]
GET //webapi/IDOTA2MatchStats/GetRealtimeStats/v001?server_steam_id=90105191599565825 HTTP/1.1

@Crazy-Duck may I know how to get the server_steam_id?
I have a bot placing at unassigned player, I am able to get match_id, lobby_id etc..
I wish to get K/D/A gold etc of every player in the match. But I only saw bot's info, not every players.

**Comment by rossengeorgiev** [comment]
There server steam id should be available in the lobby shared object

**Comment by XenBG** [comment]
@rossengeorgiev , do you know how to convert the channel_user_id to the real user's SteamID from http://www.dota2.com/webapi/IChat/GetChannelMembers/v0001?channel_id=552 ?

**Comment by rossengeorgiev** [comment]
You cant 'covert'. It supposed to be unrelated, in order for people to be 'anonymous'.

**Comment by XenBG** [comment]
Yea, I realized that after the last update 😄 . That sucks.

**Comment by shu1396** [comment]
Yeah, i too found the match scores for practice lobby using the player's steam id credential and match_id of the player who played in the game. But i would like to know how the stats of practice match can be fetched using a bot spectator. If the Fiddler/wireshark tapping is the solution. So please recommend me something to do it.

**Comment by mburst** [comment]
Just use the web API if you have the match id

**Comment by zocheyado** [comment]
> You can't. Unless you are participating in the match

Does anyone know how to get the server_steam_id at all? I cannot figure out anyway to get it other than getting top live games. Lets assume I am actually in the game, is it somewhere in the console? temp file? How can one actually get that information. @rossengeorgiev

**Comment by beerpulse** [comment]
@cmosboss a day late & a dollar short but it shows up in console immediately after clicking in-game button
