### ISSUE TITLE
requestProfileCard get different result when I use different accounts

### ISSUE THREAD

**Issue by soloqi** [Arcana/node-dota2#370]
I reinstall node-dota2 and steam ,connect to different  server ip
But nothing works.And it's happend on client too
Is it have caches on steam server?
Does anyone have the same problem？

**Comment by KenBeanNet** [comment]
Yes.  This also happens on MatchDetails request too.  I always do a check after I get the results to ensure that the send match id == the result match id.  I use SteamKit2 and it happens there, so its just a general bug with Steam, not with Node2.
