### ISSUE TITLE
Bot crash due to "get messages from a chat I don't know"

### ISSUE THREAD

**Issue by kevinyeo92** [Arcana/node-dota2#379]
[PlayerId] left channel 312108 (PS: why do I get messages from a chat I don't know? Did you kill me D: ?)
Error: handlers\chat.js:222 channel.channel_name,

Everytime my bot LaunchPracticeLobby(), this error will show up and my bot crashed. Any idea?

**Comment by jimmydorry** [comment]
Probably related to https://github.com/Arcana/node-dota2/pull/378#issuecomment-264096298

**Comment by kevinyeo92** [comment]
Still getting the errors after the pull.

> TypeError: Cannot read property 'channel_name' of undefined

[PlayerId] joined channel Lobby_248483184657880
[PlayerId] left channel 402004 (totally a new channel id)

> Log: Received message from unknown channel. Leaving channel. See bug: (https://github.com/Arcana/node-dota2/pull/378)
> Log: This probably should be physically impossible, but whatever: you managed to leave a channel you didn't know you were in, congratulations...

debugged at chat.js, the channel is undefined.

**Comment by jimmydorry** [comment]
Read the comments on the PR, specifically the comment I linked. 

Not sure if solved yet as @Crazy-Duck is looking at it on the weekend.

**Comment by Crazy-Duck** [comment]
As for the errors you're getting, we'll probably need to look at the other message handlers in chat.js to make similar modifications as @tomasmck has made. The typical usecase where they pop up is when a bot get's killed without properly leaving all chat channels. I did not know the bot joins the post-game channel automatically, we'll probably need to find a workaround for that usecase (manually add the channel to the cache as soon as a practiceLobbyUpdate arrives or something ... ). @kevinyeo92 feel free to make suggestions :)
As for your problem detecting the end of the game, check the state property and the match_outcome properties on the practiceLobbyUpdate event

**Comment by tomasmck** [comment]
This will hopefully be resolved by this PR: https://github.com/Arcana/node-dota2/pull/378.

I just pushed another update, cleaning up that handler. I'll be testing over the next few days.

**Comment by MeLlamoPablo** [comment]
Hi, I'm getting the same error. I'm leaving the full stack trace in case it helps:

```
8 Dec 00:14:11 - Dota2 fromGC: k_EMsgGCOtherLeftChannel
8 Dec 00:14:11 - 76561198041415108 left channel 4123027 (PS: why do I get messages from a chat I don't know? Did you kill me D: ?)
C:\Users\Pablo\NodeProjects\schedulebot\node_modules\dota2\handlers\chat.js:222
            channel.channel_name,
                   ^

TypeError: Cannot read property 'channel_name' of undefined
    at Dota2Client.onOtherLeftChannel (C:\Users\Pablo\NodeProjects\schedulebot\node_modules\dota2\handlers\chat.js:222:20)
    at SteamGameCoordinator.fromGC (C:\Users\Pablo\NodeProjects\schedulebot\node_modules\dota2\index.js:57:38)
    at emitThree (events.js:116:13)
    at SteamGameCoordinator.emit (events.js:194:7)
    at SteamGameCoordinator.handlers.(anonymous function) (C:\Users\Pablo\NodeProjects\schedulebot\node_modules\steam\lib\handlers\game_coordinator\index.js:107:10)
    at SteamGameCoordinator.<anonymous> (C:\Users\Pablo\NodeProjects\schedulebot\node_modules\steam\lib\handlers\game_coordinator\index.js:19:28)
    at emitThree (events.js:121:20)
    at SteamClient.emit (events.js:194:7)
    at SteamClient._netMsgReceived (C:\Users\Pablo\NodeProjects\schedulebot\node_modules\steam\lib\steam_client.js:172:10)
    at SteamClient.handlers.(anonymous function) (C:\Users\Pablo\NodeProjects\schedulebot\node_modules\steam\lib\steam_client.js:259:10)
    at SteamClient._netMsgReceived (C:\Users\Pablo\NodeProjects\schedulebot\node_modules\steam\lib\steam_client.js:157:26)
    at emitOne (events.js:96:13)
    at Connection.emit (events.js:188:7)
    at Connection._readPacket (C:\Users\Pablo\NodeProjects\schedulebot\node_modules\steam\lib\connection.js:50:8)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run-script" "bot"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! schedulebot@1.0.0 bot: `node ./lib/index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the schedulebot@1.0.0 bot script 'node ./lib/index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the schedulebot package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./lib/index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs schedulebot
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls schedulebot
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Pablo\NodeProjects\schedulebot\npm-debug.log
```

By the way, is there a temporary workaround to this? Such as a `try ... catch ...` block whose `catch` ignores the error. It'd be good to have a workaround while the PR comes since this bug makes it impossible to ship to production.

Please do tell me if there's anything else I can do to help.

**Comment by kevinyeo92** [comment]
I tested the new PR in #378 
My bot no longer crash after I finished a game.
