### ISSUE TITLE
Will the node-dota2 work with Dota 2 ver 7.00?

### ISSUE THREAD

**Issue by XenBG** [Arcana/node-dota2#385]
The question itself :D.

I'm asking, because I have lobby host bot and I wanna know if it will work or not with the new version. If somebody know how to test it on the Dota 2 Test version, I will do it.

**Comment by Crazy-Duck** [comment]
Your guess is as good as mine :) as soon as patch hits we'll check it out. I think most functionality should still work, but you never know I guess.

**Comment by Crazy-Duck** [comment]
As for your test question, I think the test client has its own APP_ID, so you'd need to figure that one out and replace the DOTA_APP_ID=570 in index.js. I think that should work

**Comment by XenBG** [comment]
Already tried, didn't worked.

```[root@esp4 test]# node test.js
12 Dec 21:11:16 - Logged on Steam.
12 Dec 21:11:16 - Launching Dota 2
12 Dec 21:11:16 - Received servers.
12 Dec 21:11:16 - sentryfile saved
12 Dec 21:11:17 - Sending ClientHello
12 Dec 21:11:22 - Sending ClientHello
12 Dec 21:11:28 - Sending ClientHello```

**Comment by Crazy-Duck** [comment]
@jimmydorry did you ever play with test client?

**Comment by XenBG** [comment]
Test client ID is 205790.

**Comment by jimmydorry** [comment]
^ I think. Am on phone right now.

I wouldn't bother though. If stuff breaks, it breaks. The test client is too different to be of much use for testing IMHO.

**Comment by jimmydorry** [comment]
Got to a computer. Yes it's 205790

**Comment by XenBG** [comment]
Seems the code still works for me in the new patch. That's nice!

**Comment by Crazy-Duck** [comment]
Sweet, closing issue then :)
