### ISSUE TITLE
Bot created lobby by inviting players, but how to Leave it?

### ISSUE THREAD

**Issue by JasonMcz** [Arcana/node-dota2#388]
> Asks to invite a player to your lobby. This creates a new default lobby when you are not already in one.

Using `inviteToLobby(steam_id)` _endpoint_ the bot is able to create a lobby and send invitation to players and how does the Bot leave the lobby after people join the current lobby and bot's "service" is no longer needed?

**Comment by XenBG** [comment]
```leavePracticeLobby()```

**Comment by Crazy-Duck** [comment]
Might want to launchPracticeLobby (this launches the game) first if you want to prevent the players from messing with the lobby's settings

**Comment by JasonMcz** [comment]
@XenBG , can Bot leave the lobby after 1st invitee enters it?

**Comment by XenBG** [comment]
Yes, just listen when somebody joins the lobby and use the ```leavePracticeLobby()``` method.

**Comment by JasonMcz** [comment]
Danke!

**Comment by XenBG** [comment]
Here's a sample of that thing you want to do:

```Dota2.on("practiceLobbyUpdate", function(lobby) {
	global.gameLobbyID = lobby.lobby_id;
});

Dota2.on("chatJoin", function(channel_id, joiner_name, joiner_steam_id, otherJoined_object) {
	var botSteamID = "76561198216778601"; // also for Steam3 ID use this method - Dota2.ToSteamID("256512873");

	if(joiner_steam_id != botSteamID){
		var lobbyChannelName = "Lobby_" + global.gameLobbyID;

		Dota2.leavePracticeLobby(function(err, data) {
			if (data.result == 2) {
				util.log("There's no lobby to leave.");
			} else {
				util.log("Leaving the Lobby and its Chat Channel.");
				Dota2.leaveChat(lobbyChannelName);
			}
		});
	}
});

**Comment by Crazy-Duck** [comment]
Be careful with this code though, it assumes that someone joining the lobby automatically joins the chat channel as well, which isn't a prerequisite (for example, afaik your bot needs to explicitly join the lobby chat channel, else it won't be in it). It's better to listen for `practiceLobbyUpdate` events and interpret those. Each time a new player joins the lobby, you'll receive a `practiceLobbyUpdate` event which contains the new list of players in the lobby. By comparing with the Lobby property (which is only updated *after* the event is handled), you can see who joined/left.

**Comment by zackcoburn** [comment]
Is there a way to get the match ID after leaving the lobby?

**Comment by Crazy-Duck** [comment]
@zackcoburn check #395

**Comment by Crazy-Duck** [comment]
@JasonMcz can you close this issue if your problem is resolved?
