### ISSUE TITLE
BOT and unassigned players. Need help!

### ISSUE THREAD

**Issue by Nevmen9sha** [Arcana/node-dota2#394]
Hi! I have a problem. When creating a lobby, bot automatically jump into the player slot.  What method should I use, to throw it in unassigned players?

**Comment by Crazy-Duck** [comment]
There's an enum for the different teams, use `joinPracticeLobbyTeam` with the unassigned team value (I think,  I'll have to get to a pc for the actual value)

**Comment by Nevmen9sha** [comment]
Thank you! I will wait)

**Comment by Crazy-Duck** [comment]
The enum is
```
enum DOTA_GC_TEAM {
	DOTA_GC_TEAM_GOOD_GUYS = 0;
	DOTA_GC_TEAM_BAD_GUYS = 1;
	DOTA_GC_TEAM_BROADCASTER = 2;
	DOTA_GC_TEAM_SPECTATOR = 3;
	DOTA_GC_TEAM_PLAYER_POOL = 4;
	DOTA_GC_TEAM_NOTEAM = 5;
}
```
The value you're searching for is `Dota2.schema.DOTA_GC_TEAM.DOTA_GC_TEAM_PLAYER_POOL`

**Comment by XenBG** [comment]
```Dota2.practiceLobbyKickFromTeam("  BOT ACCOUNT ID   ");```

**Comment by angel200sdnot** [comment]
I use this right after creating the lobby
`Dota2.joinPracticeLobbyTeam(1, 4, function(err);`

**Comment by Crazy-Duck** [comment]
both work, it's just preference I guess. In the first one you kick yourself from the team, in the second you go willingly

**Comment by Crazy-Duck** [comment]
@Nevmen9sha can you close this if you have no further questions?

**Comment by Nevmen9sha** [comment]
Yes, thank you)
