### ISSUE TITLE
How to get MatchID after BOT leaves the lobby.

### ISSUE THREAD

**Issue by JasonMcz** [Arcana/node-dota2#396]
Currently, bot can use an event listener using LobbyID to listen players joining the game and analyzing the promise of how many people in the lobby, but is there a smart way to get matchID after Bot leaves the lobby after creating it and send invites? so it can get the result?

**Comment by JasonMcz** [comment]
@Crazy-Duck @paralin

**Comment by Crazy-Duck** [comment]
Duplicate of #395
