### ISSUE TITLE
Could any one help with CSODOTALobby.CExtraMsg ? 

### ISSUE THREAD

**Issue by dmitry-tuzenkov** [Arcana/node-dota2#397]
Hello everyone.

Could anyone help me figure out with `CSODOTALobby.CExtraMsg` field?
What secret contains this data  structure? 
```
message CSODOTALobby {
	message CExtraMsg {
		optional uint32 id = 1;
		optional bytes contents = 2;
	}
//...

}
```

**Comment by Crazy-Duck** [comment]
@howardchung do you have any idea?

**Comment by howardchung** [comment]
Nope.  Probably need to use nethook or something and try a bunch of lobby actions to see if this pops up.  Might be difficult to find though. Typically it works the other way, you identify what behavior you want to emulate then use nethook to find the relevant messages.

**Comment by angel200sdnot** [comment]
id is the EDOTAGCMsg enum value of the message and content is the encoded message (im pretty new at this and this is just guessing)

in a lobby without any league (leagueid: 0) i only get an array with 1 element
`extra_messages: CExtraMsg[ 1 ] = [{ id: 7572, contents: 080F120F08C9FAED131000180050E80758E807 }]`

i happen to have access to a league ticket and in that lobby i get an array with 2 elements
 `extra_messages: CExtraMsg[ 2 ] = [{ id: 7572, contents: 080F120F08C9FAED131000180050E80758E807 }, { id: 7434, contents: 08CFA4F20908C9FAED1308EAD8BC30 }]`

7572 is the enum value of k_EMsgLobbyEventPoints and 7434 is k_EMsgGCLeagueAdminList}

I got that right after launching the lobby in the message k_ESOMsg_UpdateMultiple, before launching the lobby i didnt get any extra_messages

**Comment by Crazy-Duck** [comment]
Did you already try to decode the first one as a `CMsgLobbyEventPoints` and the second one as a `CMsgLeagueAdminList` ?

**Comment by dmitry-tuzenkov** [comment]
According to your message @angel200sdnot  i should decode by message id right?
```javascript
k_EMsgLobbyEventPoints = 7572;
->
message CMsgLobbyEventPoints {
	message AccountPoints {
		optional uint32 account_id = 1;
		optional uint32 normal_points = 2;
		optional uint32 premium_points = 3;
		optional bool owned = 4;
		optional uint32 favorite_team = 5;
		optional uint32 favorite_team_level = 6;
		optional uint32 points_held = 7;
		optional uint32 premium_points_held = 8;
		optional uint32 favorite_team_foil_level = 9;
		optional uint32 wager_tokens_remaining = 10;
		optional uint32 wager_tokens_max = 11;
		optional uint64 active_effects_mask = 12;
	}

	optional uint32 event_id = 1;
	repeated .CMsgLobbyEventPoints.AccountPoints account_points = 2;
}

```

```
var data = Dota2.schema.CMsgLobbyEventPoints.decode(message);
 ```

**Comment by angel200sdnot** [comment]
I just did a quick test and this is what i got in a lobby with a leagueid

For k_EMsgLobbyEventPoints = 7572
`24 Dec 01:22:04 - { event_id: 15,
  account_points: 
   [ { account_id: 41647433,
       normal_points: 0,
       premium_points: 0,
       owned: null,
       favorite_team: null,
       favorite_team_level: null,
       points_held: null,
       premium_points_held: null,
       favorite_team_foil_level: null,
       wager_tokens_remaining: 1000,
       wager_tokens_max: 1000,
       active_effects_mask: null } ] }`

For k_EMsgGCLeagueAdminList = 7434 
`24 Dec 01:22:04 - { account_ids: [ 20746831, 41647433, 101657706 ] }`

to get this i modified in handlers/cache.js, the handleSubscribedType function, under case cacheTypeIDs.CSODOTALobby:
`var lobby = Dota2.schema.CSODOTALobby.decode(object_data);
            var lobbyEventPoints;
            var leagueAdminList;
            if (this.debug) util.log("Received lobby snapshot for lobby ID " + lobby.lobby_id);
            if (lobby.extra_messages.length > 0) {
                for (var i = 0; i < lobby.extra_messages.length; i++) {
                    if (lobby.extra_messages[i].id == 7572) {
                        lobbyEventPoints = Dota2.schema.CMsgLobbyEventPoints.decode(lobby.extra_messages[i].contents);
                    }
                    if (lobby.extra_messages[i].id == 7434) {
                        leagueAdminList = Dota2.schema.CMsgLeagueAdminList.decode(lobby.extra_messages[i].contents);
                    }
                }
            }
            this.emit("practiceLobbyUpdate", lobby, lobbyEventPoints, leagueAdminList);
            this.Lobby = lobby;
            break;`

**Comment by dmitry-tuzenkov** [comment]
Hey, @angel200sdnot please look attachment!

``` javascript

var a = 2;

```

![screen shot 2016-12-25 at 22 52 44](https://cloud.githubusercontent.com/assets/1918309/21472858/e3da3816-caf4-11e6-9150-8d15213ee83d.png)

**Comment by jimmydorry** [comment]
Cool, I didn't know that markup existed.
