### ISSUE TITLE
How to remove warning DeprecationWarning when connect?

### ISSUE THREAD

**Issue by shockwaves** [Arcana/node-dota2#398]
```
20 Dec 18:03:16 - Logged on.
20 Dec 18:03:16 - Launching Dota 2
20 Dec 18:03:16 - Received servers.
(node:20209) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
20 Dec 18:03:22 - Sending ClientHello
20 Dec 18:03:23 - Dota2 fromGC: k_EMsgGCClientWelcome
20 Dec 18:03:23 - Received client welcome.
```

**Comment by shockwaves** [comment]
ok, sorry, i find this in `fs.writeFile servers`, in handler `onSteamServers` ,
add just callback function and fix it:

```
        fs.writeFile(__dirname + '/servers', JSON.stringify(servers), function () {
            console.log('writeFile servers');
        });
```

**Comment by Crazy-Duck** [comment]
This is a problem in your own code, which I'm guessing you based on the examples. Example.js has already been fixed on the dev and staging branches, for example2.js I've just made the pull. As soon as I bump the master to 4.2.0 (probably this week) this error should disappear.

**Comment by shockwaves** [comment]
yes, i see it now)
so very glad that this warning disappeared ^_^
