### ISSUE TITLE
Add Warning that Trophy Level 5 is required to use sendMessage

### ISSUE THREAD

**Issue by yukidaruma** [Arcana/node-dota2#403]
![dota2_2016-12-22_11-33-53](https://cloud.githubusercontent.com/assets/6897821/21432316/48816f80-c8ae-11e6-8945-62cbd1f6d990.png)

**Comment by yukidaruma** [comment]
I'm sorry I think I made wrong use of Issues/PR...

**Comment by Crazy-Duck** [comment]
Nah, this is fine honestly. This issue will auto-close as soon as I merge, well done!

**Comment by Crazy-Duck** [comment]
just make sure next time if you fix an issue, you put Fix  #issue number in the pull request. That way it auto-closes

**Comment by yukidaruma** [comment]
Got it. Thanks for the information.
