### ISSUE TITLE
how to check the presence of a previously created lobby when reconnecting to the game?

### ISSUE THREAD

**Issue by shockwaves** [Arcana/node-dota2#406]
I do login, launch game, create lobby in my app based on node-dota2. Then i restart my app and launch game again. If if I try once more to create a lobby, i get message:

```
Received create/flip/shuffle/kick/launch/leave response {"result":2}
Sending match CMsgPracticeLobbyCreate request
```

 What is best way to check that the lobby was already created?

**Comment by Crazy-Duck** [comment]
Well, the result: 2 literally means: you're already in a lobby. So I'd say this is a pretty good way to check if you're in one. You could also just start off with calling leavePracticeLobby, that way you're sure you're not in one

**Comment by dmitry-tuzenkov** [comment]
I'have tried to decode but...

**Comment by Crazy-Duck** [comment]
Are you posting in the right issue here?

**Comment by shockwaves** [comment]
Thank's for answer!

> Are you posting in the right issue here?

what do you mean?

**Comment by Crazy-Duck** [comment]
@shockwaves someone had posted a whole block of code that belonged in another issue. He has deleted his comment in the mean time :)
