### ISSUE TITLE
Add an event for onJoinChatChannelResponse

### ISSUE THREAD

**Issue by yukidaruma** [Arcana/node-dota2#407]
So we can safely handle event instead of [setTimeout](https://github.com/Arcana/node-dota2/blob/ca5c84bf50ac6007899758bd437d6d9cdcd71fb7/examples/example.js#L77).

By the way, there is `chatJoin` event for [onOtherJoinedChannel](https://github.com/Arcana/node-dota2/blob/95a679dd9062ef77d56305d56d42ce2352c3f727/handlers/chat.js#L186). I cannot come up with good name for `onJoinChatChannelResponse` event.

**Comment by Crazy-Duck** [comment]
how about `chatJoined`?
