### ISSUE TITLE
dota2.schema.DOTA_GameMode is undefined

### ISSUE THREAD

**Issue by shockwaves** [Arcana/node-dota2#413]
it happened in the current release (4.2.0)

**Comment by MeLlamoPablo** [comment]
Apparently the API changed. Now it's:

```js
Dota2.schema.lookupEnum("DOTA_GameMode")
```

I refactored all my code to have the enums I use on the same place, just in case it changes again:

```js
const EServerRegion     = Dota2.ServerRegion
	, ESeriesType       = Dota2.SeriesType
	, EGameMode         = Dota2.schema.lookupEnum("DOTA_GameMode")
	, EGameVersion      = Dota2.schema.lookupEnum("DOTAGameVersion")
	, ECMPick           = Dota2.schema.lookupEnum("DOTA_CM_PICK")
	, EDotaTVDelay      = Dota2.schema.lookupEnum("LobbyDotaTVDelay")
	, EChatChannelType  = Dota2.schema.lookupEnum("DOTAChatChannelType_t")
;
```

**Comment by Crazy-Duck** [comment]
It's an unfortunate side-effect of protobufjs changing their API in the latest version. `Dota2.schema` will return a [`Root` ](https://github.com/dcodeIO/protobuf.js/blob/master/src/root.js) object. If you want to get an enum from the protobufschema, you need to call `Dota2.schema.lookupEnum`.
