### ISSUE TITLE
How to get tournament_game_id required to host a ticketed match?

### ISSUE THREAD

**Issue by MeLlamoPablo** [Arcana/node-dota2#414]
Hello! I'm struggling to get my bot to host a ticketed match, because I don't know what should I put in `tournament_game_id` (the section in the README.md is not documented). Taking a look at the source code, it seems that if I put anything lower than 1, no ticketed lobby is created. So I tried with 1, and 123456789, but none works. I don't really know what should I put. How am I supposed to know a match ID before the game even begins?

This is my code:

```js
const EServerRegion     = Dota2.ServerRegion
    , ESeriesType       = Dota2.SeriesType
    , EGameMode         = Dota2.schema.lookupEnum("DOTA_GameMode")
    , EGameVersion      = Dota2.schema.lookupEnum("DOTAGameVersion")
    , ECMPick           = Dota2.schema.lookupEnum("DOTA_CM_PICK")
    , EDotaTVDelay      = Dota2.schema.lookupEnum("LobbyDotaTVDelay")
    , EChatChannelType  = Dota2.schema.lookupEnum("DOTAChatChannelType_t")
;

/* this.client = Dota2 */ this.client.createTournamentLobby(
	this.currentLobbyPassword /* Randomly generated */,
	/*tournament_game_id*/ 123456789,
	/*tournament_id*/ 4187, /* https://es.dotabuff.com/esports/leagues/4187 */
	{
		"game_name": this.currentLobbyName, /* User input */
		"server_region": server, /* User input, valid ENUM value */
		"game_mode": gamemode, /* User input, valid ENUM value */
		"game_version": EGameVersion.GAME_VERSION_STABLE,
		"series_type": ESeriesType.NONE,
		"cm_pick": ECMPick.DOTA_CM_RANDOM,
		"allow_cheats": false,
		"fill_with_bots": false,
		"allow_spectating": true,
		"pass_key": this.currentLobbyPassword, /* Randomly generated */
		"radiant_series_wins": 0,
		"dire_series_wins": 0,
		"allchat": false,
		"dota_tv_delay": EDotaTVDelay.LobbyDotaTV_120
	},
	err => {
		// Unrelated
	}
);
```

Of course, the Steam account I'm using is a league administrator.

Thanks in advance for your help!

**Comment by MeLlamoPablo** [comment]
Hi, thanks for the answer. Do you have any reccomendations for using a nethook? I have never used one and I don't know where to begin.

**Comment by Crazy-Duck** [comment]
[Our wiki](https://github.com/Arcana/node-dota2/wiki#using-nethook) is a good place to start :)

**Comment by MeLlamoPablo** [comment]
Hi, do you have by any chance a compiled NethookAnalyzer? I got Nethook from appveyor and managed to get it working, but I couldn't manage to compile the NethookAnalyzer.

**Comment by angel200sdnot** [comment]
My bot makes ticketed league games without any issues using this options and using createPracticeLobby()
```javascript
var properties = {
    "game_name": lobbyName,
    "server_region": 2,
    "game_mode": lobbyGamemode,
    "series_type": 0,
    "game_version": 1,
    "allow_cheats": true,
    "fill_with_bots": false,
    "allow_spectating": true,
    "pass_key": lobbyPassword,
    "radiant_series_wins": 0,
    "dire_series_wins": 0,
    "allchat": true,
    "dota_tv_delay": 0,
    "pause_setting": 1,
    "leagueid": 2971
};

For the bot to be able to make the league lobby it needs to be an admin of that league, otherwise it wont be able to use that league id
```

**Comment by MeLlamoPablo** [comment]
@angel200sdnot thank you! That did work! You're a lifesaver, I can't thank you enough :)

@Crazy-Duck, the param `leagueid` is documented as `league_id`, which doesn't work. I'll later send a PR with some little documentation improvements, as I encountered other problems in the past.

**Comment by Crazy-Duck** [comment]
alright, more docs is always welcome!

**Comment by Crazy-Duck** [comment]
@angel200sdnot i take it this means tournament_game_id is optional then?

**Comment by angel200sdnot** [comment]
@Crazy-Duck Yes, using the default value always works

The tournament game id could be used to track bo3 or bo5 type of league matches, where all of them have different match id but share a common tournament_game_id, this is just me guessing because i havent actually tested those types of games

**Comment by Crazy-Duck** [comment]
Alright, then I prefer we make tournament_game_id a an optional argument in `handlers/lobbies.js`. @MeLlamoPablo can you make this modification and add it to your pull? I propose we continue this discussion there then
