### ISSUE TITLE
Managing more than 1 bot

### ISSUE THREAD

**Issue by angel200sdnot** [Arcana/node-dota2#418]
Whats the best way to manage more than 1 bot, spawning a child process for each bot or using 1 process that manages all of the bots?

How slow would the manager be in comparison with using 1 process for each bot?

**Comment by Crazy-Duck** [comment]
It depends of the number of bots you're managing I think. @howardchung I take it you guys use a decently sized bot pool? How do you manage them?

**Comment by howardchung** [comment]
Nothing fancy.

https://github.com/odota/core/blob/master/svc/retriever.js

The bot just connects with a configurable number of accounts (currently 15).  (That would one process, logging into multiple accounts at once).  You can also do one account per process but that's more memory overhead.

**Comment by shockwaves** [comment]
what to do if the number of bots is greater than 100 ?

**Comment by angel200sdnot** [comment]
@howardchung this is the answer i was looking for, thanks

**Comment by Crazy-Duck** [comment]
@shockwaves you'd have to run some tests to see what's the most performant based on your current setup. We've never deployed networks of bots of that size, so it's hard to speculate
