### ISSUE TITLE
How can i fetch Solo MMR from Acount IDs ? 

### ISSUE THREAD

**Issue by rnsparkour** [Arcana/node-dota2#419]
`  var steamID = '76561198058632219';
           var accid = Dota2.ToAccountID(steamID);

             Dota2.requestProfile(accid,function(err, res) {
                if (err) throw err;
              console.log(JSON.stringify(res));
             });`

> TypeError: Dota2.requestProfile is not a function

So is there  another way to get Solo MMR ?  Without OPEN DOTA  API ?

**Comment by Crazy-Duck** [comment]
`requestProfile` is deprecated, as stated in the README (has been for over a year now I think). You can only retrieve solo MMR if people show it on their profile card. To obtain that, you can call [`requestProfileCard`](https://github.com/Arcana/node-dota2#requestprofilecard-account_id-callback)

**Comment by soloqi** [comment]
http://cbss.api.766.com/app/dota2/self/player/summary?steamId=5342463
PerfectWorld once granted super api-key which can get solommr and other hidden mmr directly
This api based on the super key，you can test it with any account id

**Comment by Crazy-Duck** [comment]
@jimmydorry @RJacksonm1 do any of you guys have contacts at Valve? This one might be worth reporting honestly. This is clearly a public endpoint that shouldn't exist..

**Comment by jimmydorry** [comment]
Been away for a bit. Valve don't care about anything PerfectWorld related. I'll report it, but past precedent indicates they will just get another key.

**Comment by Crazy-Duck** [comment]
From what I gather this is a custom api built with a leaked API key (the one from ruru?). I get they don't care much about perfect world (I mean, those guys need this kind of access to be able to manage the chinese servers), but I'd assume Valve would oppose to the fact the key is this blatantly available? At least they should revoke this key and give a new one to PW then. They've already gone through all this trouble of hiding people's MMR when they don't want to show it.

**Comment by rossengeorgiev** [comment]
@soloqi are there other similiar APIs on that site? Matches for examples, etc

**Comment by jimmydorry** [comment]
Confirmed PW. The report was received.

**Comment by soloqi** [comment]
@rossengeorgiev No yet，the api was used in their andriod app，expect updates...
those key was disabled after ruru event，but it was restored  a few days later，maybe it's legal

**Comment by rnsparkour** [comment]
so this API from PW should not use it ?

**Comment by Crazy-Duck** [comment]
Well I can't stop you, but I'd advise against it. There's a reason Valve wants this kind of information to be kept private. In any case, I wouldn't rely on the API since chances are it will disappear.

**Comment by howardchung** [comment]
Combining this API with GC requests to get an unbiased sample of account_ids could finally produce an answer to the question of MMR distribution/inflation.

@rossengeorgiev are you already working on this?

**Comment by rossengeorgiev** [comment]
@howardchung 😄

**Comment by howardchung** [comment]
If you aren't I might do it for personal interest.  Not planning to make it part of the OpenDota project though since it's kind of ethically gray.

If you're already working on something though I'll just wait for your results :)

**Comment by jimmydorry** [comment]
Their app looks dead now. Good work guys.

**Comment by Crazy-Duck** [comment]
@howardchung the MMR listings weren't 100% accurate either. I did a few tests, and while accurate for some people, for others the numbers could be off by quite a big margin. For example, an account which had 3k solo ranked on its profile was reported as only having 2.5k by the API call...

**Comment by jimmydorry** [comment]
Did you run the update API though? There were other APIs exposed that had even more useful capabilities for harvesting data.

**Comment by Crazy-Duck** [comment]
I only played around with the player summary, once I saw that one didn't give accurate results I didn't look into it further. What was the update API?

**Comment by jimmydorry** [comment]
It would update the user's data, and I think it did their MMR too.

**Comment by rossengeorgiev** [comment]
@howardchung what are you interested in? I may be able to answer.

**Comment by howardchung** [comment]
Whether MMR median (unbiased sample) has shifted from the values that Valve provided years ago

**Comment by rossengeorgiev** [comment]
I didn't get the chance to do random sampling, so that question remains to be answered.

**Comment by pendo324** [comment]
Wow, I wish I read this thread earlier and had a chance to do some sampling before it was restricted/removed :(
