### ISSUE TITLE
Can't chat despite having trophy level 5

### ISSUE THREAD

**Issue by qing5hu1** [Arcana/node-dota2#431]
#I keep getting 

> (Console): You must reach at least level 5 to participate in public chat channels.

despite the account having paid for games on steam, + being level 5 on Dota.
Is there any way to resolve this or do I need to get a new account?

This guy has the same problem:
https://www.reddit.com/r/DotA2/comments/5l08a5/please_create_an_official_bot_account/

Edit: made a thread on dev.dota
http://dev.dota2.com/showthread.php?t=276627

**Comment by rossengeorgiev** [comment]
Have you tried getting the account to level 6?

**Comment by qing5hu1** [comment]
Not yet, I'll try that.

**Comment by qing5hu1** [comment]
The account is level 9 and i still can't talk on it.
https://i.imgur.com/jr3JdEf.jpg
Heres an extract from dota_game_account_debug:
`CDOTAGameAccountClient:
[Developer] account_id: 75562186
[Developer] wins: 17
[Developer] losses: 11
[Developer] xp: 390
[Developer] level: 1
[Developer] initial_skill: 100
[Developer] leaver_count: 0
[Developer] low_priority_until_date: 0
[Developer] prevent_text_chat_until_date: 0
[Developer] prevent_voice_until_date: 0
[Developer] last_abandoned_game_date: 0
[Developer] leaver_penalty_count: 0
[Developer] completed_game_streak: 31`

**Comment by rossengeorgiev** [comment]
Wierd... maybe its broken at the moment? I checked on my account and level doesn't correspond to the account level. `play_time_level` is trophy

**Comment by hhuh** [comment]
I have the same issue.  I got my bot account's dota profile level to 8 and it still yelled at me that I need to be level 5.  Then I thought it was the steam profile level so I just leveled it up to 7 but even then, its giving me the same result.  This has to be some sort of bug on Valve's end.

**Comment by qing5hu1** [comment]
@rossengeorgiev You're correct. level: 1 doesn't mean anything. play_time_level on my account is different.

**Comment by rossengeorgiev** [comment]
I might have a solution for you guys. Try sending a profileCard request for account you are logged in with, after you get a non empty response, try sending chat messages.

**Comment by Crazy-Duck** [comment]
@rossengeorgiev can you provide some more context to this? How do profilecard requests influence your ability to chat?

**Comment by rossengeorgiev** [comment]
Ok, so I encountered someone complaining that they can't chat and getting the `not level 5` message. They provided a screenshot and their profile card was blank. So, we know lvl5 message is server side, and the level is not part of the game account shared object. I'm thinking profile is fetched server side, and cached, and the instance handling the specific client looks up the value from there to decide whether the client can chat or not. However, during peak hours due to dark moon, most of profile cards requests would fail, so the server side doesn't have the level value and defaults to 1.

**Comment by bippum** [comment]
Hi, I'm having the same issue where I can't chat, 
```js
{
    account_id: 376290001,
    background_def_index: 0,
    slots: [],
    badge_points: 110,
    event_points: null,
    event_id: null,
    recent_battle_cup_victory: null 
}
```
Here is the response I get from `requestProfileCard`. Still can't chat in public chat channels. I activated this account by buying something from Steam marketplace.

**Comment by rossengeorgiev** [comment]
@bippum you have 110 badge points, which is level 1, and you need level 5 to chat.

**Comment by bippum** [comment]
I know this but it worked before and then the same day as Valve "cracking down" on Boostore.net advertisers/etc it broke. What's frustrating is it did nothing to stop those advertisers.

**Comment by qing5hu1** [comment]
`9 Feb 02:18:37 - Logged on.
9 Feb 02:18:37 - Launching Dota 2
9 Feb 02:18:37 - Received servers.
9 Feb 02:18:38 - Sending ClientHello
9 Feb 02:18:38 - Received client welcome.
Node-dota2 ready.
9 Feb 02:18:38 - Sending profile card request
9 Feb 02:18:38 - Joining chat channel: quaswexreport
9 Feb 02:18:39 - Cache(s) subscribed, type(s): 1,7
9 Feb 02:18:39 - Received inventory snapshot
9 Feb 02:18:39 - Unhandled cache ID: 7
9 Feb 02:18:39 - Received profile card data for: 75562186
{
  "account_id": 75562186,
  "background_def_index": 0,
  "slots": [
    {
      "slot_id": 0,
      "stat": {
        "stat_id": "k_eStat_FirstMatchDate",
        "stat_score": 1353189369
      }
    },
    {
      "slot_id": 1,
      "stat": {
        "stat_id": "k_eStat_Commends",
        "stat_score": 32
      }
    },
    {
      "slot_id": 2,
      "hero": {
        "hero_id": 74,
        "hero_wins": 0
      }
    },
    {
      "slot_id": 3,
      "hero": {
        "hero_id": 82,
        "hero_wins": 0
      }
    },
    {
      "slot_id": 4,
      "hero": {
        "hero_id": 44,
        "hero_wins": 1
      }
    }
  ],
  "badge_points": 800
}
9 Feb 02:18:39 - Chat channel quaswexreport has 0 person(s) online
9 Feb 02:18:44 - Sending message to quaswexreport
9 Feb 02:18:44 - Received popup:
9 Feb 02:18:49 - Leaving chat channel: quaswexreport
9 Feb 02:18:49 - Leaving channel 10352
`

Still not able to talk.

**Comment by rossengeorgiev** [comment]
Ok, I'm out of ideas. Maybe, it only says its level 5, but its actually higher.

**Comment by Crazy-Duck** [comment]
Have you spent more than $5 on the account? Verified the email address?
http://steamcommunity.com/app/570/discussions/0/617330406652296100/

**Comment by bippum** [comment]
Yes that's how I got it working in the first place. It's almost like the account was blacklisted.

**Comment by Crazy-Duck** [comment]
But yours is still lvl 1 right? You need to have spent 5$ *and* leveled your account at least to lvl5

**Comment by qing5hu1** [comment]
Made over $30 worth (more than that) of purchases on the account, dating back to 2010. With the most recent purchase being Huniepop in Novmeber
![2000px-fiji_water_logo svg](https://cloud.githubusercontent.com/assets/23038323/22787173/31813d90-eefd-11e6-842f-df16348ce82c.png)

**Comment by Crazy-Duck** [comment]
Yes, but is its in-game dota 2 level > lvl 5?

**Comment by qing5hu1** [comment]
Yes it is
```"badge_points": 800```

**Comment by bippum** [comment]
This honestly seems like a Valve-lack-of-communication issue rather than a node-dota2 issue. And our use case is so niche it doesn't seem like a priority for Valve at the moment anyway. I made a Reddit post about this earlier which was linked in the initial issue post but it didn't get much traction. I really don't know what choice we have other than to wait.

**Comment by rossengeorgiev** [comment]
People who were spamming channels are to blame. Likely using `node-dota2`. I won't expect much after forcing Valve implement stupid blocks to counter spammers.

**Comment by hhuh** [comment]
I got my bot account to chat in public channels again.  Apparently you need to be over level 5 and have over 20 games of matchmaking.  I had 20 games of co-op bots and normal matchmaking but it still didn't work.  But now I made sure that I have 20 games of regular matchmaking games instead.  Although it didn't get the account to talk immediately, when I checked in after a few days, the bot is able to talk in public channels again.

**Comment by bippum** [comment]
Thanks for that info, I'll see if I can will myself to play those games :P

**Comment by Crazy-Duck** [comment]
Alright, gonna look to add that somewhere on the wiki or so

**Comment by bippum** [comment]
Well, the account has 20 games played, and I spent 6 dollars on on Golf with your Friends, and I can't talk still. Here's some screenshots:

 - http://puu.sh/uWsut/7256efae3e.png
 - http://puu.sh/uWsw9/5658ff857c.png

Gonna play a few more games on the account to see if that will kick it over.
