### ISSUE TITLE
requestMatches criteria question

### ISSUE THREAD

**Issue by altairmizuchi** [Arcana/node-dota2#433]
[criteria] - The options available for searching matches:
[hero_id]
[game_mode]
[date_min]
[date_max]
[matches_requested]
[start_at_match_id]
[min_players]
[tournament_games_only]
[account_id]
[league_id]
[skill]
[team_id] -
Is there any description for these parameters? Like format, type or something like this. Thank you

**Comment by devilesk** [comment]
```
        hero_id: "number",
        game_mode: "number",
        date_min: "number",
        date_max: "number",
        matches_requested: "number",
        start_at_match_id: "number",
        min_players: "number",
        tournament_games_only: "boolean",
        account_id: "number",
        league_id: "number",
        skill: "number",
        team_id: "number"
```

https://github.com/Arcana/node-dota2/blob/a1f51cb388b4705b4b4e1570bbe65a4809197499/handlers/match.js#L4-L16

https://github.com/Arcana/node-dota2/blob/a1f51cb388b4705b4b4e1570bbe65a4809197499/proto/dota_gcmessages_client.proto#L88-L101

**Comment by Crazy-Duck** [comment]
@altairmizuchi did @devilesk's response fix your problem?

**Comment by rossengeorgiev** [comment]
It worth to note that some of those option were disabled by Valve a long time ago, like `date_min` and `date_max`

**Comment by Crazy-Duck** [comment]
@rossengeorgiev if you know about stuff that's been deprecated, I'd very much like to know about it. It's kinda hard to keep up with everything valve deprecates

**Comment by rossengeorgiev** [comment]
I've not been keeping track. That message is also rate limited, and I think overuse results in temp ban for that message. I'm guessing here, but I think dotabuff might be using it heavily  to get skill rating for matches. Think tons of accounts.

**Comment by altairmizuchi** [comment]
Crap. I was really interested in those exact fields. Is there a way to request only mmr matches? I also have a strange problem with retrieving matches with specified account_id. As soon as I send it responses stop coming.
No response:
```
                Dota2.requestMatches({
                    "matches_requested": 25,
                    "account_id" : 43053140,
                    "tournament_games_only": false
                }
```
has response
```
                Dota2.requestMatches({
                    "matches_requested": 25,
                    "account_id" : 43053140,
                    "tournament_games_only": false
                }
```

**Comment by rossengeorgiev** [comment]
Like I said above, you only get the 500 most recent matches. Perhaps `account_id` works as filter over those 500 matches. If you are hoping to get recent match history of a specific player, you are out of luck, unless they share with thirdparty

**Comment by altairmizuchi** [comment]
Do you mean "Expose Public Match Data" option? If you do how will I get matches for such users only?
Is there a way to filter out mmr matches only?

**Comment by Crazy-Duck** [comment]
requestMatches indeed only works over the last 500 matches and is rate limited as @rossengeorgiev said. If you want the match history of a player, you need to use `requestPlayerMatchHistory`. However, since Valve's changes like two months or so ago, this only works for people on your friend list.

**Comment by altairmizuchi** [comment]
So I can get only 500 matches starting from specified match id or is it always only last 500 and start match id only works as filter?

**Comment by Crazy-Duck** [comment]
the start match id is a filter in these last 500 matches, since you only get them 25 at a time

**Comment by altairmizuchi** [comment]
So can I:
1) store last match id I requested
2) get new last match id
3) request by 500 from stored to new sequentially with filter
4) store new last match id and repeat after some time
?

**Comment by inShu** [comment]
https://api.steampowered.com/IDOTA2Match_570/GetMatchHistory/V001/?key=<key>&account_id=<account_id> will return last 500 matches for any account. It doesn't matter will they listed in global all matches list or not. **account_id** parameter is not applied as filter for **all matches** search. For sure.

**Comment by kevinyeo92** [comment]
requestMatchDetails() not available for Practice Match/Private Lobby?
