### ISSUE TITLE
configPracticeLobby - Help

### ISSUE THREAD

**Issue by zeTurk** [Arcana/node-dota2#434]
After joining a lobby, how would I go on about changing the settings with commands from lobby chat? 

```javascript
Dota2.createPracticeLobby(lobbyPassword, properties, function(err, data){
                   util.log(JSON.stringify(data));
               });

Dota2.practiceLobbyKickFromTeam(404305595); // Kick self from team to be placed in spectator slot. This number is the Dota 2 ID on your profile page.
```

I believe this is the method I need to call, but I am confused on how to operate it and also how to obtain the lobby_id. I'm pretty new here, so help would be appreciated. Thanks

configPracticeLobby(lobby_id, options, [callback])

**Comment by Crazy-Duck** [comment]
`configPracticeLobby` is indeed the function you need. You need to call it passing the ID of the lobby you want to configure and an object containing the options you want to configure. The currently supported ones are:
```
Dota2._lobbyOptions = {
    game_name: "string",
    server_region: "number",
    game_mode: "number",
    game_version: "number",
    cm_pick: "number",
    allow_cheats: "boolean",
    fill_with_bots: "boolean",
    allow_spectating: "boolean",
    pass_key: "string",
    series_type: "number",
    radiant_series_wins: "number",
    dire_series_wins: "number",
    allchat: "boolean",
    leagueid: "number",
    dota_tv_delay: "number",
    custom_game_mode: "string",
    custom_map_name: "string",
    custom_difficulty: "number",
    custom_game_id: "number",
};
```

**Comment by zeTurk** [comment]
How would I go on about getting the lobby_id? I know it's in the console logs but is there an object I can just access?

**Comment by gerlaic** [comment]
@zeTurk Yes. You can do like this:
```
Dota2.createPracticeLobby(["password",{configs},function(err,body){
    console.log(JSON.stringify(body));
}
```

And you will see the `lobby_id` inside `body`. It's a dictionary so it's easy to extract it

**Comment by zeTurk** [comment]
oh ok, thanks!
