### ISSUE TITLE
value constants mismatch DOTA_GC_TEAM vs match_outcome

### ISSUE THREAD

**Issue by shockwaves** [Arcana/node-dota2#436]
When lobby is ended, event `practiceLobbyUpdate` send lobby object with attribute `match_outcome`.
Value of this attribute can be is `2` (Dire) or `3` (Radiant).
But `DOTA_GC_TEAM` contains:
```
DOTA_GC_TEAM_GOOD_GUYS = 0;
DOTA_GC_TEAM_BAD_GUYS = 1;
```
it is inappropriate? there are ways to determine the winner of the lobby?

**Comment by rossengeorgiev** [comment]
You use the outcome enum.

https://github.com/Arcana/node-dota2/blob/31e823811667f4a5308d684659bdfc7ce9a171a2/proto/dota_shared_enums.proto#L315-L324

**Comment by shockwaves** [comment]
Thank you very much! your answer helped me! :)

**Comment by Crazy-Duck** [comment]
Can this be closed then?

**Comment by shockwaves** [comment]
yes!
