### ISSUE TITLE
Bug in handlers/chat.js

### ISSUE THREAD

**Issue by innerfears** [Arcana/node-dota2#445]
In function joinChat, the first instruction is:

`channel_type = channel_type || Dota2.schema.lookupEnum("DOTAChatChannelType_t").DOTAChannelType_Custom;`

this of course is done in order to make channel_type an optional argument. This overwrites channel_type if channel_type's value is 0 (false) but 0 is a valid value for channel_type.
From proto:

enum DOTAChatChannelType_t {
	DOTAChannelType_Regional = 0;
	DOTAChannelType_Custom = 1;
        ...
        ...
}

Channel_type 0 is regional chat, this makes it impossible to join regional channels (unless you pass the argument not as a number but as a string, in which case it doesn't evaluate to false)

**Comment by Crazy-Duck** [comment]
Good catch! I'll make sure it's fixed for 5.0.0. Gonna have to think about the most elegant way to fix this, might just have to add a 0-check 🤔

**Comment by innerfears** [comment]
You could do something like

`channel_type = channel_type == null ? Dota2.schema.lookupEnum("DOTAChatChannelType_t").DOTAChannelType_Custom : channel_type;`

**Comment by Crazy-Duck** [comment]
That wouldn't catch undefined. Think I'm gonna solve it like this:
```
if (channel_type !== 0)
        channel_type = channel_type || Dota2.schema.lookupEnum("DOTAChatChannelType_t").DOTAChannelType_Custom;
```

**Comment by Ne3tCode** [comment]
> That wouldn't catch undefined.

```javascript
console.log(undefined == null); // true
console.log(undefined === null); // false
```
JavaScript things ¯\\\_(ツ)\_/¯

**Comment by Crazy-Duck** [comment]
ugh, this is why I hate using == -_-'

**Comment by howardchung** [comment]
Some consider the `x == null` case the only acceptable use of `==` since it's a nice shorthand.

I prefer to use `===` everywhere, so I just explictly write out `x == null || x == undefined`

**Comment by Ne3tCode** [comment]
Maybe [`Number.isInteger(channel_type)`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isInteger)? At least we'll be sure that `type` is not string, object or something else.

**Comment by Crazy-Duck** [comment]
I don't think I'm going to go overboard on parameter validation, else we'll be doing more validation than actual functionality. The interface is defined and the GC will throw errors if we pass incorrect parameters. So the null/undefined check to verify there at least is a parameter present seems sufficient to me..

**Comment by Silur** [comment]
so again, what do people have to pass as parameter when we want to connect to regional channels? because neither `0`, `'0'`, or `DOTAChannelType_Regional` is working

**Comment by Silur** [comment]
btw the double tilde `~~` is an elegant way of checking for a zero value, it doesn't trigger on null and undefined but triggers both on 0 as number and '0' as string

**Comment by innerfears** [comment]
Just manually correct the bug on your own for now

**Comment by ProbablyPeps** [comment]
Can you show us the exact way to correct it please?

**Comment by innerfears** [comment]
In file handlers/chat.js

`Dota2.Dota2Client.prototype.joinChat = function(channel_name, channel_type) {
    channel_type = channel_type || Dota2.schema.lookupEnum("DOTAChatChannelType_t").DOTAChannelType_Custom;`

Add `if (channel_type !== 0)` before channel_type = ......

obtaining

`Dota2.Dota2Client.prototype.joinChat = function(channel_name, channel_type) {
if (channel_type !== 0)
        channel_type = channel_type || Dota2.schema.lookupEnum("DOTAChatChannelType_t").DOTAChannelType_Custom;`

**Comment by Crazy-Duck** [comment]
Issue is fixed on the doc branch (where I'm preparing v5.0.0). Be careful to read the CHANGELOG.md though, cause there have been a few changes to the API

**Comment by ProbablyPeps** [comment]
Thanks guys

**Comment by Silur** [comment]
I've already tried this and many alternatives yesterday, no channel check, make regional the default option and even hardcoding the regional option all without success the bot still creats a user channel with 0 users.

**Comment by Crazy-Duck** [comment]
Are you sure you're providing the correct name for the regional channel?

**Comment by innerfears** [comment]
Whenever i join a regional channel the log says it has 0 users to me too; don't be deceived, you actually joined the  channel, just listen for messages and log them if you want to make sure, or log in with another account through steam and check that the bot is in the channel

**Comment by rossengeorgiev** [comment]
Regional type channels don't get the member list from GC, but via a HTTP API.
