### ISSUE TITLE
Error: Cannot find module 'dota2' V2

### ISSUE THREAD

**Issue by clarityworld** [Arcana/node-dota2#45]
When i try to start with:
var Steam = require('steam'),
steamClient = new Steam.SteamClient(),
dota2 = require('dota2'),
Dota2 = new dota2.Dota2Client(steamClient, true);

I get this error:
Error: Cannot find module 'dota2'

Also i installed the packages via npm for sure !! 
http://puu.sh/aAKC1/708c03db1a.png This is installed ! But no dota module :/

Sorry :/ You closed my first iusse way to fast

**Comment by wotuthink** [comment]
@bontscho I am unable to view above link. Any other link where I can found how to make it work?

**Comment by bontscho** [comment]
@wotuthink that link i was posted is 4years old.

a good way to start would be the [Installation & Setup](https://github.com/Arcana/node-dota2#installation-and-setup) section of the README along with the mentioned [Examples](https://github.com/Arcana/node-dota2#examples) section of the README
