### ISSUE TITLE
Hosting Custom Games - Notes for later

### ISSUE THREAD

**Issue by jimmydorry** [Arcana/node-dota2#450]
Note for distant future me, or anyone else that wants this to happen:

You allegedly can't host custom games without their computed crc value (I haven't tested) according to their experience and the [protobuff](https://github.com/Arcana/node-dota2/blob/a470b22d25b985c43bd5f841f479e65a59f12f2a/proto/dota_gcmessages_client_match_management.proto#L119).

The potential [CRC64 algo](https://t.g-ds.io/awuExn) they may be using, obviously not compatible as is with node-js. There is probably already a node library for this somewhere out there. @psychonic also linked his [rough concept](https://t.g-ds.io/hKpHW3) and the [redis one](https://t.g-ds.io/wL5yRg) to give an idea of what it might look like.

Otherwise, this CRC value needs to be user-defined after each map update. Bit annoying that this may need to be defined. You would think that the client would just grab it from the workshop or from a meta info file distributed with the mods.

Thanks @psychonic and @DoctorGester

**Comment by ChrisPei** [comment]
Hi, your links are broken. I am also trying to find a way to calculate CRC, I really want to see related content.
