### ISSUE TITLE
How get regional chat channels ban information?

### ISSUE THREAD

**Issue by truered2** [Arcana/node-dota2#451]
Hello! How i get regional chat channels ban information? I guess it k_EMsgGCToGCPublicChatCommunicationBan but i don't know how send this request and read response. Help, please.

**Comment by rossengeorgiev** [comment]
k_EMsg `GCToGC` PublicChatCommunicationBan

**Comment by truered2** [comment]
I don't now you, rossengeorgiev. Can you talk me more information?

**Comment by Crazy-Duck** [comment]
He's highlighting the fact that the message you linked is a message that's exchanged between game coordinator instances and hence won't be responded to if sent from the client
