### ISSUE TITLE
Multiple lobbies by one bot

### ISSUE THREAD

**Issue by zeTurk** [Arcana/node-dota2#452]
When I create a lobby, start the game, then make the bot leave the lobby and try to start another lobby (while the other game is still going on) a new lobby is not created. Is this intended or am I doing something wrong?

**Comment by Crazy-Duck** [comment]
Yeah, I'm pretty sure you need to both leave and abandon the lobby. It's the same with the normal client, if you disconnect from an ongoing game, you need to confirm by abandoning

**Comment by zeTurk** [comment]
Yep, this worked.
