### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by zairkz** [Arcana/node-dota2#457]
I would like to ask if I launch the project with use the bot and node-dota2, can Valve block me((? Maybe i need some sort of permission from Valve?

**Comment by Crazy-Duck** [comment]
I'll quote our disclaimer from the README:

We do not in any way encourage people to use their own accounts when using this library. This library tries to mimic the behavior of the Dota 2 client to allow people to programmatically interact with the Dota 2 GC, however we make no efforts to hide this fact and it's pretty easy for Valve to detect clients using this library based on the generated traffic. While Valve has not yet expressed a dislike regarding reverse engineering projects like this one, it's not unimaginable that this might one day change and result in VAC bans.
