### ISSUE TITLE
requestFriendPracticeLobbyList

### ISSUE THREAD

**Issue by notscimmy** [Arcana/node-dota2#458]
This function is always giving an empty response even if I have a friend with an open practice lobby with friends/public visibility. I've tried it on a fresh account and an account with a game purchased. It also does not provide an error code.

Anybody have any idea what is going on?

**Comment by swangboy55** [comment]
Can confirm, it is not working for me either

**Comment by Crazy-Duck** [comment]
Do you receive an actual response from the GC or it just never answers?

**Comment by Passerby** [comment]
> Do you receive an actual response from the GC or it just never answers?


this method need friends steam id


`
    var payload = new Dota2.schema.CMsgFriendPracticeLobbyListRequest({
        "friends": [123, 456]
    });
`
