### ISSUE TITLE
Cannot send message to a channel you have not joined

### ISSUE THREAD

**Issue by kevinyeo92** [Arcana/node-dota2#459]
> Note: Lobby_lobby_id is the arguments I got from practiceLobbyUpdate after created a lobby. I hard coded it there as an example.

```
var channeltype = dota2.schema.DOTAChatChannelType_t.DOTAChannelType_Lobby;
setTimeout(function() {
    Dota2.joinChat('Lobby_24995653311042253', channeltype);
}, 1000);
```
> Joining chat channel: Lobby_24995653311042253
> Chat channel Lobby_24995653311042253 has 1 person(s) online
```
setTimeout(function () {
    Dota2.sendMessage('Lobby_24995653311042253', 'Test chat.', channeltype);
}, 7000);

Dota2.on("chatJoined", function (data) {
     util.log(data);
});
```
chatJoined's response --- my bot had joined the Lobby channel that my bot created. 

> response: 0, channel_name: 'Lobby_24995653311042253', channel_type: 3

I am able to joinChat and sendmessage using the last January/February's commits.
I just updated again with current new commits. Now I am having problem sending message to Lobby.

Anyone encounter same issue?

**Comment by kevinyeo92** [comment]
my bot is unable to send message to Lobby. 
`Dota2.sendMessage('Lobby_24995653311042253', 'Test chat.', channeltype);`

> Cannot send message to a channel you have not joined

**Comment by Crazy-Duck** [comment]
Can you try to wrap that statement in a settimeout with 0ms delay?

**Comment by kevinyeo92** [comment]
I tried everything, it does not work. It error message was "Cannot send message to a channel you have not joined".

Before I pull this new commits, my code sendMessage code was working fine. I'm just curious was it only me encounter such issue.

**Comment by Crazy-Duck** [comment]
Hmm, can you change L23 of chat.js in your version of the library to `return ("" + item.channel_id === "" + channel_id);`

**Comment by kevinyeo92** [comment]
changed, not working.. my code doesn't hit L23 of chat.js

**Comment by Crazy-Duck** [comment]
Could you provide a minimal working example of your code that provokes the error?

**Comment by kevinyeo92** [comment]
> Attached URL is screenshot of my example code

[http://imgur.com/a/23VXP](url)

Not sure if I am doing it correctly. But this code worked previously.

**Comment by jimmydorry** [comment]
Rather than give something that someone could use to help you with your problem, you gave them a screenshot? To run that code, one would need to type it all out, thus wasting more time... and it's not even a minimal working example. Seems legit. 

If it was me trying to help you, I would have just closed the issue.

**Comment by kevinyeo92** [comment]
Sorry @jimmydorry.. I will workout and paste out a run-able code.

**Comment by csplkiller** [comment]
I have the same problem
My code:

```
			 console.log("=========== leavePracticeLobby ===========");
			 Dota2.leavePracticeLobby(function(err, body){
			 		console.log("=========== createPracticeLobby ===========");
			 		Dota2.createPracticeLobby(properties, function(err, body){
			 				console.log(JSON.stringify(body));
			 				setTimeout(function(){
			 						console.log("=========== inviteToLobby ===========");
			 						Dota2.inviteToLobby('76561197974615568');
			 					}, 1000);
			 			});
			 	});
								 
            Dota2.on("practiceLobbyUpdate", function(lobby_data) {
                lobby = lobby_data;
    			Dota2.joinChat('Lobby_' + lobby.lobby_id, 3);
            });


	       	Dota2.on("chatMessage", function(channel, personaName, message) {
	            util.log("[" + channel + "] " + personaName + ": " + message);
 				setTimeout(function(){
 					console.log('send to channel: Lobby_' + lobby.lobby_id);
    				Dota2.sendMessage('Lobby_' + lobby.lobby_id, "Hello from BOT...", 3);
 					}, 1000);
	        });
```

Bot log:

```
14 Apr 17:36:46 - Chat channel Lobby_25033785964635081 has 1 person(s) online
=========== inviteToLobby ===========
14 Apr 17:36:46 - Inviting 76561197974615568 to a lobby.
14 Apr 17:36:47 - Created invitation to online user 76561197974615568
14 Apr 17:36:49 - Received lobby snapshot for lobby ID 25033785964635081
14 Apr 17:36:49 - Joining chat channel: Lobby_25033785964635081
14 Apr 17:36:49 - 76561197974615568 joined channel Lobby_25033785964635081
14 Apr 17:36:49 - Chat channel Lobby_25033785964635081 has 2 person(s) online
14 Apr 17:37:09 - Received chat message from hampy9907 in channel Lobby_25033785964635081
14 Apr 17:37:09 - [Lobby_25033785964635081] hampy9907: Hello FROM PLAYER
send to channel: Lobby_25033785964635081
14 Apr 17:37:10 - Sending message to Hello from BOT...
14 Apr 17:37:10 - Cannot send message to a channel you have not joined.
```

**Comment by csplkiller** [comment]
I understood the problem.
The fact is that in the examples there are minor errors
In this case, messed up the message and the name of the channel.

Dota2.sendMessage("Hello from BOT...", 'Lobby_' + lobby.lobby_id, 3); // Right code
