### ISSUE TITLE
kMsg_name returns undefined.

### ISSUE THREAD

**Issue by qing5hu1** [Arcana/node-dota2#461]
```js
client.dota2.on('unhandled', (kMsg, kMsg_name) => {
			util.log(`[Dota] UNHANDLED MESSAGE: (${kMsg}) ${kMsg_name}`)
			client.createMessage(config.discord.dev_channel, `:warning: DOTA 2 Unhandled Message: \`(${kMsg}) ${kMsg_name}\``);
});
```

Console shows this:
```
28 Mar 06:51:14 - [Dota] UNHANDLED MESSAGE: (7388) undefined
```

Discord as well:
https://i.imgur.com/wAzWF05.png

**Comment by Crazy-Duck** [comment]
What version of the library are you using? Cause I just tested it with the latest version and everything seems to work fine...

**Comment by qing5hu1** [comment]
4.2.1, will be rewriting on 5.0 when you push it to stable

**Comment by Crazy-Duck** [comment]
Can you try with v5.0.0? We just pushed it to npm

**Comment by qing5hu1** [comment]
Updated to 5.0.0, is there anyway I can check this? or I'll keep monitoring on discord for an unhandled message.

**Comment by Crazy-Duck** [comment]
Don't think so. In any case, there's a unit test to verify if the function behaves correctly in 5.0.0 and it passes :)

**Comment by qing5hu1** [comment]
https://u.nya.is/yrmcnm.PNG 
it works now :)
