### ISSUE TITLE
Connection closed by server

### ISSUE THREAD

**Issue by markrmessmore** [Arcana/node-dota2#465]
I'm certain that this is a problem between my keyboard and my chair however I'm honestly not certain what's going on. I've followed the instructions in terms of installing:

```npm install dota2```

I've moved ```config.js.example``` to ```config.js```. I've entered in my steambot account's username and password (I've double and triple checked-it), and when running example.js I get:

```30 Mar 14:45:30 - Connection closed by server: Error: Disconnected```

Similarly when I run example2.js I get:

```30 Mar 14:46:02 - Connection closed by server.```

test.js tells me ```describe is not defined``` (not sure if there is a package dependency which for some reason is not installed).

I don't have an error number or anything else to go off of so what am I missing/overlooking?

**Comment by Crazy-Duck** [comment]
The tests should be executed with moccha while having the two environment variables set to the username and password. However, I doubt that that will work when the examples don't.. Does the account have 2fa activated or so?

**Comment by Crazy-Duck** [comment]
There was just a patch, try again in like half an hour, GC might be rebooting as well

**Comment by markrmessmore** [comment]
2fa is not activated. I was able to log in previously with the steam-user module however haven't been able to get this to work. And now that I've done a bit more digging I see the test.js isn't really meant to be run, the example.js & example2.js are the true tests.

Errors are still happening.

**Comment by markrmessmore** [comment]
FWIW I wanted to reorganize my project so I spent this evening doing that and did a fresh install of the dota2 module...same result.

However I did notice not all the files/folders would show up when I did the ```npm install dota2```.  I downloaded the zip to get the examples, could that be causing this?

**Comment by Crazy-Duck** [comment]
The exmples etc. are no longer included in the npm package, since you really don't need those to use the library. If you want to run the examples, you are indeed better off forking/downloading the repo

**Comment by Crazy-Duck** [comment]
Do you have the config.js file in the same directory as the example files? Did you comment out the lines in the config for 2FA? Can you add a few printlines right before L193 and L195 in example.js? Make it look like this:
```
util.log(logOnDetails);
steamClient.connect();
steamClient.on('connected', function() {
    util.log("Connected to steam, attempting logon");
    steamUser.logOn(logOnDetails);
});
```

**Comment by markrmessmore** [comment]
The config.js IS in the same directory as the example files. I did comment out the config for 2FA (I also tried it as being ```""``` however no change.) I've changed lines 193 and following as you recommended. Here is the output:

```
31 Mar 08:50:58 - { account_name: '*****', password: '*********' }
31 Mar 08:50:59 - Connected to steam, attempting logon
31 Mar 08:50:59 - Connection closed by server: Error: Disconnected
```

For any wondering, yes the correct account name and password were showing up, I've commented them out here.

**Comment by markrmessmore** [comment]
Marking this as resolved.

What resolved it? Nothing really. Steam Guard was turned off. I turned it on. Verified. Turned it back off. Now it logs in. Volvo pls.

Thanks for your help.

**Comment by rossengeorgiev** [comment]
There are multiple things that can cause a disconnect, but without providing the `LogonResponse.eresult`, there is no way to debug. You could've been rate limited due to many failed logins, typically 15 minutes. Or maybe the CM you connected to was out of service

**Comment by Un1xMida** [comment]
guys when i try to run the example.js after installing this libs [steam , dota2] when i node example.js i got this errors
`SteamClient {
  _events: [Object: null prototype] {
    message: [
      [Function: bound ],
      [Function: bound ],
      [Function: bound ],
      [Function: bound ]
    ],
    logOnResponse: [
      [Function: bound ],
      [Function: bound ],
      [Function: onSteamLogOn]
    ],
    connected: [Function],
    loggedOff: [Function: onSteamLogOff],
    error: [Function: onSteamError],
    servers: [Function: onSteamServers]
  },
  _eventsCount: 6,
  _maxListeners: undefined,
  _jobs: {},
  _currentJobID: 0,
  sessionID: 0,
  _connection: Connection {
    connecting: true,
    _hadError: false,
    _parent: null,
    _host: null,
    _readableState: ReadableState {
      objectMode: false,
      highWaterMark: 16384,
      buffer: BufferList { head: null, tail: null, length: 0 },
      length: 0,
      pipes: null,
      pipesCount: 0,
      flowing: false,
      ended: false,
      endEmitted: false,
      reading: false,
      sync: true,
      needReadable: true,
      emittedReadable: false,
      readableListening: true,
      resumeScheduled: false,
      emitClose: false,
      autoDestroy: false,
      destroyed: false,
      defaultEncoding: 'utf8',
      awaitDrainWriters: null,
      multiAwaitDrain: false,
      readingMore: false,
      decoder: null,
      encoding: null,
      [Symbol(kPaused)]: null
    },
    readable: false,
    _events: [Object: null prototype] {
      end: [Array],
      readable: [Function: bound ],
      packet: [Function: bound ],
      close: [Function: bound ],
      error: [Function],
      connect: [Function],
      timeout: [Function]
    },
    _eventsCount: 7,
    _maxListeners: undefined,
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: false,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
SteamClient {
  _events: [Object: null prototype] {
    message: [
      [Function: bound ],
      [Function: bound ],
      [Function: bound ],
      [Function: bound ]
    ],
    logOnResponse: [
      [Function: bound ],
      [Function: bound ],
      [Function: onSteamLogOn]
    ],
    connected: [Function],
    loggedOff: [Function: onSteamLogOff],
    error: [Function: onSteamError],
    servers: [Function: onSteamServers]
  },
  _eventsCount: 6,
  _maxListeners: undefined,
  _jobs: {},
  _currentJobID: 0,
  sessionID: 0,
  _connection: Connection {
    connecting: true,
    _hadError: false,
    _parent: null,
    _host: null,
    _readableState: ReadableState {
      objectMode: false,
      highWaterMark: 16384,
      buffer: BufferList { head: null, tail: null, length: 0 },
      length: 0,
      pipes: null,
      pipesCount: 0,
      flowing: false,
      ended: false,
      endEmitted: false,
      reading: false,
      sync: true,
      needReadable: true,
      emittedReadable: false,
      readableListening: true,
      resumeScheduled: false,
      emitClose: false,
      autoDestroy: false,
      destroyed: false,
      defaultEncoding: 'utf8',
      awaitDrainWriters: null,
      multiAwaitDrain: false,
      readingMore: false,
      decoder: null,
      encoding: null,
      [Symbol(kPaused)]: null
    },
    readable: false,
    _events: [Object: null prototype] {
      end: [Array],
      readable: [Function: bound ],
      packet: [Function: bound ],
      close: [Function: bound ],
      error: [Function],
      connect: [Function],
      timeout: [Function]
    },
    _eventsCount: 7,
    _maxListeners: undefined,
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: false,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      bufferedRequest: null,
      lastBufferedRequest: null,
      pendingcb: 0,
      prefinished: false,
      errorEmitted: false,
      emitClose: false,
      autoDestroy: false,
      bufferedRequestCount: 0,
      corkedRequestsFree: [Object]
    },
    writable: true,
    allowHalfOpen: false,
    _sockname: null,
    _pendingData: null,
    _pendingEncoding: '',
    server: null,
    _server: null,
    timeout: 1000,
    [Symbol(asyncId)]: 8,
    [Symbol(kHandle)]: TCP {
      reading: false,
      onconnection: null,
      [Symbol(owner_symbol)]: [Circular]
    },
    [Symbol(kSetNoDelay)]: false,
    [Symbol(lastWriteQueueSize)]: 0,
    [Symbol(timeout)]: Timeout {
      _idleTimeout: 1000,
      _idlePrev: [TimersList],
      _idleNext: [TimersList],
      _idleStart: 18423,
      _onTimeout: [Function: bound ],
      _timerArgs: undefined,
      _repeat: null,
      _destroyed: false,
      [Symbol(refed)]: false,
      [Symbol(asyncId)]: 7,
      [Symbol(triggerId)]: 1
    },
    [Symbol(kBuffer)]: null,
    [Symbol(kBufferCb)]: null,
    [Symbol(kBufferGen)]: null,
    [Symbol(kCapture)]: false,
    [Symbol(kBytesRead)]: 0,
    [Symbol(kBytesWritten)]: 0
  },
  [Symbol(kCapture)]: false
}
Hint: hit control+c anytime to enter REPL.
2 Mar 22:01:26 - Connection closed by server: Error: Disconnected`
