### ISSUE TITLE
Can a given bot create a match, start the game, quit the game then start another practiceLobby? 

### ISSUE THREAD

**Issue by JasonMcz** [Arcana/node-dota2#472]
Can a given bot create a match, 
start the game, quit the game then start another practiceLobby?

**Comment by Crazy-Duck** [comment]
Yes indeed it can, just follow your call to `launchPracticeLobby` with a call to `leavePracticeLobby`

**Comment by JasonMcz** [comment]
Tried this method and bot ended up inviting users to spectate the game it has lobby it has created?

**Comment by Crazy-Duck** [comment]
Try to follow up the `leavePracticeLobby` call with an `abandonCurrentGame`call, before you create the new one.

**Comment by csplkiller** [comment]
After I call leavePracticeLobby and abandonCurrentGame, I get an error in the match. It can continue to play - but the error seems to players critical and they leave the server.


![2017-04-15_11-59-37](https://cloud.githubusercontent.com/assets/7470513/25062367/bb00fd4a-21d3-11e7-9e2c-1339bfb938b1.png)


My Code:

```
// LOBBY DATA
var properties = {
	"server_region": dota2.ServerRegion.EUROPE,
	"game_mode": dota2.schema.DOTA_GameMode.DOTA_GAMEMODE_CM,
	"game_name": "CSPL_lobby2",
	"pass_key": "1234",
	"leagueid": 2091
};

 // LEAVE BEFORE CREATE
 Dota2.leavePracticeLobby(function(err, body){
 		// CREATE LOBBY
 		Dota2.createPracticeLobby(properties, function(err, body){
 				console.log(JSON.stringify(body));
 				// INVITE TO LOBBY
 				setTimeout(function(){
				Dota2.inviteToLobby('76561197974615568'); // Humpy
				Dota2.inviteToLobby('76561198094710754'); // HOLA
 						
 					}, 1000);
 			});
 	});
					 
Dota2.on("practiceLobbyUpdate", function(lobby_data) {
if(lobby == null){
		Dota2.joinChat('Lobby_' + lobby_data.lobby_id, 3);
		}
    lobby = lobby_data;
    // LOBBY GAME STATED ... 
    if(typeof lobby.game_state != 'undefined' && lobby.game_state == 2){
 		Dota2.leavePracticeLobby(function(err, body){
			
			console.log(JSON.stringify(body));
	 		console.log('==============abandonCurrentGame...');
	 		Dota2.abandonCurrentGame(function(err, body){//abandonCurrentGame
	 			console.log(JSON.stringify(body));
	 			});
 			});

		}
});

````

Bot log:

```
node example2.js
15 Apr 11:59:02 - Logged on.
15 Apr 11:59:02 - Launching Dota 2
15 Apr 11:59:02 - Received servers.
15 Apr 11:59:03 - Sending ClientHello
15 Apr 11:59:03 - GC Connection Status unreliable - 3
15 Apr 11:59:04 - Received client welcome.
15 Apr 11:59:04 - Node-dota2 ready.
BOT STEAM64 ID: 76561198380180326
15 Apr 11:59:04 - Sending match CMsgPracticeLobbyLeave request
15 Apr 11:59:04 - UNHANDLED MESSAGE k_EMsgDOTAGetEventPointsResponse
15 Apr 11:59:04 - Cache(s) subscribed, type(s): 7
15 Apr 11:59:04 - Unhandled cache ID: 7
15 Apr 11:59:04 - Received create/flip/shuffle/kick/launch/leave response {"result":"DOTA_JOIN_RESULT_INVALID_LOBBY"}
15 Apr 11:59:04 - Sending match CMsgPracticeLobbyCreate request
15 Apr 11:59:04 - Cache(s) subscribed, type(s): 2004
15 Apr 11:59:05 - Received lobby snapshot for lobby ID 25035152863536422
15 Apr 11:59:05 - Joining chat channel: Lobby_25035152863536422
15 Apr 11:59:05 - Received create/flip/shuffle/kick/launch/leave response {"result":"DOTA_JOIN_RESULT_ALREADY_IN_GAME"}
{"result":"DOTA_JOIN_RESULT_ALREADY_IN_GAME"}
15 Apr 11:59:05 - Chat channel Lobby_25035152863536422 has 1 person(s) online
=========== inviteToLobby ===========
15 Apr 11:59:06 - Inviting 76561197974615568 to a lobby.
15 Apr 11:59:06 - Inviting 76561198094710754 to a lobby.
15 Apr 11:59:06 - Created invitation to online user 76561197974615568
15 Apr 11:59:06 - Created invitation to online user 76561198094710754
15 Apr 11:59:08 - Received lobby snapshot for lobby ID 25035152863536422
15 Apr 11:59:08 - Received lobby snapshot for lobby ID 25035152863536422
15 Apr 11:59:09 - 76561197974615568 joined channel Lobby_25035152863536422
15 Apr 11:59:09 - 76561198094710754 joined channel Lobby_25035152863536422
15 Apr 11:59:11 - Received lobby snapshot for lobby ID 25035152863536422
15 Apr 11:59:14 - Received lobby snapshot for lobby ID 25035152863536422
15 Apr 11:59:20 - Received chat message from hampy9907 in channel Lobby_25035152863536422
15 Apr 11:59:20 - [Lobby_25035152863536422] hampy9907: start
=============Match starting...
15 Apr 11:59:20 - Sending match CMsgPracticeLobbyLaunch request
15 Apr 11:59:21 - Received lobby snapshot for lobby ID 25035152863536422
15 Apr 11:59:21 - Received create/flip/shuffle/kick/launch/leave response {"result":"DOTA_JOIN_RESULT_ALREADY_IN_GAME"}
Match started
{"result":"DOTA_JOIN_RESULT_ALREADY_IN_GAME"}
send to channel: Lobby_25035152863536422
15 Apr 11:59:21 - Sending message to Lobby_25035152863536422
15 Apr 11:59:21 - UNHANDLED MESSAGE k_EMsgGCPingRequest
15 Apr 11:59:21 - Received lobby snapshot for lobby ID 25035152863536422
15 Apr 11:59:22 - UNHANDLED MESSAGE k_EMsgGCToClientSteamDatagramTicket
15 Apr 11:59:22 - Received lobby snapshot for lobby ID 25035152863536422
15 Apr 11:59:22 - Received lobby snapshot for lobby ID 25035152863536422
15 Apr 11:59:22 - Received lobby snapshot for lobby ID 25035152863536422
15 Apr 11:59:28 - Received lobby snapshot for lobby ID 25035152863536422
=============leavePracticeLobby...
15 Apr 11:59:28 - Sending match CMsgPracticeLobbyLeave request
15 Apr 11:59:28 - Received create/flip/shuffle/kick/launch/leave response {"result":"DOTA_JOIN_RESULT_INVALID_LOBBY"}
{"result":"DOTA_JOIN_RESULT_INVALID_LOBBY"}
==============abandonCurrentGame...
15 Apr 11:59:28 - Sending match CMsgAbandonCurrentGame request
15 Apr 11:59:29 - Cache unsubscribed, 25035152863536422
15 Apr 12:00:38 - 76561198094710754 left channel Lobby_25035152863536422
15 Apr 12:02:16 - 76561197974615568 left channel Lobby_25035152863536422

```

**Comment by angel200sdnot** [comment]
Have you tried making the bot leave after the game starts?

**Comment by csplkiller** [comment]
See my code:

I create a lobby:
leavePracticeLobby  - Just in case
createPracticeLobby

After starting the match, I do:
leavePracticeLobby
abandonCurrentGame

...

**Comment by csplkiller** [comment]
Maybe I do not understand something?
Can you give a small sample code?

**Comment by csplkiller** [comment]
The task is this. Launch a match for the players.
Disconnect from server
Exit the lobby
...
Create a new match (lobby) with new parameters

**Comment by angel200sdnot** [comment]
I tried a lot of things to fix this issues and i couldn't, the only thing i didnt try was making the bot leave after the game started when everyone picked heroes

I didn't try it because i didn't want a downtime between lobbies

add this to you practiceLobbyUpdate event listener and remove the other disconnection method you were using

```javascript
//lobby.game_state == 4 means everyone got in the game after picking the heroes
if (lobby.game_state == 4 { 
    Dota2.abandonCurrentGame();
}
```

if that doesnt work then add Dota2.leavePracticeLobby();

**Comment by csplkiller** [comment]
Yes, this option seems to work - I get a message about communication error with the server for literally 1-3 seconds - after which it disappears ...

**Comment by angel200sdnot** [comment]
Then it doesn't fix the issue, it only hides it

One last thing you can try is adding a timeout so it doesnt even show those 1-3 seconds

```javascript
//lobby.game_state == 4 means everyone got in the game after picking the heroes
if (lobby.game_state == 4 { 
    setTimeout(function() {
        Dota2.abandonCurrentGame();
        //Remaking lobby method goes here or in the practiceLobbyCleared listener
    }, 5000); //5 seconds, you can play with this to see if it gets better
}
```
Thats as much as i can help you, if you do manage to hide the message complelety post it here and close the issue

**Comment by Crazy-Duck** [comment]
Alright, there seems to be a lot of misunderstanding going on around here, so let me clarify. When your bot creates a lobby, invites people to it, sets everything up, everyone (your bot included) is just connected to the Dota 2 Game Coordinator. However, once your bot calls `launchPracticeLobby', the GC sends a server ID to all people inside the lobby. Based on that ID everyone is supposed to connect to the actual game servers to start the game. However, your bot doesn't do that (since it's incapable of doing that seeing that functionality doesn't exist in this library). As soon as you launched the lobby, you leave it (which in the normal client would show you the green reconnect and the red abandon buttons) and abandon it straight after. What follows is an unhandled case in the Dota2 server code. The game server has people connecting to it for a game, from which there is one (non-crucial for the game's progress) who isn't connecting, but immediately has abandoned. Following that it shows the screen it would show in normal matchmaking when someone leaves while everyone is loading in, i.e. the connection failure error message (which is what happened, your bot failed to connect). However, since only the people in actual player slots are crucial for starting the game, it lets the picking phase and the game continue as if nothing happens. As of now, to my knowledge, there is no way to not have this error message pop up..

**Comment by MikeShalin** [comment]
node js dota 2 bot lunch match, then I see attention "players connection", then I leave match to lobby

**Comment by danielvieira43** [comment]
What are you doing to collect the game result?
1- Bot create and invite people;
2- People join lobby and bot launch the game.
