### ISSUE TITLE
Deprecate 4.2.0, 4.2.1 and 5.0.0

### ISSUE THREAD

**Issue by Crazy-Duck** [Arcana/node-dota2#474]
@RJacksonm1 could you by any chance [deprecate](https://docs.npmjs.com/cli/deprecate) 4.2.0, 4.2.1 and 5.0.0 on npm? These versions have a dependency on protobufjs ^6.0.0 which got broken with the release of 6.7.0.
I fixed this in 5.0.1 by forcing ^6.7.0. Our v4.1.0 and below still depend on protobufjs ^5.0.0

**Comment by RJacksonm1** [comment]
Done. I've deprecated everything under 5.0.1 (the really old versions surely won't be in a working state either).

**Comment by Crazy-Duck** [comment]
Alright, thanks!
