### ISSUE TITLE
What is UNHANDLED MESSAGE 4009?

### ISSUE THREAD

**Issue by zackcoburn** [Arcana/node-dota2#476]
I have a bot that works fine for a while and eventually starts getting this error:

10 Apr 14:09:56 - Dota2 fromGC: undefined
10 Apr 14:09:56 - UNHANDLED MESSAGE 4009

What does it mean? Is it a ban?

**Comment by rossengeorgiev** [comment]
It not a ban, just unhandled message. Don't worry

**Comment by zackcoburn** [comment]
How do I avoid it? It is making it impossible to run a bot.

**Comment by Crazy-Duck** [comment]
How does it make it impossible to run a bot? It's just a notification printed to the console. If you don't want to see it anymore, disable debug output.. I also take it you're not running the latest version of the lib, cause then the output would specify what type of message it was that wasn't handled.

**Comment by zackcoburn** [comment]
Yep, you are right, it was my fault!
