### ISSUE TITLE
Firstbloodio forked and pushed our repo to npm

### ISSUE THREAD

**Issue by Crazy-Duck** [Arcana/node-dota2#477]
Anyone has seen this yet?
https://www.npmjs.com/package/fb-dota2
https://www.npmjs.com/package/fb-steam

It seems like the people at firstblood.io forked our repo and node-steam's and pushed the fork to npm, under their own name o_O

**Comment by howardchung** [comment]
They're free to do that.  Did they add any features we want to merge back?

**Comment by jimmydorry** [comment]
We will be hearing more from them soon, I assume. They are doing blockchain (Etherium) powered betting, combined with their own dueling and queueing system. They got in contact with the only public email associated with this repo, and were pointed to this issue tracker.

**Comment by Crazy-Duck** [comment]
Strange thing is they didn't seem to have added anything, the only change I see atm is that they've commented one debug output. All the links in the README and stuff still point to this repo. Just thought it strange to basically push what is an identical clone to npm. It's not like this lib is stale or that we don't take requests :thinking:

**Comment by jimmydorry** [comment]
I imagine this is why they tried to get in contact to "bounce ideas" off us. :laughing:

Time will tell, I guess. I just hope they commit back what ever innovations they make... as it wouldn't make sense for them to add firstblood specific stuff to what should just be a library.

**Comment by Crazy-Duck** [comment]
I'll keep an eye on their repo from time to time; if something interesting pops up, I'll go steal it :laughing:

**Comment by rossengeorgiev** [comment]
🍿
