### ISSUE TITLE
createPracticeLobby error

### ISSUE THREAD

**Issue by csplkiller** [Arcana/node-dota2#478]
Please help me with the creation of the lobby
When I try to create a lobby, I get an error
I can not understand what I'm doing wrong.

```
			var password = "1234";
            var properties = {
				"game_name": "mynewlobby",
				"server_region": dota2.ServerRegion.EUROPE,
				"game_mode": dota2.schema.DOTA_GameMode.DOTA_GAMEMODE_CM,
				"series_type": 2,
				"game_version": 1,
				"allow_cheats": false,
				"fill_with_bots": false,
				"allow_spectating": true,
				"pass_key": password,
				"radiant_series_wins": 1,
				"dire_series_wins": 0,
				"allchat": false
            	};

			Dota2.createPracticeLobby(properties, function(err,body){
				console.log(err);
			    console.log(JSON.stringify(body));
			});
```

And I get the following result:

```
/scripts/dota2/examples# node example2.js
14 Apr 13:25:43 - Logged on.
14 Apr 13:25:43 - Launching Dota 2
14 Apr 13:25:43 - Received servers.
14 Apr 13:25:44 - Sending ClientHello
14 Apr 13:25:49 - Sending ClientHello
14 Apr 13:25:50 - Received client welcome.
14 Apr 13:25:50 - Node-dota2 ready.
14 Apr 13:25:50 - Sending match CMsgPracticeLobbyCreate request
14 Apr 13:25:50 - Cache(s) subscribed, type(s): 1,7,39,2007,2008
14 Apr 13:25:50 - Received inventory snapshot
14 Apr 13:25:50 - Unhandled cache ID: 7
14 Apr 13:25:50 - Unhandled cache ID: 39
14 Apr 13:25:50 - Unhandled cache ID: 2007
14 Apr 13:25:50 - Unhandled cache ID: 2008
14 Apr 13:25:50 - Received create/flip/shuffle/kick/launch/leave response {"result":"DOTA_JOIN_RESULT_INVALID_LOBBY"}
2
{"result":"DOTA_JOIN_RESULT_INVALID_LOBBY"}

```
Sometimes produces this error - DOTA_JOIN_RESULT_ALREADY_IN_GAME

**Comment by csplkiller** [comment]
node -v
v7.8.0
package.json

**Comment by csplkiller** [comment]
```
			var password = "1234";
            var properties = {
				"game_name": "mynewlobby",
				"pass_key": password
            	};

			console.log("=========== leavePracticeLobby ===========");
			Dota2.leavePracticeLobby(function(err, body){
			    console.log(JSON.stringify(err));
			    console.log(JSON.stringify(body));

				console.log("=========== createPracticeLobby ===========");
				Dota2.createPracticeLobby(properties, function(err, body){
				    console.log(JSON.stringify(body));

					console.log("=========== inviteToLobby ===========");
		            Dota2.inviteToLobby('76561198295710682', function(err, data){
		                util.log(JSON.stringify(data));
		            });
				});
			});
```

result:

```
14 Apr 14:17:08 - Logged on.
14 Apr 14:17:08 - Launching Dota 2
14 Apr 14:17:08 - Received servers.
14 Apr 14:17:09 - Sending ClientHello
14 Apr 14:17:14 - Sending ClientHello
14 Apr 14:17:14 - Received client welcome.
14 Apr 14:17:14 - Node-dota2 ready.
=========== leavePracticeLobby ===========
14 Apr 14:17:14 - Sending match CMsgPracticeLobbyLeave request
14 Apr 14:17:14 - Cache(s) subscribed, type(s): 1,7,39,2007,2008
14 Apr 14:17:14 - Received inventory snapshot
14 Apr 14:17:14 - Unhandled cache ID: 7
14 Apr 14:17:14 - Unhandled cache ID: 39
14 Apr 14:17:14 - Unhandled cache ID: 2007
14 Apr 14:17:14 - Unhandled cache ID: 2008
14 Apr 14:17:15 - Cache unsubscribed, 25033785835572707
14 Apr 14:17:15 - Received create/flip/shuffle/kick/launch/leave response {"result":"DOTA_JOIN_RESULT_ALREADY_IN_GAME"}
null
{"result":"DOTA_JOIN_RESULT_ALREADY_IN_GAME"}
=========== createPracticeLobby ===========
14 Apr 14:17:15 - Sending match CMsgPracticeLobbyCreate request
14 Apr 14:17:15 - Cache(s) subscribed, type(s): 2004
14 Apr 14:17:15 - Received lobby snapshot for lobby ID 25033785843043991
14 Apr 14:17:15 - Received create/flip/shuffle/kick/launch/leave response {"result":"DOTA_JOIN_RESULT_ALREADY_IN_GAME"}
{"result":"DOTA_JOIN_RESULT_ALREADY_IN_GAME"}
=========== inviteToLobby ===========
14 Apr 14:17:15 - Inviting 76561198295710682 to a lobby.
14 Apr 14:17:16 - Created invitation to online user 76561198295710682
14 Apr 14:17:41 - Received lobby snapshot for lobby ID 25033785843043991
```

**Comment by csplkiller** [comment]
The lobby is created.
But I can not immediately get it ID

**Comment by csplkiller** [comment]
=========== leavePracticeLobby ===========
14 Apr 15:55:50 - Sending match CMsgPracticeLobbyLeave request
14 Apr 15:55:51 - Received create/flip/shuffle/kick/launch/leave response {"result":"DOTA_JOIN_RESULT_ALREADY_IN_GAME"}


=========== createPracticeLobby ===========
14 Apr 15:55:51 - Sending match CMsgPracticeLobbyCreate request
14 Apr 15:55:52 - Received create/flip/shuffle/kick/launch/leave response {"result":"DOTA_JOIN_RESULT_ALREADY_IN_GAME"}


=========== practiceLobbyKickFromTeam 76561198012945267 ===========
14 Apr 15:55:55 - Sending match CMsgPracticeLobbyKickFromTeam request
14 Apr 15:55:55 - Received create/flip/shuffle/kick/launch/leave response {"result":"DOTA_JOIN_RESULT_INVALID_LOBBY"}


=========== inviteToLobby ===========
14 Apr 15:55:57 - Inviting 76561197974615568 to a lobby.
14 Apr 15:55:57 - Created invitation to online user 76561197974615568
14 Apr 15:55:59 - Received lobby snapshot for lobby ID 25033785899541533


=========== practiceLobbyKickFromTeam 76561197974615568 ===========
14 Apr 15:56:17 - Sending match CMsgPracticeLobbyKickFromTeam request
14 Apr 15:56:17 - Received create/flip/shuffle/kick/launch/leave response {"result":"DOTA_JOIN_RESULT_ALREADY_IN_GAME"}
14 Apr 15:56:17 - {"result":"DOTA_JOIN_RESULT_ALREADY_IN_GAME"}

**Comment by csplkiller** [comment]
Sorry, node-dota2 is working.
Only returns why it is always the same errors.
I found a couple of errors in the code examples ...
Because of them it was difficult to start communicating with the library.

**Comment by Crazy-Duck** [comment]
You're not using the latest (5.0.1) version syntax of the library, so it's normal you're having issues.
`dota2.schema.DOTA_GameMode.DOTA_GAMEMODE_CM` does not work anymore, you need to change that to `dota2.schema.lookupEnum(DOTA_GameMode).values.DOTA_GAMEMODE_CM`.
Further, the reason why you're getting `DOTA_JOIN_RESULT_ALREADY_IN_GAME` is because you're not leaving your previous lobby before trying to start a new one. You need to first call `leavePracticeLobby` and `abandonCurrentGame` before you can start a new lobby

**Comment by csplkiller** [comment]
console.log(dota2.schema.DOTA_GameMode.DOTA_GAMEMODE_CM);

return 2

console.log(dota2.schema.lookupEnum(DOTA_GameMode).values.DOTA_GAMEMODE_CM);


ReferenceError
DOTA_GameMode is not defined
ReferenceError: DOTA_GameMode is not defined

Where can I get the latest version of the library?
I instal node-dota2 by instruction..
npm install steam
npm install node-dota2

My package.json:

```{
  "name": "dota2",
  "version": "5.0.1",
  "dependencies": {
    "long": "^3.0.0",
    "deferred": "^0.7.2",
    "merge": "^1.2.0",
    "protobufjs": "^6.7.0",
    "steam": "^1.2.0"
  },
  "devDependencies": {
    "mocha": "^3.0.2",
    "should": "^11.0.0"
  },
  "scripts": {
    "update": "bash update_proto.sh",
    "test": "mocha"
  },
  "readmeFilename": "README.md",
  "description": "A node-steam plugin for Dota 2.",
  "main": "index.js",
  "repository": {
    "type": "git",
    "url": "git://github.com/Arcana/node-dota2.git"
  },
  "keywords": [
    "steam",
    "valve",
    "dota"
  ],
  "license": "MIT"
}
```

**Comment by Crazy-Duck** [comment]
You're using the latest version, just the wrong syntax. The reason why you're getting a ReferenceError is because DOTA_GameMode should be passed as a string (my bad, I forgot them in the example I gave as well, it's updated now). Try this:
```
console.log(dota2.schema.lookupEnum('DOTA_GameMode').values.DOTA_GAMEMODE_CM);
```

**Comment by Crazy-Duck** [comment]
Btw, if you're receiving DOTA_JOIN_RESULT_ALREADY_IN_GAME in the debug output, but the error value in the return is null, disregard the debug output. Your lobby is created and available, it's just the debug output that's faulty. I'm going to check if I can do something about that..

**Comment by Crazy-Duck** [comment]
#482

**Comment by Gaever** [comment]
Hello. I've got the same error. I've repeat changes from #482 but still no success. Sometimes dota2.schema.lookupEnum('DOTA_GameMode').values.DOTA_GAMEMODE_CM returns 2, sometimes null.
Here's my code: 



				var creatingLobby = 1;
				var leavingLobby = 1;

				if(creatingLobby == 1){ 
					var properties = {
						"game_name": "MyLobby",
						"server_region": 0,
						"game_mode": dota2.schema.lookupEnum('DOTA_GameMode').values.DOTA_GAMEMODE_CM
					}
					Dota2.leavePracticeLobby(function(err, data){
						util.log('leavePracticeLobby');
						util.log(JSON.stringify(data));
						util.log(err);
						Dota2.createPracticeLobby(properties, function(err, data){
							util.log('createPracticeLobby');
							util.log(JSON.stringify(data));
							util.log(err);
						});
					});
				}

				if(leavingLobby == 1){
					setTimeout(function(){
						Dota2.leavePracticeLobby(function(err, data){
							util.log('leavePracticeLobby');
							util.log(JSON.stringify(data));
							util.log(err);
						});

					}, 10000);
				}



Log:

> 25 May 01:06:00 - Logged on.
25 May 01:06:00 - Launching Dota 2
25 May 01:06:00 - Received servers.
25 May 01:06:01 - Sending ClientHello
25 May 01:06:01 - Dota2 fromGC: k_EMsgGCClientWelcome
25 May 01:06:01 - Received client welcome.
Node-dota2 ready.
25 May 01:06:01 - Sending match CMsgPracticeLobbyLeave request
25 May 01:06:01 - Dota2 fromGC: k_ESOMsg_CacheSubscribed
25 May 01:06:01 - Cache(s) subscribed, type(s): 7
25 May 01:06:01 - Unhandled cache ID: 7
25 May 01:06:02 - Received create/flip/shuffle/kick/launch/leave response {"result":"DOTA_JOIN_RESULT_INVALID_LOBBY"}
25 May 01:06:02 - leavePracticeLobby
25 May 01:06:02 - {"result":"DOTA_JOIN_RESULT_INVALID_LOBBY"}
25 May 01:06:02 - 2
25 May 01:06:02 - Sending match CMsgPracticeLobbyCreate request
25 May 01:06:02 - Dota2 fromGC: k_ESOMsg_CacheSubscribed
25 May 01:06:02 - Cache(s) subscribed, type(s): 2004
25 May 01:06:02 - Received lobby snapshot for lobby ID 25091795504660013
25 May 01:06:02 - Received create/flip/shuffle/kick/launch/leave response {"result":"DOTA_JOIN_RESULT_ALREADY_IN_GAME"}
25 May 01:06:02 - createPracticeLobby
25 May 01:06:02 - {"result":"DOTA_JOIN_RESULT_ALREADY_IN_GAME"}
25 May 01:06:02 - null
25 May 01:06:11 - Sending match CMsgPracticeLobbyLeave request
25 May 01:06:12 - Dota2 fromGC: k_ESOMsg_CacheUnsubscribed
25 May 01:06:12 - Cache unsubscribed, 25091795504660013
25 May 01:06:12 - Received create/flip/shuffle/kick/launch/leave response {"result":"DOTA_JOIN_RESULT_ALREADY_IN_GAME"}
25 May 01:06:12 - leavePracticeLobby
25 May 01:06:12 - {"result":"DOTA_JOIN_RESULT_ALREADY_IN_GAME"}
25 May 01:06:12 - null
`


package.json

> {
  "name": "dota2",
  "version": "5.0.1",
  "dependencies": {
    "long": "^3.2.0",
    "deferred": "^0.7.7",
    "merge": "^1.2.0",
    "protobufjs": "^6.7.3",
    "steam": "^1.4.0",
    "dota2": "^5.1.0"
  },
  "devDependencies": {
    "mocha": "^3.4.2",
    "should": "^11.2.1"
  },
  "scripts": {
    "update": "bash update_proto.sh",
    "test": "mocha"
  },
  "readmeFilename": "README.md",
  "description": "A node-steam plugin for Dota 2.",
  "main": "index.js",
  "repository": {
    "type": "git",
    "url": "git://github.com/Arcana/node-dota2.git"
  },
  "keywords": [
    "steam",
    "valve",
    "dota"
  ],
  "license": "MIT"
}

> npm -v
4.2.0
node -v
v7.8.0

**Comment by Crazy-Duck** [comment]
Did you try adding abandonGame yet?

**Comment by Gaever** [comment]
Tried abandonCurrentGame both before and after leavePracticeLobby.
> Dota2.abandonCurrentGame(function(err, data){
	util.log('abandonCurrentGame');
	util.log(JSON.stringify(data));
	util.log(err);
	Dota2.leavePracticeLobby(function(err, data){
		util.log('leavePracticeLobby');
		util.log(JSON.stringify(data));
		util.log(err);
		Dota2.createPracticeLobby(properties, function(err, data){
			util.log('createPracticeLobby');
			util.log(JSON.stringify(data));
			util.log(err);
		});
	});
})

Result: 

> 28 May 22:51:06 - Logged on.
28 May 22:51:06 - Launching Dota 2
28 May 22:51:07 - Received servers.
28 May 22:51:07 - Sending ClientHello
28 May 22:51:08 - Dota2 fromGC: k_EMsgGCClientWelcome
28 May 22:51:08 - Received client welcome.
Node-dota2 ready.
28 May 22:51:08 - Sending match CMsgAbandonCurrentGame request
28 May 22:51:08 - Dota2 fromGC: k_ESOMsg_CacheSubscribed
28 May 22:51:08 - Cache(s) subscribed, type(s): 7
28 May 22:51:08 - Unhandled cache ID: 7
28 May 22:51:18 - Sending match CMsgPracticeLobbyLeave request
28 May 22:51:18 - Received create/flip/shuffle/kick/launch/leave response {"result":"DOTA_JOIN_RESULT_INVALID_LOBBY"}
28 May 22:51:18 - leavePracticeLobby
28 May 22:51:18 - {"result":"DOTA_JOIN_RESULT_INVALID_LOBBY"}
28 May 22:51:18 - 2

**Comment by ACmagic** [comment]
Same here. Tried abandonCurrentGame and leavePracticeLobby before creating practice lobby, not working.

**Comment by ekifox** [comment]
Same: Tried abandonCurrentGame and leavePracticeLobby before creating practice lobby, not working.
