### ISSUE TITLE
Some errors in node-dota2

### ISSUE THREAD

**Issue by csplkiller** [Arcana/node-dota2#479]
I started studying the library two days ago, and I faced a lot of difficulties, due to mistakes in the examples and other things ..
I think we need to correct the examples, at least.

node-dota2/examples/example2.js

Line 32: 
```
Dota2.sendMessage(chatChannel, "Hello, guys! I'm Dota 2 Bot.");
```
Swap message and channel name
```
Dota2.sendMessage("Hello, guys! I'm Dota 2 Bot.", chatChannel);
```
And it would be nice to give an example of sending a message to the lobby and joining the chat lobby.
```
Dota2.joinChat('Lobby_' + lobby.lobby_id, 3);
Dota2.sendMessage("Hello, guys! I'm Dota 2 Bot.", 'Lobby_' + lobby.lobby_id, 3);
```

Line 129: Old method

```
Dota2.createPracticeLobby(lobbyPassword, properties, function(err, data){
```
Replace to
```
Dota2.createPracticeLobby(properties, function(err, data){
```

abandonCurrentGame function - Do not return to callback!

**Comment by Crazy-Duck** [comment]
Indeed, it seems I forgot to update the examples when I changed everything to v5. Good catch! I'll update them

**Comment by Crazy-Duck** [comment]
#481
