### ISSUE TITLE
Not logging with SteamGuard on

### ISSUE THREAD

**Issue by trainingday01** [Arcana/node-dota2#483]
Sentry file and config.steam_guard_code are empty at start, on first attempt of login I get the steamGuard code on the phone app, put it into config.json, restart the app and it doesn't log in, I receive another steamguard code instead. 
And it always keeps saying this:

Connection closed by server: Error: Disconnected

Help appreciated

P.S.: I have tried an account without steamguard and it works perfectly though

**Comment by Crazy-Duck** [comment]
Can you try changing `config.steam_guard_code` to `config.two_factor_code`?

**Comment by Crazy-Duck** [comment]
Btw is your file named config.js or config.json? Because in the exaples we're looking for a js file

**Comment by trainingday01** [comment]
I followed the instructions and the config is config.js

Tried this:
`if (global.config.steam_guard_code) logOnDetails.two_factor_code = global.config.steam_guard_code;`

And I get this output:
```
19 Apr 17:23:25 - Logged on.
19 Apr 17:23:25 - Launching Dota 2
19 Apr 17:23:25 - Received servers.
19 Apr 17:23:25 - sentryfile saved
19 Apr 17:23:25 - Logged off from Steam.
19 Apr 17:23:25 - Connection closed by server: Error: Disconnected
19 Apr 17:23:26 - Sending ClientHello
/Users/xxx/node-dota2/node_modules/steam/lib/steam_client.js:114
  this._connection.send(Buffer.concat([header.toBuffer(), body]));
                  ^

TypeError: Cannot read property 'send' of undefined
    at SteamClient._send (/Users/xxx/node-dota2/node_modules/steam/lib/steam_client.js:114:19)
    at SteamClient.send (/Users/xxx/node-dota2/node_modules/steam/lib/steam_client.js:123:8)
    at SteamGameCoordinator._send (/Users/xxx/node-dota2/node_modules/steam/lib/handlers/game_coordinator/index.js:49:16)
    at SteamGameCoordinator.send (/Users/xxx/node-dota2/node_modules/steam/lib/handlers/game_coordinator/index.js:67:8)
    at Timeout.Dota2Client._sendClientHello [as _onTimeout] (/Users/xxx/node-dota2/index.js:181:22)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
```
I remove the steamGuard code from the config.js and it ignores the sentry file completely by just outputting
`19 Apr 17:22:12 - Connection closed by server: Error: Disconnected`
and sending again the steamGuard to the mobile phone app.
Is this a node-steam issue?
Thanks.

**Comment by trainingday01** [comment]
Tried this too:
`logOnDetails.auth_code = global.config.two_factor_code;`

Keeps saying:
`20 Apr 10:37:18 - Connection closed by server: Error: Disconnected`

**Comment by trainingday01** [comment]
Yes, it's config.js
Seems to work with:
`if (global.config.steam_guard_code) logOnDetails.two_factor_code = global.config.steam_guard_code;`

But, after removing the steam_guard_code from config and try to log in using sentry file, it won't.
Throws the error message
`20 Apr 10:51:23 - Connection closed by server: Error: Disconnected`
And sends the code to the mobile phone app.

**Comment by trainingday01** [comment]
Ok, you can close this, just found this on node-steam:
https://github.com/seishun/node-steam/issues/370#issuecomment-228603748

**Comment by Crazy-Duck** [comment]
Yeah, was gonna reply that, sentry file does not work with 2FA, you need to enter a new code upon each login :) and you should change steam_guard_code to two_factor_code both in config.js and in your code evidently ;) Check (example2)[https://github.com/Arcana/node-dota2/blob/staging/examples/example2.js#L234] for how to do it
