### ISSUE TITLE
Support for custom handlers?

### ISSUE THREAD

**Issue by luxalpa** [Arcana/node-dota2#489]
I'm using some functionality that isn't supported by node-dota2 and implemented my own versions of those handlers.

Currently I'm doing it like this:

```
Dota2.Dota2Client.prototype._handlers[Dota2.schema.lookupEnum("EGCBaseClientMsg").values.k_EMsgGCPingRequest] = function onPingRequest() {
     this.sendToGC(Dota2.schema.lookupEnum("EGCBaseClientMsg").values.k_EMsgGCPingResponse,
     Dota2.schema.lookupType("CMsgGCClientPing").encode({}).finish());
};
```

Quite obviously this method has a serious problem: It's relying on node-dota2 internals that could change without notice in any update.

Would be cool if there was some official support for setting custom handler functions and sending custom messages to the GC.

**Comment by Crazy-Duck** [comment]
Well, there are 2 obvious solutions here:
* create a pull request/issue with the new functionality you'd like to see implemented
* fork the library
We very much prefer the first solution :)
