### ISSUE TITLE
New debug log mechanism

### ISSUE THREAD

**Issue by Crazy-Duck** [Arcana/node-dota2#490]
I've created a new branch where I implemented a proper way of writing logs, since util.log is deprecated. I've kept the default output identical to util.log, so outwardly there is no difference for our users, other than a new Logger property that's gonna be exposed. 

The question is now, can I push this in a minor release or should this be put in a major one? Myself I'm inclined to put it in a minor since I can't really see how I could've broken something..

**Comment by Crazy-Duck** [comment]
Pinging the usuals @jimmydorry @howardchung

**Comment by jimmydorry** [comment]
Wait what? https://nodejs.org/api/util.html#util_util_log_string

Woah, they are deprecating it. I would think minor is fine. I would imagine users probably use util.log themselves, and what ever work-around they make, won't be held back by us.

**Comment by howardchung** [comment]
Minor is fine, there's no API change for the user.
