### ISSUE TITLE
Revisit using createPracticeLobby to join a dedicated server

### ISSUE THREAD

**Issue by CasperAlant** [Arcana/node-dota2#491]
It has been two years to the day since @paralin explained in #64 that this was not possible at the time.

In my mind it should work similarly to how you can create a lobby in game and set the server to "Local Host", except in this case it needs to be a dedicated server.

Have we made any progress to make this possible?

Can anyone elaborate on what the process may look like?

**Comment by rossengeorgiev** [comment]
It might be even more difficult now given the relay system.

**Comment by paralin** [comment]
Go reverse engineer all of the Source 2 networking protocol and then come back to me.

**Comment by CasperAlant** [comment]
Closing the issue as the answer seemingly no.
