### ISSUE TITLE
Tip after match

### ISSUE THREAD

**Issue by wwickedseek** [Arcana/node-dota2#497]
Yo! Thanks for such bot 

I'm asking, is there any way to tip player after match?

**Comment by rossengeorgiev** [comment]
Yes, you just send the message for that.

**Comment by wwickedseek** [comment]
Thanks for help, but I can't understand your message :c
Can you explain it please?

As tip after match I mean button that gives +50 compendium points, located near commend button.

**Comment by Crazy-Duck** [comment]
well, there's a protobuf message that needs to be sent to the GC, however, that particular message hasn't been implemented in the lib yet. I'll see if I have time to look into it.
