### ISSUE TITLE
[Help] Distribution of players by teams (daer, rediant) after their joining the lobby?

### ISSUE THREAD

**Issue by fenixphp** [Arcana/node-dota2#500]
The task is simple enough: to distribute the invited players in the lobby to their places in the teams. If it is possible? Thanks in advance.

**Comment by angel200sdnot** [comment]
No, you can only make the bot kick players from either team as soon as they sit on that slot if they don't belong to that team

**Comment by fenixphp** [comment]
Understood thanks.
