### ISSUE TITLE
node js dota 2 bot connecting player failure returning matchmaking

### ISSUE THREAD

**Issue by v3xperts** [Arcana/node-dota2#505]
i am try to create a practice lobby for playing game using dota 2 steam api in node js 
thanks in advance

**Comment by Crazy-Duck** [comment]
You're going to have to be a little bit more specific on what exactly the problem is, because with the info you're giving me here I have very little to go by to understand the issue...

**Comment by angel200sdnot** [comment]
I think he is referring to this https://github.com/Arcana/node-dota2/issues/472#issuecomment-294293402

**Comment by Crazy-Duck** [comment]
Closed because inactive
