### ISSUE TITLE
createPracticeLobbyAsync stops working for unknown reason

### ISSUE THREAD

**Issue by Idan-** [Arcana/node-dota2#506]
My application works perfectly for 10min-5hours, after that every call to `createPracticeLobbyAsync` just returns response 2 (INVALID_LOBBY).
the call is being sent as the following 
```
const gameProfile = {
    game_name: 'Zen DOTA2',
    server_region: dota2lib.ServerRegion[settings.region],
    game_mode: dota2lib.schema.lookupEnum('DOTA_GameMode').values[`DOTA_GAMEMODE_1V1MID`],
    series_type: dota2lib.SeriesType.NONE,
    game_version: settings.region,
    allow_spectating: true,
    pass_key: '<TODO: GENERATE PASSWORD>',
    radiant_series_wins: 0,
    dire_series_wins: 0,
    allow_cheats: false,
    fill_with_bots: false,
    allchat: true,
  }
  const lobbyId = await Manager.createLobby(gameProfile, teams)
```

and the manager function - 
```
async createLobby(gameProfile) {
    try {
      // Leave any old lobby just in case
      await this.leaveLobby()
    } catch (err) {  // eslint-disable-line no-empty
    }

    const lobbyUpdatePromise = eventToPromise(this.dota2, 'practiceLobbyUpdate')

      const { eresult } = await this.dota2.createPracticeLobbyAsync(gameProfile)
      const result = lobbyJoinResultToName[eresult]
      if (result !== 'SUCCESS' && result !== 'ALREADY_IN_GAME') { // HERE MY APPLICATION FAILS
          throw new Error(`Got ${result} while trying to create practice lobby`)
      } else {
        logger.info('Create practice lobby result:', result)
        break
      }

    const lobby = await lobbyUpdatePromise
    const lobbyId = lobby.lobby_id.toString()

    await this.dota2.joinPracticeLobbyTeamAsync(
      0,
      dota2lib.schema.DOTA_GC_TEAM.DOTA_GC_TEAM_PLAYER_POOL)

    this.dota2.joinChat(`Lobby_${lobbyId}`, dota2lib.schema.DOTAChatChannelType_t.DOTAChannelType_Lobby)

    return lobbyId
  }
```

After some time instead of getting SUCESS I get INVALID_LOBBY, if I continue calling that manager it will just not work, if I put it in downtime for about 20 min and try again it will work.
Sometimes when I restart the application it just works.
As for now I can't find a way to reproduce that manually as it just works in any case.
The only way I got to reproduce that error is by calling that endpoint multiple times simultaneously, in that case all the calls (including the first received) got INVALID_LOBBY, after waiting few seconds I did that call again and it did work so it seems as unrelated bug..

**Comment by Crazy-Duck** [comment]
Going by the error codes I'd say you lose your connection with the GC (which happens daily) after which your lobby doesn't get cleaned up properly. It's not always sufficient to just leave the practice lobby, in many cases you also need to do an abandon game after. Could you try that and see if you still get the error?
