### ISSUE TITLE
bot with ID null

### ISSUE THREAD

**Issue by neoxedneox** [Arcana/node-dota2#514]
Hello,

I've used the script for a discord dota 2 bot which uses node-dota2. Thanks to @angel200sdnot for resolving the first issue, now i'm facing another problem with this error :

```
 Error: The bot with ID null doesn't exist.
    at DotaHandler.getLobbyDetails (/home/dotabot/Documents/schedulebot/lib/modules/dotahandler/index.js:143:10)
    at db.getLobbyBotId.then.botID (/home/dotabot/Documents/schedulebot/lib/commands/admin/get-lobby.js:17:41)
```

But when i go to the database and add manually the bot ID it works.

**Comment by angel200sdnot** [comment]
This problem isn't directly related to the node-dota2 module, so you will have to create an issue in the repository you got the script from

**Comment by neoxedneox** [comment]
@angel200sdnot if i was getting answers i wouldn't ask here :(, i've emailed you anyway.
