### ISSUE TITLE
 str.indexOf is not a function

### ISSUE THREAD

**Issue by oleghalin** [Arcana/node-dota2#516]
`Dota2.Dota2Client.prototype.ToSteamID = function(accid) {
    return new Long.fromString(accid).add('76561197960265728');
};`

I have error  str.indexOf is not a function on line with return

**Comment by Crazy-Duck** [comment]
Could you provide a bit more detail? In what context are you getting this error? Which version of node and which versio of the library are you running?

**Comment by oleghalin** [comment]
Last node-dota and node v5.6. Having error wheb execute ToSteamID(lobby[players][0].id.low)

**Comment by angel200sdnot** [comment]
Try this
```Javascript
ToSteamID(lobby[players][0].id + "")
```
or this
```Javascript
ToSteamID(lobby[players][0].id.low + "")
```

**Comment by Crazy-Duck** [comment]
Function doc explicitly states it wants a string yeah
```
/**
 * Converts a 64bit Steam ID to a Dota2 account ID by deleting the 32 most significant bits
 * @alias module:Dota2.Dota2Client.ToAccountID
 * @param {string} steamID - String representation of a 64bit Steam ID
 * @returns {number} Dota2 account ID corresponding with steamID
 */
Dota2.Dota2Client.prototype.ToAccountID = function(steamID) {
    return new Long.fromString(steamID).sub('76561197960265728').toNumber();
};
```

**Comment by angel200sdnot** [comment]
@Crazy-Duck i started having this issue when ToAccountID and ToSteamID stopped using bignumber.js so i had to add a + "" to ensure that they were strings
Perhaps both functions can be changed so they always ensure it gets strings?
```Javascript
Dota2.Dota2Client.prototype.ToAccountID = function(steamID) {
    steamID += ""
    return new Long.fromString(steamID).sub('76561197960265728').toNumber();
}
```
A lot of times people will be using the Long steamID they get from the game coordinator instead of a string

**Comment by Crazy-Duck** [comment]
Yeah good suggestion, I'll add something in

**Comment by oleghalin** [comment]
Yes, it helped. But im getting Long { low: 304962623, high: 17825793, unsigned: false }, before im having correct STEAM ID. What i need to do with it?

**Comment by angel200sdnot** [comment]
If you need the string of the converted steamID just add + ""
```Javascript
ToSteamID(lobby[players][0].id + "") + ""
```

**Comment by oleghalin** [comment]
thanks

**Comment by Crazy-Duck** [comment]
Fixed on the inventory branch, will soon be merged
