### ISSUE TITLE
Fantasy Cards

### ISSUE THREAD

**Issue by Hack3l** [Arcana/node-dota2#520]
I'm trying to fetch my fantasy player cards with the function provided in the example but its just returning an empty array.
I also tried to just fetch my Inventory but its returning an empty array too. 
Does anyone have experience with fantasy cards?

**Comment by Crazy-Duck** [comment]
Seems like Valve changed the way they're storing player cards on their end. I'm looking into what changed

**Comment by Crazy-Duck** [comment]
Should be fixed on the inventory branch

**Comment by Hack3l** [comment]
Thanks

**Comment by Hack3l** [comment]
This doesnt really belong here but i dont know where else to ask. I'm having trouble interpreting the card bonuses as they are a UInt8Array and the same indices are used for different stats and i cannt make sense of the last 2 values in the array so you know how these work?
