### ISSUE TITLE
steam_id is noted as type long

### ISSUE THREAD

**Issue by dca123** [Arcana/node-dota2#522]
steam_id is noted as type long in the documentation, but when using it I have to pass it as a string. I'm kinda new to this and was wondering why it noted as of type long but I have to convert it to a string for use within functions.

**Comment by dca123** [comment]
Found it , 

> You should treat it as a string.
> 
> http://www.javascripter.net/faq/converti.htm
> 
> http://stackoverflow.com/questions/24037751/how-to-do-64bit-integer-arithmetic-in-node-js

Delete this post if it provides no value

**Comment by Crazy-Duck** [comment]
The inventory branch contains a fix for this. Both functions now take both Long and String values
