### ISSUE TITLE
Join the reggional chat

### ISSUE THREAD

**Issue by ClockRide** [Arcana/node-dota2#525]
I tried the following:
`Dota2.joinChat('Yoshkar Ola, Mariy-El', 0); // because of DOTAChannelType_Regional = 0`
`Dota2.joinChat('Yoshkar Ola, Mariy-El', '0'); // because of DOTAChannelType_Regional = 0`

However, instead of joining the regional channel, the bot creates a custom channel in which there are 0 people. What should i do to join the regional chat?

**Comment by ktestpi** [comment]
i have same problem. Bot creates a void channel where there aren't people instead of join to the regional channel.
