### ISSUE TITLE
Lobby Creation Questions

### ISSUE THREAD

**Issue by markrmessmore** [Arcana/node-dota2#532]
Hello all, a few questions regarding lobby creation. I'll try to give pertinent details along the way:

***How does one set first pick to Dire or Radiant?***
* I've seen things about setting 1 or 2, good guys/bad guys...I just need to know the proper syntax.

***How does one set the leagueid?***
* I have **leagueid** defined in my settings yet it never seems to carry into the lobby creation. I'm currently using the four-digit number (and yes the bot is set as an admin through Valve's site).

***What is the best way to receive the dota lobby id after it's been created?***
* I SEE it in the console but I'm struggling to determine how to grab and thereby be able to use the information. 

***General question about how lobby creation will work***
Where I am vs. what I'm figuring out:
* The bot will create the lobby and then place itself in the first spot on the Radiant side.
* I'm currently having it leave the lobby at a timeout - not sure if this is best practice.
* Will the settings established by the bot (like leagueid when it is functioning) stay once the bot has left? Or do I need to actually begin the match before the bot leaves?

Thanks for the assistance.

**Comment by Crazy-Duck** [comment]
**_How does one set first pick to Dire or Radiant_**
Check the docs/README for [`configPracticeLobby`](https://github.com/Arcana/node-dota2#module_Dota2.Dota2Client+Lobby.Options). There is a setting for it
**_How does one set the leagueid_**
Same as above
**_What is the best way to receive the dota lobby id after it's been created?_**
Lobby ID should be obtainable through the LobbyUpdate event that gets fired each time something changes in the lobby you're in iirc.
**_General questions_**
- usually you kick your bot from the radiant team so it sits in the unassigned/spectator slot
- you want your bot to start the lobby and then leave after the first update. That way you should have match ID as well I think
- the setting will stay if you leave before lobby has started, however, a new host will be assigned and he will be able to modify the settings at will. I'm not sure what will happen with the ticket, it might be removed if you leave the game before it starts. If you leave after start, ticket stays

**Comment by markrmessmore** [comment]
Ok so after revisiting the docs and doing some testing I figured out what I was doing wrong. For posterity here are my findings:

***How does one set first pick to Dire or Radiant?***
The [docs ](https://github.com/Arcana/node-dota2#module_Dota2.Dota2Client+Lobby.Options)only detail that the default is random. From [here ](https://github.com/yaakov-h/SKSteamKit/blob/master/Resources/Protobufs/dota%20test/dota_gcmessages.proto)I identified that the **cm_pick** option should be: **1** for **Radiant**, **2** for **Dire**.

Make sure these variables are set to NUMERICAL values and not STRINGS. That was one of my issues.

**How does one set the leagueID**?
See my statement above about numerical values vs. strings. 

**What is the best way to receive the dota lobby id after it's been created**
I'm still wrestling with this one. I do see that the lobby id is printed in my console but I cannot determine how to capture it. The ***practiceLobbyUpdate*** is the event I believe you are speaking of which I am capturing. Here is my output:

```
CSODOTALobby {
  members:
   [ CDOTALobbyMember {
       disabled_hero_id: [],
       enabled_hero_id: [],
       xp_bonuses: [],
       custom_game_product_ids: [],
       id: [Object],
       team: 4,
       name: 'BunnyBot-Test',
       slot: 0,
       leaver_status: 1,
       channel: 6,
       partner_account_type: 0,
       cameraman: false } ],
  left_members: [],
  pending_invites: [],
  team_details: [],
  timed_reward_details: [],
  broadcast_channel_info: [],
  extra_messages: [],
  active_ingame_events: [],
  previous_series_matches: [],
  lobby_id: Long { low: 441639148, high: 5878230, unsigned: true },
  game_mode: 2,
  state: 0,
  leader_id: Long { low: 414234175, high: 17825793, unsigned: true },
  lobby_type: 1,
  allow_cheats: false,
  fill_with_bots: false,
  intro_mode: false,
  game_name: 'WLDL 2017 6 vs. BB',
  server_region: 2,
  cm_pick: 2,
  allow_spectating: true,
  bot_difficulty_radiant: 0,
  game_version: 1,
  pass_key: '490843',
  leagueid: 5300,
  penalty_level_radiant: 0,
  penalty_level_dire: 0,
  series_type: 0,
  radiant_series_wins: 0,
  dire_series_wins: 0,
  allchat: true,
  dota_tv_delay: 1,
  lan: false,
  lan_host_ping_to_server_region: 0,
  visibility: 0,
  league_series_id: 0,
  league_game_id: 0,
  previous_match_override: Long { low: 0, high: 0, unsigned: true },
  pause_setting: 0,
  bot_difficulty_dire: 0,
  bot_radiant: Long { low: 0, high: 0, unsigned: true },
  bot_dire: Long { low: 0, high: 0, unsigned: true } }
```
I can't seem to identify any way to nab the id.

***General Questions***
* The league id/first pick/etc settings created with the bot ***DO*** in fact stay even after the bot has left.

**Comment by angel200sdnot** [comment]
Take the lobby_id and convert it from Long to String

for example you can do this
```Javascript
var lobby_id
Dota2.on("practiceLobbyUpdate", function (lobby, lobbyEventPoints, leagueAdminList) {
    lobby_id = lobby.lobby_id + ""
}
```

**Comment by markrmessmore** [comment]
That did the trick! Thanks for your assistance!

**Comment by Crazy-Duck** [comment]
@markrmessmore for your comment about using numbers:
- the doc for cm_pick explicitly states that the datatype is a DOTA_CM_PICK. This is an enum defined in the protobuf schema. You can access its values through `Dota2.schema.lookupEnum("DOTA_CM_PICK").values.DOTA_CM_RANDOM`. You can see in handlers/lobbies.js this is for example how we set the default value. The enum has an int representation, but I suggest you use the enum for legibility. It's why they're there
```
enum DOTA_CM_PICK {
	DOTA_CM_RANDOM = 0;
	DOTA_CM_GOOD_GUYS = 1;
	DOTA_CM_BAD_GUYS = 2;
}
```
- the doc for league_id explicitly states to use a number ... 

__Pertaining lobby_id:__ those are 64bit numbers. Javascript cannot handle numbers that big, so we're using Long.js to represent them. Default string representation of is showing the low and high bits in a json struct like you see in the lobby update snapshot. you can print them in human readable format like angel specified, or by using their toString() function

__General questions:__ like I said, the settings will stay, but the newly appointed host can change them at will. Be very careful that this is what you want! The only way to be 100%sure the setting won't be changed between the bot leaving the lobby and the game starting is to have the bot be host, modify the settings and *starting the game* before leaving.
