### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Vuzimir** [Arcana/node-dota2#539]
How can i pull match data from played match thru this dota2 node ?

**Comment by Crazy-Duck** [comment]
What data are you looking to get? Can you be a little more specific?

**Comment by Vuzimir** [comment]
Full match info playerslot, item id, everything related to match data and statistic

**Comment by Crazy-Duck** [comment]
Do you want this data for a game that is currently being played, or rather after the game has ended?

**Comment by Vuzimir** [comment]
Both will be excellent

**Comment by Crazy-Duck** [comment]
If you want data on a game that's currently being played, the best way is to have a bot in the spectator slot. For information on a game that's already finished, I'd suggest you check out the opendota api, since they already parse most games.

**Comment by Crazy-Duck** [comment]
@Vuzimir was my response sufficient? If so, can you close the issue?
