### ISSUE TITLE
[question] I can use node-dota2 to bots?

### ISSUE THREAD

**Issue by marioidival** [Arcana/node-dota2#541]
I want create a lobby and invite players to lobby

**Comment by rossengeorgiev** [comment]
yes

**Comment by marioidival** [comment]
https://github.com/Arcana/node-dota2#module_Dota2.Dota2Client+createTournamentLobby ??

**Comment by Crazy-Duck** [comment]
You want [this](https://github.com/Arcana/node-dota2#dota2clientcreatepracticelobbyoptions-callback) function

**Comment by marioidival** [comment]
Hm, so I cannot create lobbies to tournament, only to practice?
