### ISSUE TITLE
[question] Need some suggestions to get started

### ISSUE THREAD

**Issue by jasonsong93** [Arcana/node-dota2#542]
Hi there! 
Firstly, I'm relatively new to programming in general (I just changed from Mechanical Engineering to Software) but I love Dota and I've been learning a bit of the MEAN stack (haven't done Angular yet)
My experience is simply building some basic RESTful apps.
I came across this and understand enough to know how to start it but not actually "use" it.

**What I've done so far:**
- Read through all closed and open issues
- Done installation and setup successfully (I think - my CMD is outputting with the example.js files)

**Some problems:**
- My main steam account cannot login, even after following the steamguard instructions and replacing it in the config.js file
- My other steam accounts (I rarely use them to play Dota) CAN login perfectly fine with the example.js files. 
NOTE: My other steam accounts also have steamguard, so it must be account related? I'm not sure.

**What I want to use this for**
- I want to create something along the lines of Faceit in regards to easily place people into lobbies for tournaments that I host
- Something along these lines: https://github.com/MeLlamoPablo/schedulebot It does not seem to be working/managed at the moment (without the Discord aspect)

I am keen to learn and be resourceful, but I'm not quite sure where to go from here and am quite lost. Any suggestions would be appreciated (including whether this may or may not be too out of my reach for now) - thanks in advance.

**Comment by angel200sdnot** [comment]
I would say start with something simple, a lobby bot that hosts a match and starts when all slots are full is a good way to start.

**Comment by jasong93** [comment]
I'm having a bit of trouble with the example files. They work for me but when I noticed some of the methods (such as hosting) is different?

**Comment by Crazy-Duck** [comment]
Take a look at the node-dota2-bot repository to see another example of how to use the library as a proper dependency, or simply use that one if you want to start of with something simple. If you're having specific issues, feel free to past some code samples and there'll be plenty people on here happy to help you out

As for the steamguard issue, make sure your account is actually using steamguard and not steam 2FA, those are 2 different ways of authenticating (and the way you need to put them in the config file is different)!
