### ISSUE TITLE
Clear ProfileCard cache

### ISSUE THREAD

**Issue by VitorCaleffi** [Arcana/node-dota2#550]
I noticed that when using requestProfileCard a cache is created (is it true?) and the information of that player will be "outdated" only for that specific steam user that requested it on the first time, while when requesting with another steam account (or a service like dotabuff) the information will be more precise. There is a way to clear this kind of cache?

**Comment by Crazy-Duck** [comment]
The cache is entirely serverside, not in node-dota2.. So there isn't a whole lot we can do

**Comment by VitorCaleffi** [comment]
Oh Ok, I thought that maybe there was something that i could do on the steam module, thank you anyway,
