### ISSUE TITLE
When will the new version be published?

### ISSUE THREAD

**Issue by angel200sdnot** [Arcana/node-dota2#552]
I have a big event on monday and i would like to be sure the bot won't be crashing due to this 2 bugs that have been fixed on the staging branch
https://github.com/Arcana/node-dota2/pull/547
https://github.com/Arcana/node-dota2/pull/536
Installing using npm gives me version 5.1.0

**Comment by Crazy-Duck** [comment]
I'm waiting for the new patch to get stable and the new ranked matchmaking to come out, since there'll probably some proto changes at that moment. If you want, you can always point your package.json to the the staging branch if you want the bleeding edge stuff

**Comment by angel200sdnot** [comment]
Thanks, in that case i will use my forked version of node-dota2 on the meantime
