### ISSUE TITLE
Any updates to support Seasonal Ranks?

### ISSUE THREAD

**Issue by XenBG** [Arcana/node-dota2#554]
The question itself.

**Comment by Crazy-Duck** [comment]
Should already be supported I think, aren't they on the profile card?

**Comment by rossengeorgiev** [comment]
@Crazy-Duck have you updated the protobufs? 😃

**Comment by XenBG** [comment]
@Crazy-Duck, no. The profile card output is:

> {"account_id":110194593,"background_def_index":0,"slots":[{"slot_id":0,"trophy":null,"stat":{"stat_id":1,"stat_score":6426},"item":null,"hero":null,"emoticon":null},{"slot_id":1,"trophy":null,"stat":{"stat_id":4,"stat_score":831},"item":null,"hero":null,"emoticon":null},{"slot_id":2,"trophy":null,"stat":null,"item":{"serialized_item":{"buffer":{"type":"Buffer","data":[8,161,223,197,52,16,0,26,9,8,0,26,5,8,1,16,154,50,26,9,8,1,26,5,8,4,16,191,6,26,57,8,2,34,53,10,45,8,228,165,220,223,41,16,161,223,197,52,24,178,79,32,255,71,56,4,72,8,98,9,8,171,3,26,4,56,238,85,89,98,9,8,213,1,26,4,1,0,0,0,120,0,16,228,165,220,223,41,26,57,8,3,34,53,10,45,8,137,229,232,223,41,16,161,223,197,52,24,140,79,32,238,71,56,4,72,8,98,9,8,171,3,26,4,56,238,85,89,98,9,8,213,1,26,4,1,0,0,0,120,0,16,137,229,232,223,41,26,8,8,4,18,4,8,64,16,3,32,145,86,64,76]},"offset":37,"markedOffset":-1,"limit":82,"littleEndian":true,"noAssert":false},"item_id":{"low":-1678306588,"high":2,"unsigned":true}},"hero":null,"emoticon":null},{"slot_id":3,"trophy":null,"stat":null,"item":{"serialized_item":{"buffer":{"type":"Buffer","data":[8,161,223,197,52,16,0,26,9,8,0,26,5,8,1,16,154,50,26,9,8,1,26,5,8,4,16,191,6,26,57,8,2,34,53,10,45,8,228,165,220,223,41,16,161,223,197,52,24,178,79,32,255,71,56,4,72,8,98,9,8,171,3,26,4,56,238,85,89,98,9,8,213,1,26,4,1,0,0,0,120,0,16,228,165,220,223,41,26,57,8,3,34,53,10,45,8,137,229,232,223,41,16,161,223,197,52,24,140,79,32,238,71,56,4,72,8,98,9,8,171,3,26,4,56,238,85,89,98,9,8,213,1,26,4,1,0,0,0,120,0,16,137,229,232,223,41,26,8,8,4,18,4,8,64,16,3,32,145,86,64,76]},"offset":96,"markedOffset":-1,"limit":141,"littleEndian":true,"noAssert":false},"item_id":{"low":-1678101879,"high":2,"unsigned":true}},"hero":null,"emoticon":null},{"slot_id":4,"trophy":{"trophy_id":64,"trophy_score":3},"stat":null,"item":null,"hero":null,"emoticon":null}],"badge_points":11025,"event_points":null,"event_id":null}

**Comment by howardchung** [comment]
5.0.1 and 5.1.0 do not have the field.  You can use Arcana/node-dota2#staging to get the latest from GitHub which does have it

**Comment by XenBG** [comment]
Look at that image - https://i.imgur.com/suyPOUH.png. I'm using an old NetHook2 but don't know how to get that info with the community.js handler.

**Comment by angel200sdnot** [comment]
https://github.com/Arcana/node-dota2/blob/8083b51affc60e5e7f0490df712907313503a64f/proto/dota_gcmessages_common.proto#L424

You need to use the staging branch

**Comment by XenBG** [comment]
Thanks! I've added myself:

> optional uint32 leaderboard_position = 9;

Just to get the player's position in World Leaderboards.

**Comment by Crazy-Duck** [comment]
You can all stop panicking, v6.0.0 is now live on npm 👍
