### ISSUE TITLE
Bot miss its match result during disconnection

### ISSUE THREAD

**Issue by ACmagic** [Arcana/node-dota2#562]
sometimes the disconnected bot would happen to miss its match result. How can we make sure bot always receive result? will the practiceLobbyUpdate be fired after match ends?

**Comment by angel200sdnot** [comment]
If the bot disconnects from the match then it will stop receiving practiveLobbyUpdate, if it misses the match result then there is no way of getting it unless the match has a league ticket. If it has a ticket you can use the dota 2 API to get the result
