### ISSUE TITLE
Spin up bot game on local machine

### ISSUE THREAD

**Issue by null77** [Arcana/node-dota2#574]
Was wondering if it's possible to add a feature that would allow node-dota2 to configure a lobby to start a game configured to Server Location -> Local Host. I was looking at the code but couldn't figure out how to hack this in. I can start a dedicated server locally, was hoping to try to make the GC find my local server for running some bot matches for machine learning purposes. Any advice?

**Comment by Crazy-Duck** [comment]
Can you manually launch games this way? If so you can try and nethook the commands that are sent out while you're setting up

**Comment by jimmydorry** [comment]
I'm not sure if nethook2 even works right now. I think there have been a whole heap of breaking protobuf updates since the last update.

**Comment by Crazy-Duck** [comment]
oh rip,  haven't used it in a few months :(

**Comment by jimmydorry** [comment]
Just grabbed the most recent version myself, and it still seems to work. Just make sure you aren't using the Steam Client Beta (or so I've heard).
