### ISSUE TITLE
Cannot recieve profile card

### ISSUE THREAD

**Issue by FrostBy** [Arcana/node-dota2#575]
```
6 February 13:54:01 - Dota2 fromGC: k_EMsgGCClientWelcome
6 February 13:54:01 - Received client welcome.
Bot_request queue is active
botReady
6 February 13:54:01 - Sending profile card request
{ msg: 24,
  headerLength: 0,
  proto: 
   { job_id_source: '18446744073709551615',
     job_id_target: '18446744073709551615',
     eresult: 2,
     gc_msg_src: 'GCProtoBufMsgSrc_Unspecified' } } <Buffer 12 15 08 07 12 11 08 00 10 01 18 01 20 00 28 00 35 00 00 00 00 48 00 19 bc f4 56 11 71 75 5a 05 22 0c 08 01 10 cf 8d a2 e3 91 80 80 88 01 28 01 30 00 ... > null
6 February 13:54:01 - Dota2 fromGC: k_ESOMsg_CacheSubscribed
6 February 13:54:01 - Cache(s) subscribed, type(s): 7
6 February 13:54:01 - Unhandled cache ID: 7
```
There is console.log of this._gc.on("message") params above

When I get this messages my bot freezes

Where should I debug to find a reason of the behavior?

**Comment by Crazy-Duck** [comment]
What version of node-dota2 are you using? And for which account are you making the request? I've just done a test myself and everything seems to work fine...

**Comment by FrostBy** [comment]
The last version.
acc_id = 110968934
It's a phantom bug, sometimes I get it, sometimes nope. But it's more often with my account bellow

**Comment by FrostBy** [comment]
@Crazy-Duck Hi, any news?

**Comment by Crazy-Duck** [comment]
Can you put the bot in debugMore mode and check what exactly happens when you get the bug? Because as it stands I can not reproduce it.
