### ISSUE TITLE
InviteToParty questions

### ISSUE THREAD

**Issue by sidyes** [Arcana/node-dota2#577]
Hey,

I have some issues regarding the "inviteToParty" interface.
I want to create a party and invite multiple users.
My call looks like that:
`
function createParty(idx, player, cb){
    const DotaBot = steamObj[idx].Dota2;
    return DotaBot.inviteToParty(Number(player), (err, partInvite) => {
       cb(err, partInvite);
    });
}
`

The cb will make an HTTP response on my express server.
What is the best way to iterate over an array of players and to invite them to the party?
I want to wait until all players are invited and after that, send a response back to the client.
Sorry if that is too easy but I am kind of a beginner regarding nodejs.

Hope you can help me out there.

**Comment by Crazy-Duck** [comment]
I'd use promises if I were you. The piece of code hereunder (untested!) will return a promise that resolves when all invites have been responded to
```
function createParty(playerIds) {
    return Promise.all(playerIds.map(id => {
        return new Promise((resolve, reject) => {
            DotaBot.inviteToParty(id, (err, response) => {
                if (!err) resolve(response);
                else reject(err);
            });
            setTimeout(() => reject("Timeout"), 10000); // 10s timeout
        });
    }));
}
```

**Comment by sidyes** [comment]
Thank you I will try that one out.
