### ISSUE TITLE
Is it possible to get info which user didn't connect to hero selection screen?

### ISSUE THREAD

**Issue by zm3d3ni** [Arcana/node-dota2#578]
After launchPracticeLobby sometimes happens that some users don't manage to connect to hero selection screen. Is there a way to get info about users which didn't connect?

**Comment by angel200sdnot** [comment]
I would also like to know this, i tried looking into the "practiceLobbyUpdate" event before, while and after the players failed to connect into the game and i couldn't find anything that would tell me which user(s) failed to connect
