### ISSUE TITLE
Is it possible to know whether a match currently being played is ranked or unranked?

### ISSUE THREAD

**Issue by Tsury** [Arcana/node-dota2#580]
The GAME_MODE doesn't state it.

**Comment by danielvieira43** [comment]
checkout this file with game mode strings:
https://github.com/Arcana/node-dota2/blob/80657f9ab7f882ee7329e428903bd905041e8288/proto/dota_shared_enums.proto

**Comment by Crazy-Duck** [comment]
DOTA_GAMEMODE_ALL_DRAFT is ranked all pick, for random draft there is afaik no way to determine if it's ranked or not

**Comment by Crazy-Duck** [comment]
Actually, there might be a way if you know someone in the game via the rich presence thingy, but I don't know what the exact proto message for that one would be. This would need some investigation
