### ISSUE TITLE
Match ID of ended lobby game not found

### ISSUE THREAD

**Issue by danielvieira43** [Arcana/node-dota2#581]
My arcana bot is managing a dota 2 league and all seems to work fine, but after the match ends I cannot find any data about the Match with the given ID on Dota 2. When search for it I get not found. Open Dota and dotabuff also doesn't find the match.

The bot is running a ticket league with Game Mode DOTA_GAMEMODE_ALL_DRAFT (22).

Properties of game:

var properties = {
        "game_name": "Lobby game name",
        "server_region": dota2.ServerRegion.BRAZIL,
        "game_mode": dota2.schema.lookupEnum('DOTA_GameMode').values.DOTA_GAMEMODE_ALL_DRAFT,
        "series_type": dota2.SeriesType.NONE,
        "game_version": 1,
        "allow_cheats": false,
        "fill_with_bots": false,
        "allow_spectating": true,
        "pass_key": "My password",
        "radiant_series_wins": 0,
        "dire_series_wins": 0,
        "allchat": false,
        "leagueid": 9824
    };

Somebody knows why I cannot find the match after it's end?

Thanks!

Cya

**Comment by Crazy-Duck** [comment]
Unless the game is ticketed it's normal that it doesn't show up. Valve doesn't disclose private lobby information, among others to protect skrim data from leaking

**Comment by angel200sdnot** [comment]
When the match is ticketed and it ends too early, it won't be available on the Dota 2 API, try playing a normal match and checking if the match is available online. This applies to most game modes

**Comment by danielvieira43** [comment]
That's it! Thanks a lot!
