### ISSUE TITLE
Lobby visibility option not working. Quick fix

### ISSUE THREAD

**Issue by ghost** [Arcana/node-dota2#601]
Hello, sorry if I've missed this in the issues section but I saw nothing on the matter. I noticed that the option to set the practice lobby's visibility is missing. The variants are:

DOTALobbyVisibility_Public = 0;
DOTALobbyVisibility_Friends = 1;
DOTALobbyVisibility_Unlisted = 2;

This can be easily added. What i've done is:

- in lobbies.js > Dota2._lobbyOptions add // visibility : "number"
- in lobbies.js > Dota2.Dota2Client.prototype.createPracticeLobby add to the defaults object // visibility: 0 (or whatever else default you want)

When creating a lobby options object, just add a "visibility" key with value dota2.schema.lookupEnum('DOTALobbyVisibility').values.SELECT_A_VALUE

**Comment by Crazy-Duck** [comment]
Would you consider creating a pull request with these changes?
