### ISSUE TITLE
Triggering "practiceLobbyUpdate" event after lobby was launched

### ISSUE THREAD

**Issue by angel200sdnot** [Arcana/node-dota2#603]
Is there a way to get the event "practiceLobbyUpdate" after the lobby was launched? I trigger lobby updates using `Dota2.joinPracticeLobbyTeam()` but this doesn't work after the lobby is launched

**Comment by Crazy-Duck** [comment]
Normally you shouldn't even have to join a team to receive lobby updates. If your bot is the one that created and started the lobby you should be getting lobby updates as soon as the game starts
