### ISSUE TITLE
GC reponse Player Info

### ISSUE THREAD

**Issue by dm1989** [Arcana/node-dota2#605]
Can anyone confirm if this has been changed? Player info call (CMsgGCPlayerInfoRequest) to GC does not receive a callback anymore (k_EMsgGCPlayerInfo).

**Comment by pendo324** [comment]
I'm going to take a look using NetHook later today to see what changed. Hopefully I'll be able to make a pull request

**Comment by pendo324** [comment]
Does anyone know what causes (caused?) the Dota client to send a PlayerInfoRequest? I thought it was when you viewed someone's profile, but I guess not: ![image](https://user-images.githubusercontent.com/424987/46101473-0488d200-c19a-11e8-8f08-b619627f9ed0.png)

**Comment by dm1989** [comment]
i believe the natural use for this is for the source tv games list under the watch tab. 

this request gives back a player's info (i've only used it up to 10 players) in terms of what team that player belongs to. 

so kuroky in a game in the watch tab would show Liquid.Kuroky, and this would be accomplished using this call

**Comment by pendo324** [comment]
> 
> 
> i believe the natural use for this is for the source tv games list under the watch tab.
> 
> this request gives back a player's info (i've only used it up to 10 players) in terms of what team that player belongs to.
> 
> so kuroky in a game in the watch tab would show Liquid.Kuroky, and this would be accomplished using this call

Looks like the watch tab now uses a different method to find that information.

First, it makes a [CMsgClientToGCFindTopSourceTVGames request](https://github.com/SteamDatabase/Protobufs/blob/master/dota2/dota_gcmessages_client_watch.proto#L41), which returns a [CMsgGCToClientFindTopSourceTVGamesResponse](https://github.com/SteamDatabase/Protobufs/blob/master/dota2/dota_gcmessages_client_watch.proto#L50).

The client then makes [CMsgClientToGCGetProfileCard requests](https://github.com/SteamDatabase/Protobufs/blob/master/dota2/dota_gcmessages_client.proto#L1097) for every visible player for the game you have selected. 

You can see what I described in the screenshot below.

![image](https://user-images.githubusercontent.com/424987/46119037-2ce2f180-c1d7-11e8-8a6b-91497b8cf926.png)

Interestingly, the [ProfileCard](https://github.com/SteamDatabase/Protobufs/blob/b6ea5931534cb2d9a14c590f5ea5a6427808cb3c/dota2/dota_gcmessages_common.proto#L355) protobuf doesn't seem to contain the "official player name" information. I don't see any other request being made that could be getting that info, so I'm at a dead end here. I'll keep doing research, but I'm not sure what it could be,

**Comment by rossengeorgiev** [comment]
The GC no longer response to that request. It was replaced in the client by https://www.dota2.com/webapi/IDOTA2Fantasy/GetPlayerInfo/v001?account_id=70388657
