### ISSUE TITLE
installation setup

### ISSUE THREAD

**Issue by StakedWins** [Arcana/node-dota2#608]
Hi i can't get this to work. I am using ubunutu 16 now.
when I run "node examples/example.js" or "node examples/example2.js" I get no output at all. If i add the line:  Dota2.launch();
4 September 20:38:29 - Launching Dota 2
4 September 20:38:30 - Sending ClientHello
4 September 20:38:30 - Sending ClientHello
..
until it times out and starts Sending ClientHello again.

I have not changed anything except for this in my example files.

Help is very appreciated

**Comment by StakedWins** [comment]
It seems to work in a way. But nothing is happening when I just run the examples. I assume i am supposed to get a messaged saying im logged in or something.

**Comment by judhizputra** [comment]
Yeah, I face the same problem.

@Crazy-Duck please help...

**Comment by judhizputra** [comment]
@StakedWins i guess i found where the problem is.
The server list on steam module is outdated, you need to manually update the server list.

You can obtain the list from here https://github.com/seishun/node-steam/issues/434#issuecomment-404778885

**Comment by Dmytro4** [comment]
you can also turn off steam guard or click to install dota on account. Worked always for me if servers fix is not enough

**Comment by StakedWins** [comment]
@Dmytro4 what do you mean by "click to install dota on account"?

**Comment by StakedWins** [comment]
It works for me now thanks to your message judhizputra, the server update fixed it. Thank you
