### ISSUE TITLE
Unassigned players

### ISSUE THREAD

**Issue by ghost** [Arcana/node-dota2#611]
Hi! I have a problem. When creating a lobby, bot automatically jump into the player slot and when i invite players to lobby automatically in unassigned players. The bot has been successfully set on unassigned players. But how can i set players into the player slot?

**Comment by angel200sdnot** [comment]
The bot can only kick players from slots or the lobby, it can't place them in the slots

**Comment by iamyuu** [comment]
When i invite players to lobby, players there is not in team slot but in unassigned players

**Comment by iamyuu** [comment]
Thanks for respond. So bot can't set a `DOTA_GC_TEAM` for players?
