### ISSUE TITLE
Local IP address in node-dota2

### ISSUE THREAD

**Issue by truered2** [Arcana/node-dota2#613]
How use local IP address in node-dota2? Steam connected from IP, which i need. But dota2 always connected from eth0 (default interface) . How can i make dota connect from local ip / network interface ?

**Comment by Crazy-Duck** [comment]
Could you be a little more specific in what you're trying to achieve? Are you trying to obtain an IP address of the steam servers?

**Comment by truered2** [comment]
I trying load dota2 and steam from needed network virtual interface. If it a request to website, i do that - request({url: 'needed url', localAddress: 'needed ip'}).
