### ISSUE TITLE
Stats

### ISSUE THREAD

**Issue by StakedWins** [Arcana/node-dota2#615]
Is it possible to retrieve game stats? 
I want to know:
Who are playing in the game (player names, id?) 
Which team won the game

**Comment by StakedWins** [comment]
I don't try to be smart, I just wonder. If this is not possible. What do people use node-dota2 for?

**Comment by andresrivero** [comment]
https://github.com/Arcana/node-dota2

Also: https://github.com/Arcana/node-dota2/blob/staging/README.md

Everything is explained there.
