### ISSUE TITLE
Any interest in using a module for resource handling?

### ISSUE THREAD

**Issue by seishun** [Arcana/node-dota2#617]
A few years ago I moved some code related to resource (protobufs and SteamLanguage) handling from node-steam to a separate project (https://github.com/seishun/node-steam-resources). It was intended to help module authors avoid regularly updating protobufs in their repos, instead bundling them only when publishing the package.

The .proto file lists in it are now outdated and node-steam no longer works with the latest protobufs (i.e. when installing from git). Since the lists include those for Dota 2 and CS:GO, which node-steam doesn't use, I would like to find out if there is any interest in using node-steam-resources before deciding whether to update it or move the relevant parts back into node-steam.

What do you think?

cc @joshuaferrara

**Comment by joshuaferrara** [comment]
The node-steam-resources projects looks very interesting. It seems like a great way of centralizing and providing protobufs that are compatible with node-steam. My [current solution](https://github.com/joshuaferrara/node-csgo/blob/master/protoUpdate.js) of pulling protobufs from repos is a bit hacky, so provided it receives updates to protobufs, I think it would be a great addition to node-csgo.

**Comment by Crazy-Duck** [comment]
I'd be very interested in adding this for node-dota2 as well, right now the protobufs are part of the project itself with some bash scripts that fetch them. Having them in a separate repo would be much better
