### ISSUE TITLE
Build failed, client not working

### ISSUE THREAD

**Issue by Banonevar** [Arcana/node-dota2#623]
As you not saw, build is was failed, and node-dota2 not working
```
internal/process/main_thread_only.js:31
    return _chdir(...args);
           ^

Error: ENOENT: no such file or directory, chdir 'C:\Users\Username\Desktop\node-dota2-staging\node_modules\steam-resources\steam_language'
```
Same error travis https://travis-ci.org/Arcana/node-dota2/jobs/447151987#L466

**Comment by Banonevar** [comment]
@wa1one maybe you know ways for fix that?

**Comment by kasiditp** [comment]
Same here

**Comment by sborod** [comment]
Same problem with fresh cloning of repo and npm install.

I solved the problem by copy-pasting \node_modules\steam\node_modules\steam-resources from old project to new project.

I think problem appears on npm install of steam-resources when npm script call svn checkout like this:
> steam-resources@1.0.0 prepublish ...\node_modules\steam\node_modules\steam-resources
> svn checkout https://github.com/SteamRE/SteamKit/trunk/Resources/Protobufs protobufs && svn checkout https://github.com/SteamRE/SteamKit/trunk/Resources/SteamLanguage steam_language

> svn: E235000: In file 'D:\Development\SVN\Releases\TortoiseSVN-1.11.1\ext\subversion\subversion\libsvn_wc\wc_db.c' line 1648: assertion failed (SVN_IS_VALID_REVNUM(changed_rev))
> npm ERR! code ELIFECYCLE
> npm ERR! errno 3221226505
> npm ERR! steam-resources@1.0.0 prepublish: `svn checkout https://github.com/SteamRE/SteamKit/trunk/Resources/Protobufs protobufs && svn checkout https://github.com/SteamRE/SteamKit/trunk/Resources/SteamLanguage steam_language`
> npm ERR! Exit status 3221226505

**Comment by Banonevar** [comment]
Fixed with latest commits.
