### ISSUE TITLE
Creating custom game lobbies

### ISSUE THREAD

**Issue by Karavil** [Arcana/node-dota2#632]
Does anyone have experience with creating custom game lobbies? I'm currently trying to create a DOTA AUTO CHESS lobby, but non of my attempts are working. Here are my lobby options:

   

        var DOTA_AUTO_CHESS_ID = new Long(1613886175, 0, true);
        Dota2.leavePracticeLobby();
        Dota2.createPracticeLobby({
            "server_region": dota2.ServerRegion.USEAST,
            "custom_game_id": DOTA_AUTO_CHESS_ID,
            "custom_game_mode": "DOTA AUTO CHESS",
            "custom_map_name": "normal",
            "custom_difficulty": 1,
            "pass_key": "password"
          },
          function (err, body) {
            console.log(JSON.stringify(body));
          });
        setTimeout(function () {
        }, 60000);`

I've tried inputting the long as a string, just a number, and played around with not including map names and passwords, or difficulties but I still can't seem to figure out how to create one. It always ends up creating a normal/default lobby.

**Comment by angel200sdnot** [comment]
IIRC you can't host custom games since the library can only communicate to the Game Coordinator, it can't host a server.

You can try custom games that are hosted by valve (dedicated servers) but i don't know if it will work.

**Comment by jimmydorry** [comment]
I don't see you using: `custom_game_crc`. I think this was an important one.

I haven't looked at this since before Valve moved everything to dedis.

**Comment by Karavil** [comment]
I can't seem to find any info on custom_game_crc, hmmm

**Comment by maratkh** [comment]
Any news about custom gsme lobby?

**Comment by devdammit** [comment]
+1

**Comment by havramar** [comment]
+1

**Comment by freedbrt** [comment]
I think, CMsgPracticeLobbyCreate is wrong request, he always creates practice DOTA lobby (just like in the dota2 client)
You should send CMsgCustomGameCreate request.

**Comment by c00kie17** [comment]
#657

**Comment by c00kie17** [comment]
Checkout issue #657 should have the answers to your questions.

**Comment by lemeshovich** [comment]
do we have any solution of that #444 issue?
