### ISSUE TITLE
How to create a Broadcast channel

### ISSUE THREAD

**Issue by herenickname** [Arcana/node-dota2#638]
I see we have a function called `.joinPracticeLobbyBroadcastChannel()`, but how to create a channel?
I doesn't seen function like `.createPracticeLobbyBroadcastChannel` :)

**Comment by ekifox** [comment]
Even I call `joinPracticeLobbyBroadcastChannel` function, I've got this answer:

```
7 Feb 20:50:42 - Received practice lobby join response 1
(node:5057) UnhandledPromiseRejectionWarning: Error: 1 - {"result":"DOTA_JOIN_RESULT_ALREADY_IN_GAME"}
```

PS: Before creating a new lobby I've used `abandonCurrentGame()` and `destroyCurrentLobby()`
