### ISSUE TITLE
Create custom game lobby, and start game

### ISSUE THREAD

**Issue by maratkh** [Arcana/node-dota2#640]
Hi! Someone could create a custom game and start game it. Suppose that the bot came out of the lobby and some of the players can put a button on it.
how to do it?

**Comment by maratkh** [comment]
It's work

**Comment by Rodion15** [comment]
@maratkh Здравствуйте. Как вы решили проблему? Подскажешь?

**Comment by maratkh** [comment]
Не решил до конца, игру запустить можно ботом, но принять игру бот не может, соответственно бота нужно исключать и заставлять кого то другого нажимать старт игры )
