### ISSUE TITLE
match_detail response

### ISSUE THREAD

**Issue by lintangtimur** [Arcana/node-dota2#653]
hello, can someone explain to me what is this mean?
like party_id have low, high, unsigned, damage_type, match_id low, high, unsigned, replay_salt, custom_game_id low, high, unsigned?

**Comment by devilesk** [comment]
party_id, match_id, and custom_game_id are 64 bit unsigned integers. They're too big for javascript's number type, so [long.js](https://github.com/dcodeIO/long.js) is used to represent them.

**Comment by Crazy-Duck** [comment]
See also [this](https://github.com/Arcana/node-dota2#dota2long) section in the README
