### ISSUE TITLE
Questions about the creation, launch of the lobby and the results of the game

### ISSUE THREAD

**Issue by Terran47** [Arcana/node-dota2#658]
Good day to all, tell me there are questions.
**1) Create a lobby and start the game (when players enter).
2) If I do a tournament how a bot can create for each lobby if it can only be in one lobby
3) How to know the result of the lobby played? (Is it possible to leave the lobby after starting the game for the players?)**

**Comment by Terran47** [comment]
I understand you need to create a league in https://www.dota2.com/league/0/list further how to manage the league
  bot

**Comment by ghost** [comment]
Hello, I followed you on Github, I have a request and I hope you can help us.
In our community, we are using a software called Tinserver to play Dota2 on the LAN, but we are missing a GameCoordinator plugin to make it easy for us to build the lobby for the game. I hope you can help us. Thank you very much.

https://cs.rin.ru/forum/viewtopic.php?f=29&t=66246
