### ISSUE TITLE
help how to create multiple lobbies

### ISSUE THREAD

**Issue by Terran47** [Arcana/node-dota2#659]
**The task to hold a tournament.**
It is necessary to create several lobbies, so that I could at the end of the game find out the results by reading all the questions about this. What I understood:
1) You cannot create several lobbies without leaving the previous one; it turns out until the game ends. Other players cannot play, because I should not leave the lobby to find out the result of the game.
2) Found the information that you need to create a league at https://www.dota2.com/league/0/list (created).
Further, how to tie the need to the lobby to the lobby so that after creating the lobby and starting it was possible to leave the lobby and find out the result of the game.
Then I did not find information on how to attach a ticket to the lobby

**Comment by S1ipKn0T** [comment]
Hello, I also ask you to answer this question.
In general, there is a place to get a complete guide to launching this script to resolve most of our questions?
