### ISSUE TITLE
Possible to get logged in users support / core mmr from stats page?

### ISSUE THREAD

**Issue by itsjfx** [Arcana/node-dota2#667]
Hi, not an issue but a query - I was wondering if there was a way of getting the logged in users support and core mmr from their stats page, as well as their medal and number (if immortal).

Right now I'm getting mmr by grabbing recent matches, but the new update has made it impossible to tell what role was played from the recent matches response, figured if this was possible it would be an easy way to check which MMR changed.

Cheers.

**Comment by itsjfx** [comment]
Also a followup, is it possible to edit the 2 stats on your profile? It would be good to do this instead of having to download the old client to get the old solo mmr/party values.

**Comment by jimmydorry** [comment]
Use nethook to figure out what messages are sent, then extend node-dota2 to implement those messages.

**Comment by itsjfx** [comment]
I wasn't able to get NetHook working for Dota 2, but it worked fine for Steam. Instead I just went into the protobufs and figured out I was looking for CSODOTAGameAccountClient which is a cache not handled by node-dota2, so I've made a PR for it. 

https://github.com/Arcana/node-dota2/pull/670

Thanks for your help though, is there any chance you know how to get NetHook working for Dota? I could inject into Steam fine but not Dota.

**Comment by jimmydorry** [comment]
Did you follow the wiki? I believe it included steps for getting the latest NetHook version (as yours might be out of date).

https://github.com/Arcana/node-dota2/wiki

**Comment by itsjfx** [comment]
Ah I didn't check this wiki but I compiled NetHook myself using the instructions from the SteamKit git so it would be up to date. I believe the issue is I didn't think of using the NetHook Analyzer even though it was right in front of me in the repo... lesson learnt for next time. Thanks for your help.

**Comment by jimmydorry** [comment]
No worries. I should have linked to that from the start. :)
