### ISSUE TITLE
Dota2.requestPlayerMatchHistory is not responding

### ISSUE THREAD

**Issue by weiseng101** [Arcana/node-dota2#673]
Stucked at 
6 Oct 18:40:35 - Sending player match history request
6 Oct 18:40:35 - Cache(s) subscribed, type(s): 1,7,2008
6 Oct 18:40:35 - Received inventory snapshot
6 Oct 18:40:35 - Unhandled cache ID: 7
6 Oct 18:40:35 - Unhandled cache ID: 2008

= ((((((

**Comment by crnbarr93** [comment]
Same issue here using the Go version of this repo, maybe game coordinator related rather than an issue with this repo.

**Comment by evangelme** [comment]
i have the same issue it was ok till last week i dont know what happend if u find anything pls tell me tnx

**Comment by anthony9981** [comment]
Any new on this?

**Comment by crnbarr93** [comment]
Hey Anthony,

I'm not currently working with the library.

Generally these issues seem to be caused by Valve making changes to the
protobuf structure. Our work around was to just develop our own smaller
version of this library focused on what exactly we needed at the time.

Good luck,
Connor

**Comment by Camamber** [comment]
Any updates?

**Comment by ns-kminaga** [comment]
A year later and its still not responding. Does anyone have an idea of the underlying cause of this? 

15 Oct 15:28:37 - Sending player match history request
15 Oct 15:28:37 - Dota2 fromGC: k_ESOMsg_CacheSubscribed
15 Oct 15:28:37 - Cache(s) subscribed, type(s): 1,7,2007,2008
15 Oct 15:28:37 - Received inventory snapshot
15 Oct 15:28:37 - Unhandled cache ID: 7
15 Oct 15:28:37 - Unhandled cache ID: 2007
15 Oct 15:28:37 - Unhandled cache ID: 2008
15 Oct 15:28:43 - Dota2 fromGC: k_ESOMsg_CacheSubscribed
