### ISSUE TITLE
Watch/interact with replays

### ISSUE THREAD

**Issue by helloGameGuy** [Arcana/node-dota2#678]
Hello, thank you so much for spending time and putting in effort to develop this amazing project. 

I couldn't find any other place to reach out for questions, so forgive me if this is the wrong place.

Is there any way to start watching and interacting with replays? If not, is that something on the roadmap, or are you aware of any similar projects that support this?

For context I want to "programmatically" launch dota, open a replay file, and capture frames from the renderer.

**Comment by maxpaj** [comment]
@helloGameGuy did you find anything?

**Comment by rossengeorgiev** [comment]
This is not something possible with this project. I suggest looking at way to programmatically launch dota client, load replay, and capture a screenshot. Something like Autohotkey, or python win32api module, etc

**Comment by maxpaj** [comment]
> This is not something possible with this project. I suggest looking at way to programmatically launch dota client, load replay, and capture a screenshot. Something like Autohotkey, or python win32api module, etc


Yes, what I understand of this code after reading some of it/testing the code is that it will talk to Dota 2 servers in order to manipulate network traffic, but not actually launch THE Dota 2 client.
