### ISSUE TITLE
Bot doesn't receive "practiceLobbyUpdate" event after lobby was launched

### ISSUE THREAD

**Issue by mage-ua** [Arcana/node-dota2#688]
Maybe this is Dota2 feature update? :)

**Comment by Angel200O** [comment]
I think its been a couple of months since this issue appeared, you need to check the state property instead of the game_state property in the lobby object

**Comment by mage-ua** [comment]
@angel200sdnot Thx for the answer.
`state` property has poor values for my targets: `UI`, `SERVERSETUP`, `RUN`, `POSTGAME`.
How can I get member **hero_id** in `RUN` **state** in `PRE_GAME` & `GAME_IN_PROGRESS` **game_state**'s?
I know the only one way to get member **hero_id** in real time - `exit` => `launch` Dota2 after launching a lobby.

I have requested some support in Valve help center to resolve this issue.

**Comment by Angel200O** [comment]
In this case you will need to check the live games api to get the heroes while the match is in progress but this will only work if the match has a league ticket

If you get back from valve please let us know
