### ISSUE TITLE
Bot is not installed

### ISSUE THREAD

**Issue by den4ela** [Arcana/node-dota2#689]
npm install dota2
npm ERR! prepareGitDep 1> 
npm ERR! prepareGitDep > steam-resources@1.2.2 prepare /Users/user/.npm/_cacache/tmp/git-clone-0bd4d1b4
npm ERR! prepareGitDep > svn checkout https://github.com/SteamDatabase/Protobufs/trunk protobufs && svn checkout https://github.com/SteamRE/SteamKit/trunk/Resources/ProtobufGen protobuf_gen && svn checkout https://github.com/SteamRE/SteamKit/trunk/Resources/SteamLanguage steam_language
npm ERR! prepareGitDep 
npm ERR! prepareGitDep 
npm ERR! prepareGitDep 2> npm WARN install Usage of the `--dev` option is deprecated. Use `--only=dev` instead.
npm ERR! prepareGitDep svn: error: The subversion command line tools are no longer provided by Xcode.
npm ERR! prepareGitDep npm ERR! code ELIFECYCLE
npm ERR! prepareGitDep npm ERR! errno 72
npm ERR! prepareGitDep npm ERR! steam-resources@1.2.2 prepare: `svn checkout https://github.com/SteamDatabase/Protobufs/trunk protobufs && svn checkout https://github.com/SteamRE/SteamKit/trunk/Resources/ProtobufGen protobuf_gen && svn checkout https://github.com/SteamRE/SteamKit/trunk/Resources/SteamLanguage steam_language`
npm ERR! prepareGitDep npm ERR! Exit status 72
npm ERR! prepareGitDep npm ERR! 
npm ERR! prepareGitDep npm ERR! Failed at the steam-resources@1.2.2 prepare script.
npm ERR! prepareGitDep npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! prepareGitDep 
npm ERR! prepareGitDep npm ERR! A complete log of this run can be found in:
npm ERR! prepareGitDep npm ERR!     /Users/user/.npm/_logs/2020-08-16T09_55_49_055Z-debug.log
npm ERR! prepareGitDep 
npm ERR! premature close

How to fix it?

**Comment by CYSPNET** [comment]
Yes I have the same problem

**Comment by mage-ua** [comment]
Install **svn**
