### ISSUE TITLE
"practiceLobbyUpdate" no longer shows members

### ISSUE THREAD

**Issue by Angel200O** [Arcana/node-dota2#690]
The bot no longer receives the members present in the lobby, has anyone been facing the same issue or solved it?

**Comment by rossengeorgiev** [comment]
A recent protobuf has renamed the members field. See https://github.com/ValvePython/dota2/issues/55

**Comment by Angel200O** [comment]
> A recent protobuf has renamed the members field. See [ValvePython/dota2#55](https://github.com/ValvePython/dota2/issues/55)

This answers the issue, thanks for the quick reply

**Comment by k0mar12** [comment]
@angel200sdnot how did u fixed it ? Thanks

**Comment by k0mar12** [comment]
I found solution, 

`npm i steam-resources`

That was simple 👍
