### ISSUE TITLE
practiceLobbyUpdate data missing

### ISSUE THREAD

**Issue by danielvieira43** [Arcana/node-dota2#691]
I'm missing some data in the lobby object coming from practiceLobbyUpdate event. I used to read lobby.members array to get id, team and slot from players. Anyone with same problem? Is there any update in valve game coordinator?

Thanks,

Daniel

**Comment by herzog0** [comment]
Hi! May I ask what version of node-dota2 are you using?  
I've been experiencing some issues with the version 7.0.3 published in npmjs, but there's no records of changelogs here in the repo. 
As far as I know, the last stable version is 6.1.1.

**Comment by herzog0** [comment]
Hi! I just noticed the same occurring to me.  
Very strange, as everything worked fine until yesterday.

**Comment by Angel200O** [comment]
Protobuf update. See: https://github.com/Arcana/node-dota2/issues/690#issuecomment-687780626

**Comment by herzog0** [comment]
I've tried to update all .proto files by hand, simply copying the new ones and overriding them in the correct folder, but node-dota2 still doesn't recognize the new parameters. Did someone managed to fix this? I'm just printing the contents of CSODotaLobby payload received by the event emitter, so there are no updates needed in my code.

**Comment by herzog0** [comment]
Oops, nevermind. I had to change the protobuf files in node_modules/dota2/proto, not in the steam package.
