### ISSUE TITLE
Bot leaves lobby, leaves unassigned player (black box)

### ISSUE THREAD

**Issue by throneitdev** [Arcana/node-dota2#695]
I have the a bot leave its lobby, then after the lobby starts there is a black box in unassigned players for team selection, attached is a screen shot of whats happening. Anyone run into this before or have an idea of something I should try?

![blackbox](https://user-images.githubusercontent.com/78885039/112585077-c1396980-8dbe-11eb-8b7e-d86e58143065.png)

**Comment by Rodion15** [comment]
@throneitdev Hello, where can I get such a script?
