### ISSUE TITLE
How to get lobby result ( members - team win - and others... ) ? 

### ISSUE THREAD

**Issue by MadPad124** [Arcana/node-dota2#698]
hi.

i start practice lobby and dont get any data about members and result  after game .

### **My Code**
                    var properties = {
                        "game_name": "newG",
                        "server_region": dota2.ServerRegion.EUROPE,
                        "game_mode": dota2.schema.DOTA_GameMode.DOTA_GAMEMODE_1V1MID,
                        "series_type": dota2.SeriesType.BEST_OF_THREE,
                        "fill_with_bots":true,
                        "intro_mode":true,
                        "allow_cheats":true
                    }

                    Dota2.createPracticeLobby(properties, function(err, data){
                        if (err) {
                            console.log(err);
                        }else{
                            console.log('lobby | Created');
                            Dota2.inviteToLobby(userId, function(err, data){
                                console.log('------------------------------ inviteToLobby -------------------------------')
                                console.log(data)
                            });

                            setTimeout(function (){
                                Dota2.launchPracticeLobby(function (c,o){

                                });
                            },20000)

                        }
                    });

### **My Result After User Accept Lobby Invite**
**members empty** 

CSODOTALobby {
  members: [],
  left_members: [],
  pending_invites: [],
  team_details: [],
  timed_reward_details: [],
  broadcast_channel_info: [],
  extra_messages: [],
  previous_series_matches: [],
  event_progression_enabled: [],
  emergency_disabled_hero_ids: [],
  mutations: [],
  lobby_id: Long { low: 674229988, high: 6332957, unsigned: true },
  game_mode: 21,
  state: 0,
  leader_id: Long { low: 368079290, high: 17825793, unsigned: true },
  lobby_type: 1,
  allow_cheats: true,
  fill_with_bots: true,
  intro_mode: false,
  game_name: 'MyLobby',
  server_region: 3,
  cm_pick: 0,
  allow_spectating: true,
  bot_difficulty_radiant: 0,
  game_version: 1,
  leagueid: 0,
  penalty_level_radiant: 0,
  penalty_level_dire: 0,
  series_type: 1,
  radiant_series_wins: 0,
  dire_series_wins: 0,
  allchat: false,
  dota_tv_delay: 1,
  lan: false,
  visibility: 0,
  previous_match_override: Long { low: 0, high: 0, unsigned: true },
  pause_setting: 0,
  bot_difficulty_dire: 0,
  bot_radiant: Long { low: 0, high: 0, unsigned: true },
  bot_dire: Long { low: 0, high: 0, unsigned: true },
  selection_priority_rules: 0,
  league_node_id: 0
}

**Comment by doroxz** [comment]
Same problem, members are empty
