### ISSUE TITLE
Cannot find module 'protobufjs'

### ISSUE THREAD

**Issue by metrogit** [Arcana/node-dota2#699]
I've done all the requirements that node-dota2 needs 
1-installed it with npm 
2-make file called config.js
3-changed line 5 to dota2
4-make an empty file called sentry

when i run the app with (node example.js) i faced this error 
![erorr](https://user-images.githubusercontent.com/59166925/123783734-eec90e00-d8eb-11eb-8264-340f2cbb66fd.PNG)
don't know how to fix it ? pls Help

**Comment by Stephanzion** [comment]
i think the reason is that steam module has been deprecated
https://www.npmjs.com/package/steam

**Comment by metrogit** [comment]
thanks dude :)
