### ISSUE TITLE
Proposal: Archive node-dota2

### ISSUE THREAD

**Issue by rjackson** [Arcana/node-dota2#700]
Hi all,

Node-dota2 began in July 2013 as a personal exploration of Dota 2's private APIs – via the Game Coordinator system / server / gateway / whatever-it-is.

Despite never intending to be anything more than an experimental alpha ([a warning that still stands to this day](https://github.com/Arcana/node-dota2/blob/bf61baeefa041e58903447caf28d2e852b1b6e69/README.md?plain=1#L9)), a wide community and ecosystem quickly grew around the package. As other commitments took me away from the project in 2016, that community continued development and maintenance of node-dota2 for many more years – until 2019 it looks like.

I'm very proud of the project and how much value node-dota2 had delivered over its 6 years of development, and the likely value it continues to deliver to any projects still using it to this day (154 weekly downloads still!).

I'm also very proud, and very thankful, to the community of contributors that have been looking after it through all those years.

That said, it looks to me like it might be time to archive the project. But I've not been involved with node-dota2 for 6 years now, so that decision is not mine to make alone.

I propose the process of archiving the project being:

- Add a note to the README noting that is is no longer maintained (perhaps linking to this issue)
- Marking the package as deprecated on npm, so any consumers of it see warnings that it is no longer maintained
- Closing all outstanding issues and pull requests
- And finally, archiving the repository in GitHub – making it read-only and closed for further contributions.

What do we think?

(cc-ing contributors with >=10 commits: @Crazy-Duck @paralin @jimmydorry @imayhaveborkedit @MeLlamoPablo @howardchung @bontscho)

**Comment by jdoran-mitacom** [comment]
I haven't been active for quite a few years now either. I defer to the others. Thanks for all the good times, team!

**Comment by jimmydorry** [comment]
I haven't been active for quite a few years now either. I defer to the others. Thanks for all the good times, team!

**Comment by bontscho** [comment]
Since i've been the last one who made the cut with 10 commits I also defer to the others. It's nice hearing from all of you and I also really enjoyed working with all of you together. Wishing all of you the best and hope to see you again some time :)

**Comment by Crazy-Duck** [comment]
I think given that seishun has archived node-steam the proper play would be to archive this project as well I suppose, especially since there's not been any active development anymore... I did massively enjoy working on this with you guys, but all good things come to an end :)

**Comment by MeLlamoPablo** [comment]
I also defer to others as I haven't been actively participating here in a long time.

I have nothing but kind words for everyone involved! It has been an absolute pleasure to collaborate with you.

This project brings so many good memories! I only did some occasional contributions, but back then I was just a kid addicted to Dota. Now I have a great job and it probably wouldn't have been possible without the experience I got from being involved here, at least not in the same way. I hope life's treating you well guys!

**Comment by paralin** [comment]
Lots of familiar names here, @jimmydorry @bontscho @Crazy-Duck @rjackson thanks for the fun times working on this & similar projects.

Note: go-dota2 is still (relatively) updated + maintained: https://github.com/paralin/go-dota2 which uses code-generation, so there's very little maintenance work.

**Comment by rjackson** [comment]
Thanks all :)

I've added a note to the README (5fe38174b0c61840e3b379d2dd8320a54ac03486) and deprecated the package on NPM.

I'll close outstanding issues, pull requests, and archive the repository at some point within the next week or so.
